### ISSUE TITLE
Center Props does not only act as initial state.

### ISSUE THREAD

**Issue by HauptmannEck** [JustFly1984/react-google-maps-api#1043]
# Issue template

## Please provide an explanation

If you pass static values into the `center` prop on `GoogleMap` component any rerendering will cause the map to move to that point no matter the current map context. A work around at this time is to put the value in a hook:
```
  const { current } = useRef({ lat: 44.076613, lng: -98.362239833 });
```

## Your Environment

os: mac/linux

node --version
10.16.0

react version
6.13.0

webpack version
4.34.0

@babel version
7.4.4

@react-google-maps/api version
1.9.7

## How is it behave?
Any changes to the Component that hold the `GoogleMap` component causes the map to move to the `center` location.

## How should it behave correctly?
Should stay in the current Map location

## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/react-google-maps-api-6kr5x?file=/src/index.js:1627-1683
Trigger issue by clicking on the map.
Workaround is shown by replacing:
```
        center={{ lat: 44.076613, lng: -98.362239833 }}
```
With:
```
       center={current}
```

**Comment by JustFly1984** [comment]
@HauptmannEck you should never pass new objects or array as props! Please use `eslint` with `eslint-plugin-react-perf` to optimize performance. You can save center object as const outside of component scope or with React.useMemo inside functional component.
