### ISSUE TITLE
Custom Map style

### ISSUE THREAD

**Issue by moesalih** [JustFly1984/react-google-maps-api#1044]
Is it possible to set the map style?

For example, to make the map monochrome.

**Comment by tartavull** [comment]
+1

**Comment by tim-kozak** [comment]
.map {
    -webkit-filter: grayscale(100%);
    -moz-filter: grayscale(100%);
    -ms-filter: grayscale(100%);
    -o-filter: grayscale(100%);
}

**Comment by Nithur-M** [comment]
Is there a way to add custom styles to water, land, roads, etc?
