### ISSUE TITLE
Component silently fails

### ISSUE THREAD

**Issue by KevinBurton** [JustFly1984/react-google-maps-api#1045]
I am using   "@react-google-maps/api": "^1.9.7". I am trying to get this component up and running. I went to the codesandbox and edited the code to use my coordinates and my key and I have verified that it works. However when I put the sample code it into my application the map returned is centered somewhere in the Pacific Ocean. There seems to be three problems with the sample for me:

1) The code
``` JavaScript
    const onLoad = React.useCallback(function callback(map) {
        const bounds = new window.google.maps.LatLngBounds();
        map.fitBounds(bounds);
        setMap(map)
    }, [])
```
shows an error in that the 'windows.google' has red squiggly line under it (I am using Visual Studio 2019) with an error that '(TS) property 'google' does not exist on type . . . .'. Puting a break in the function 'onLoad' I see the bounds returned is 180, -180. Which although I don't know what is acceptable it seems that this might be too broad of bounding box.

2) The sample in codesandbox.io sets attributes **defaultZoom** and **defaultCenter** rather than the attributes zoom and center shown in the example code.

3) When I switched to us defaultZoom and defaultCenter the property defaultZoom was accepted by the IDE I am using (again VS 2019) but defaultCenter has a red squiggly line under it indicating that defaultCenter does not exist on type . . ..

I am using a Chrome browser and since I am using Visual Studio you might have already surmised that I am on Windows 10. I am using v14.4.0 of node with version 16.13.1 of React. This project was originally generated from a template for creating a SPA with react and redux with ASP.NET then later I upgraded React to the latest. So it is probably more important to know the TypeScript version which in package.json is `"typescript": "3.6.4"`.

Like I said I cannot supply a codesandbox.io example of the error because the codesandbox.io sample that is part of the "getting started" works just fine. 

Thank you.

**Comment by JustFly1984** [comment]
@KevinBurton 
1. const bounds = new window.google.maps.LatLngBounds() requires to accept argument.
2. Every example using defaultZoom and defaultCenter props are for old unsupported react-google-maps, will not work with our library.
3. property 'google' does not exist on type . . . .'. did you install @types/googlemaps npm package? If yes, looks like you are trying to execute google api code before the script has loaded.
4. Typescript version used to build @react-google-maps/api is latest 3.9.5.
