### ISSUE TITLE
No getplaces in StandaloneSearchBox

### ISSUE THREAD

**Issue by michaelsync** [JustFly1984/react-google-maps-api#105]
Hi,

I am trying to use the SearchBox feature. I am following this example https://github.com/JustFly1984/react-google-maps-api/blob/df89a4b0a48fc085e30ac3c60c8b62bacd84e72b/packages/react-google-maps-api/src/components/places/StandaloneSearchBox.md. 

I have the code below. But I am getting this error ` Property 'getPlaces' does not exist on type 'StandaloneSearchBox'.`. 

`const searchBox = React.useRef<StandaloneSearchBox>(null);`

```
 const OnMapSearchBoxPlaceChanged = ()=> {
    if(searchBox.current != null){
      var places = searchBox.current.getPlaces();   
      if (places.length == 0) {
        return;
      }
      
      console.log(places.length);
   }
}

```
```
 <StandaloneSearchBox
      ref={searchBox}
      onPlacesChanged={OnMapSearchBoxPlaceChanged}
      >
      <input
        type="text"
        placeholder="Search" 
        className="search-box"
      />
    </StandaloneSearchBox>
```

Env:
* Windows
*  "@react-google-maps/api": "^1.2.3-alpha.3",
* node --version: v11.14.0
* react version: 16.8.6
* webpack version: 4.30.0
* @babel version: 7.1.6

**Comment by uriklar** [comment]
That's not exactly what the example does. The example uses the onLoad property. We don't support the ref property. You can set your ref in the onLoad callback

**Comment by michaelsync** [comment]
For those who are searching for the same issue. 

Here is the code that works with Typescript. I can't use the code from example. 

`const [searchBox, setSearchBox] = React.useState<google.maps.places.SearchBox>({} as google.maps.places.SearchBox);`


 ```
const OnMapSearchBoxPlaceChanged = ()=> {
    if(searchBox != null){
      var places = searchBox.getPlaces();   
      if (places.length == 0) {
        return;
      }
      
      console.log(places.length);
    }
}
```
```
<StandaloneSearchBox
      onLoad={ref => setSearchBox(ref)}
      onPlacesChanged={OnMapSearchBoxPlaceChanged}
      >
      <input
        type="text"
        placeholder="Search" 
        className="search-box"
      />
    </StandaloneSearchBox>
```

**Comment by uriklar** [comment]
Thanks for the example. I agree the fact that the example uses a class instance variable is a bit misleading. onLoad indeed can't be used with React.useRef since the resulting google maps instance isn't a dom node. 
Maybe we shouldn't call the variable ref, that way it's more clear

**Comment by Angelk90** [comment]
@michaelsync , @uriklar , @JustFly1984 : 
I tried the code posted here and that example but they don't work, they give the following error:

You could post an example of a working code on codesandbox.

![Schermata da 2020-01-08 14-45-04](https://user-images.githubusercontent.com/20476002/71982834-bd571100-3225-11ea-9675-0484c920a317.png)
![Schermata da 2020-01-08 14-45-12](https://user-images.githubusercontent.com/20476002/71982837-bdefa780-3225-11ea-823d-dbd855a3964e.png)
