### ISSUE TITLE
how to use map.fitBounds?

### ISSUE THREAD

**Issue by michaelsync** [JustFly1984/react-google-maps-api#106]
Hi,

Is there any similar feature like map.fitBounds?

I am trying to follow this example to make the StandaloneSearchBox work like this example 
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

I managed to get it until the onPlacesChanged event. 

Here is what I have so far. but I think I need to set the bound of the Map instead of SearchBox's bound. It would be great if I can get some tips. 

```

  const OnMapSearchBoxPlaceChanged = ()=> {
    if(searchBox != null){
      var placesFromSearchBox = searchBox.getPlaces();   
      if (placesFromSearchBox.length == 0) {
        return;
      }
      
      let bounds = new google.maps.LatLngBounds();
      
      placesFromSearchBox.forEach(function(place) {
        if (!place.geometry) {
          console.log("Returned place contains no geometry");
          return;
        }

      //Code to create the markers list will be here.   

        if (place.geometry.viewport) {          
          bounds.union(place.geometry.viewport);
        } else {
          bounds.extend(place.geometry.location);
        }
      });


      setsearchBoxBound(bounds);// Wrong. supposed to be Map bound
       // map.fitBounds(bounds); ??
      
    }
  }  
```

Env:

Windows
"@react-google-maps/api": "^1.2.3-alpha.3",
node --version: v11.14.0
react version: 16.8.6
webpack version: 4.30.0
@babel version: 7.1.6

**Comment by uriklar** [comment]
Depends what you want to do. Setting the bounds on a search box using ```searchBox.setBounds()``` will make sure it's results are only from the defined bounds. Setting bounds on a map will set the map's viewport to those bounds. If you have the map instance cached somewhere handy you can use that, otherwise you can use the newly added ```useGoogleMap``` custom hook that provides you with the map instance from anywhere down the component tree.

**Comment by michaelsync** [comment]
@uriklar Thanks. Any example to use useGoogleMap?
