### ISSUE TITLE
Autocomplete's getPlace() is not a function when onPlaceChanged() is executed a second time

### ISSUE THREAD

**Issue by jenridunn** [JustFly1984/react-google-maps-api#1064]
Firstly, thank you so much for all the effort you've put on this repo. Without it I couldn't been able to integrate the google maps api to my reactjs project. However I have an issue:

_Important:_
The react project implementation that is referred on this issue can be found here:  
https://codesandbox.io/embed/eager-babbage-4z366?fontsize=14&hidenavigation=1&theme=dark

The App can be accessed from here:
https://4z366.csb.app/

**Issue:**
When I call autocomplete the first time, the code works perfectly I get the response and my autocomplete state is updated. However when I change the value of the input by another random place and I click it, it stops working. I have to refresh the page (F5) for getting the autocomplete's getPlace() function working again. In a nutshell, the autocomplete only works one time.

Important:
In my localhost environment, which is the same of the codesandbox environment, when I go to the console I see a bunch of CORS errors. However my Google's Api Key has no restrictions at all. I don't know what's happening.

**Environment:**
_react version - LATEST VERSION
@react-google-maps/api  - LATEST VERSION_

**How should it behave correctly?**
Without refreshing the page I should be able to use the autocomplete's getPlace() function many times, not only once.

**Comment by jenridunn** [comment]
Hi! I've solved the issue, your plugin works perfect! Thank you!

**Comment by ugh82** [comment]
Hi @jenridunn i've got the same issue, can you drop me your workaround ?
Thanks!
