### ISSUE TITLE
change zoom by setState not working

### ISSUE THREAD

**Issue by lamvananh** [JustFly1984/react-google-maps-api#1069]
I'm using zoom state when create map:
`    <GoogleMap
      id="map-container"
      ref={map}
      zoom ={zoom}
      center={mapCenter}
    >`.
 I use control to zoom in, zoom out on the map. Then, when i click my button, i  set another value for  zoom and center state:
`setZoom(18);
setCenter({lat:21,lng:105})`
The center on map is changed a expected , but the map not response to zoom change. The current zoom level is still be keeped.

## Your Environment

os: windows

react version: 16.12
@react-google-maps/api version : 1.8.3

**Comment by jenridunn** [comment]
Could you share more of your reactjs code? I'm using useState to handle the zoom and it works fine for me.

**Comment by lamvananh** [comment]
Yes, This is my code for this function, the full component code is too long for showing here.

```
 import {
  GoogleMap,
  useLoadScript,
  Marker,
  InfoWindow,
  MarkerClusterer,
} from '@react-google-maps/api';
.....
 export function Map(){
  .....
  const [mapCenter, setMapcenter] = useState(getMarkerPosition());
  const [zoom, setZoom] = useState(17);
const renderMap = () => (
    <GoogleMap
      id="map-container"
      options={defaultMapOptions}
      mapContainerStyle={{
        height: '100%',
        width: '100%',
      }}
      zoom={zoom}
      center={mapCenter}
      onClick={e => {
        moveMarkerToNewPosition(e);
      }}
    >
        <Button
          onClick={() => {
            const defaultPosition = {
              lat: 21,
              lng: 105,
            };
            setZoom(17);
            setMapcenter(defaultPosition);
          }}
        >
          <MyLocationIcon /> <span>Go to center </span>
        </Button>
</GoogleMap>
);
return <MapContainer>{isLoaded && renderMap()}</MapContainer>
}
....
```

**Comment by JustFly1984** [comment]
@lamvananh please provide minimal reproduction in codesandbox.io

**Comment by Yvanovitch** [comment]
Hi,
You can find this [working demo](https://codesandbox.io/s/gmaps-setzoom-e7vfc?file=/src/App.js) of changing the zoom using setState.
What is more tricky is to set the zoom in a "onZoomChanged" method, as you need to first change myZoom to another value before applying the wanted one in a timeout. I couldn't find a better approach. [Here is the demo](https://codesandbox.io/s/gmaps-setzoom-on-zoom-changed-3gmvt?file=/src/App.js).

**Comment by kellystrauch** [comment]
I had this issue as well.  Using setState to set the zoom worked for me if I _only_ changed the zoom using setState, but the minute I tried zooming in or out by clicking on the + or - minus button and _then_ tried to change the zoom using setState, React seemed to believe that the zoom was still at whatever I had set it to last using setState, so the zoom wouldn't update.

All that said, the workaround provided by Yvanovitch (changing zoom to a different value using setState, then applying the zoom value you actually want with a setState in a setTimeout) worked for me.  Thank you, Yvanovitch!

**Comment by jantoodre** [comment]
You could try syncing the state zoom with the zoom on the map instance.
So in your case perhaps something like this could work:

<details>
  <summary>Code snippet</summary>

```typescript
/* ..... */
export function Map(){
	/* ..... */
	const [map, setMap] = useState(null); // map instance
	const onLoadMap = useCallback(setMap, []); // set map once map has loaded
	const [mapCenter, setMapcenter] = useState(getMarkerPosition());
	const [zoom, setZoom] = useState(17);


	const renderMap = () => (
		<GoogleMap
			id="map-container"
			options={defaultMapOptions}
			mapContainerStyle={{
				height: '100%',
				width: '100%',
			}}
			zoom={zoom}
			center={mapCenter}
			onClick={e => {
				moveMarkerToNewPosition(e);
			}}
			onLoad={onLoadMap} // once map is loaded, this will get called
			onZoomChanged={() => { // when zoom changes
				if (map === null) { // make sure we have the instance of the map
					return;
				}
				if (map.zoom !== zoom) { // sync map zoom with with the state zoom
					setZoom(map.zoom)
				}
			}}
		>
			<Button
				onClick={() => {
					const defaultPosition = {
					lat: 21,
					lng: 105,
					};
					setZoom(17);
					setMapcenter(defaultPosition);
				}}
			>
				<MyLocationIcon /> <span>Go to center </span>
			</Button>
		</GoogleMap>
	);
	return <MapContainer>{isLoaded && renderMap()}</MapContainer>
}
/* ..... */
```
</details>

For me this approach worked when updating zoom with my own controls and google map +/- buttons interchangeably. Hopefully this helps!
