### ISSUE TITLE
Marker Clusterer required props

### ISSUE THREAD

**Issue by matheusgrieger** [JustFly1984/react-google-maps-api#107]
# Please provide an explanation

## Your Environment

os: mac

node --version: v10.15.0

react version: 16.8.3

webpack version: 4.28.3

@babel version: 7.2.2

@react-google-maps/api version: 1.2.3

## How is it behave?

![image](https://user-images.githubusercontent.com/6992464/56655872-54fdda80-666a-11e9-8929-95e18876aeec.png)

When using `MarkerClusterer` with props `style`, `averageCenter`, `enableRetinaIcons`, `gridSize`, I get errors saying that most of other props are also required. Checking the source file indeed the interface has almost all members as required, except for `options`.

## How should it behave correctly?

Props such as the ones in the image above (`clusterClass`, `ignoreHidden`, etc) should have a default value and not be required to inform, otherwise I would need to pass over 10 props every time I use a clusterer.

**Comment by JustFly1984** [comment]
Published 1.2.3-alpha.5
