### ISSUE TITLE
How to traverse a car on map by longitude and latitude data?

### ISSUE THREAD

**Issue by robin-chilliapple** [JustFly1984/react-google-maps-api#111]
I want to traverse a car on the map. I am receiving data from API in 10 seconds interval. The data format is: 

> var pathCoords = [
> 			{
> 			"lat": 8.893260000000001,
> 			"lng": 76.61427
> 			},
> 			{
> 			"lat": 8.894430000000002,
> 			"lng": 76.61418
> 			},
> 			{
> 			"lat": 8.89484,
> 			"lng": 76.61416000000001
> 			}
> ]
> 

I want to create a path from source to destination and traverse a car on the created route by these data. Could you please provide me some example of code for it or some guidance and resources? It would be great for me thanks in advance. 

I want to create like this: http://www.geocodezip.com/v3_animate_marker_directions.html

**Comment by uriklar** [comment]
Please use Spectrum for usage questions:
https://spectrum.chat/react-google-maps
