### ISSUE TITLE
initial mapTypeId set to "satellite" is ignored

### ISSUE THREAD

**Issue by capaj** [JustFly1984/react-google-maps-api#1142]
![image](https://user-images.githubusercontent.com/1305378/88147881-1acd1100-cbfe-11ea-809f-96ba9a9f0ac1.png)

if I change it when component it mounted, it switches to satellite correctly, but when I set it before map component mounts it is ignored and I see the roadmap instead.

Expected result:
I see `satellite`

**Comment by JustFly1984** [comment]
@capaj please provide minimal reproduction in codesandbox.io

**Comment by kenjdavidson** [comment]
I found that this was a problem too, even though:

- The props are !==
- `map.setMapTypeId()` is being called on the reference

It still leaves the default Roadmap.  It looks like this is something in the google library and not directly related to this library.

You can get around this by passing it in through `options` instead:

```
const options = {
  mapTypeId={google.maps.MapTypeId.SATELLITE}
}
```

**Comment by danielrmartins** [comment]
This works for me:

- `options={{ mapTypeId: 'satellite' }}`

**Comment by capaj** [comment]
Seems like on init it just needs to be passed from props to that options object.

**Comment by kenjdavidson** [comment]
@capaj that's a great avatar and comment!

**Comment by kuzkokov** [comment]
hey guys, so why is this issue closed? it doesn't seem to be fixed

**Comment by powah** [comment]
Yeah, I can confirm it's still a bug with v2.2.2

**Comment by rafalkrupinski** [comment]
I use
```js
        options={{
            mapTypeId: 'hybrid',
        }}
```
but if I change it in the UI and than cause React to re-render, it goes back to hybrid.
I don't see any option to react to user changing it or make it use only as an initial value.
