### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by monkeysuffrage** [JustFly1984/react-google-maps-api#115]
I keep getting this message when I run sample code I find here.
Can someone point out what I'm missing?

ReferenceError: google is not defined
App
  37 | <DrawingManager
  38 | 	options={{
  39 | 		drawingControlOptions: {
> 40 | 			drawingModes: [
  41 | 				google.maps.drawing.OverlayType.RECTANGLE,
  42 | 			]
  43 | 		}

**Comment by JustFly1984** [comment]
Basically you are rendering a component before google-maps script loaded, or at SSR or static site generator, therefore google object is not available yet or at all. You need to render <DrawingManager /> component only if `typeof document !== 'undefined'` , or use string value instead of google.maps.drawing.OverlayType.RECTANGLE

**Comment by uriklar** [comment]
Does this happen in codesandbox or in local dev env?

**Comment by JustFly1984** [comment]
you can substitute `google.maps.drawing.OverlayType.RECTANGLE` with lowercase `'rectangle'` string BTW

**Comment by TeerawatN** [comment]
> @monkeysuffrage you can substitute `google.maps.drawing.OverlayType.RECTANGLE` with lowercase `'rectangle'` string.

I'm the same is google is not defined and  Let's try to lowercase `'rectangle'` string. 
error is TypeScript error: Type '"rectangle"' is not assignable to type 'OverlayType'.
how can i do?



drawingControlOptions: {
          drawingModes:['rectangle']
        }

**Comment by uriklar** [comment]
@TeerawatN 
It's working for me in this codesandbox (with the original all caps RECTANGLE):
https://codesandbox.io/s/react-google-maps-api-drawing-manager-jtrp1l

Maybe you can use that as a reference to see what you might be missing
