### ISSUE TITLE
How to detect when an API KEY is missing

### ISSUE THREAD

**Issue by nwaughachukwuma** [JustFly1984/react-google-maps-api#116]
Hi @JustFly1984 and everyone, is there a way or an event I can hook into to know when API key is not present?

I want to be able to raise a modal in App as warning/info asking the users to enter their API key to use the App.

Thanks.

**Comment by uriklar** [comment]
Where are the users entering their api key in your app? Can't you just check it there?

**Comment by JustFly1984** [comment]
It is not a bug in `@react-google-maps/api`, but architecture issue of underlying  `google-maps-api and google cloud in general` Either your key is valid, either not. anyway you will get an error message to the console if it is broken, and gray screen with error message instead of the map

**Comment by nwaughachukwuma** [comment]
Thanks @JustFly1984 and @uriklar, and sorry for my late response. 

So I was working on a project for an organization and I was using my API key. I had shared the project with their Tech. team with my API key still in the codebase. Reason is that I didn't want them to be confounded by the view they get when the App loads without a key, so I left my key in there, uncomfortably though.

I was thinking of making a new commit with my API key removed and a sort of a checker that asks them to insert an API key if the parameter is an empty string or as implemented on the gatsby example where the check is for key length >= 38.

I think I will go with the gatsby example for this. Thanks for the help
