### ISSUE TITLE
Map instance Persistence is broken, UI breaks when useSameInstance is set to true

### ISSUE THREAD

**Issue by xalisys** [JustFly1984/react-google-maps-api#117]
# Please provide an explanation
This is change in rendering mechanism for map div element as compared to old react-google-maps api which use to render two divs for map i.e. container-div & map-div. but this new @react-google-maps/api, only render one div, which is breaking instance persistence mechanism in Single Page Applications (SPAs). The Google map component has "useSameInstance" flag which is supposed to persist map-instance when you unmount map component and use same map instance when mounted again in client route navigation when reuseSameInstance is set to true, the instance restore behavior is broken due to this change. Se the following image.
## Your Environment
Any
os: mac/linux/windows/android/ios
Platform independent.
node --version
Any
react version
16.8.6
webpack version
29.x
@babel version
Any
@react-google-maps/api version

## How is it behave?
Doesn't restore persisted instance properly which breaks UI for map canvas.
## How should it behave correctly?
![rgm vs rgmi](https://user-images.githubusercontent.com/1515257/57318957-75498280-70c9-11e9-8cb4-1c3d49bf6dd6.png)

**Comment by JustFly1984** [comment]
@xalisys  Can you please provide a minimal example at codesandbox or error stack trace?

**Comment by JustFly1984** [comment]
in 9.4.5 you could have a single map component per GoogleMap instance, now you can have as many as you need. mapContainer was part of <script> loading. I had to get rid of it to simplify architecture according new functionality. Please make a PR, and I will merge it and publish new version ASAP.

**Comment by JustFly1984** [comment]
in 9.4.5 this container element was part of script loading algorithm, but now we externalized it to <LoadScript /> component due to change in architecture to support multiple <GoogleMap /> instances as children to <LoadScript /> component. Please make a PR according new JSX structure.

**Comment by xalisys** [comment]
@JustFly1984  react-google-maps had two props (mapElement,containerElement) for map element to render these two divs, but the new map one don't have such option instead it accepts mapContainerStyle prop, which is applied to map div internally. I originally developed, "reUseSameInstance" feature here, which rely on the virtue of having two dives.

Here is the code which is causing the issue.
src/utils/instance-persistance.ts (line: 94)

````
if (mapContainer && mapContainer.children && mapContainer.children[0]) {
    hiddenContainer.appendChild(mapContainer.children[0])
  }
````
 
Fix: 
  
````
if (mapContainer) {
    hiddenContainer.appendChild(mapContainer)
}
````

I can create minimal repo or PR for fix, but before jumping to solution i have question, was there any specific reason to change the rendering behavior of map element? If you don't the the reason then we can probably go with PR for for fix.

**Comment by JustFly1984** [comment]
published alpha.11

**Comment by JustFly1984** [comment]
@xalisys please confirm the bug is fixed and close an issue if it does.

**Comment by xalisys** [comment]
issue is fixed in updated version, closing this bug.

**Comment by JustFly1984** [comment]
@xalisys  Is it still fails?

**Comment by xalisys** [comment]
@JustFly1984, it fixed the UI part, but failing on functionality after restoring instance, there is more to it, there is essentially  problem map rendering, i am investigating, will create another PR if needed.

**Comment by JustFly1984** [comment]
It is sad that google-maps-api is not open-source itself.

**Comment by JustFly1984** [comment]
@xalisys Should we disable instance persistence for 1.2.3? I'm going to publish working version, but I do not want to confuse users with features which is incomplete

**Comment by xalisys** [comment]
@JustFly1984  yeah, for now we can disable that.

**Comment by JustFly1984** [comment]
have removed feature in 1.2.3

**Comment by nggonzalez** [comment]
@JustFly1984 Is there an ETA on when instance persistence will be added to the lib?
I may be wrong, but from what I understand from Google's new billing policies, it seems that every component mount will trigger billing:

> A web page or application that displays a map using the Maps JavaScript API. A map is created with the google.maps.Map() class.
https://developers.google.com/maps/documentation/javascript/usage-and-billing

If calling `google.maps.Map()` counts as a map load, then this simplified build will drastically increase billing costs as `getInstance()`, which calls `new google.maps.Map()`, gets called on every `componentDidMount`

**Comment by JustFly1984** [comment]
@nggonzalez  Sorry, but if you need this functionality - you need to code it yourself and make a PR

This was not done, cos google maps API is closed source, and we can't reverse engineer it yet.
