### ISSUE TITLE
LoadScript error when unmounting

### ISSUE THREAD

**Issue by seansheds** [JustFly1984/react-google-maps-api#118]
I have a view that loads the map and that works fine, but when I switch to another view that unmounts the map I'm getting the following error that crashes the app. This is urgent and if I can't get it resolved I won't be able to use this google map component. Thanks!

react.production.min.js:145 TypeError: Cannot read property 'includes' of undefined
    at filter (LoadScript.js:249)
    at Array.filter (<anonymous>)
    at LoadScript._this.cleanup (LoadScript.js:248)
    at LoadScript.componentWillUnmount (LoadScript.js:336)
    at Ig (react.production.min.js:148)
    at Jg (react.production.min.js:151)
    at $c (react.production.min.js:186)
    at Xc (react.production.min.js:180)
    at ra (react.production.min.js:179)
    at eh (react.production.min.js:191)

**Comment by seansheds** [comment]
It fails on line marked line. ---->>>

Array.prototype.slice.call(document.getElementsByTagName("link")).filter(function filter(link) {
        link.href === "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans";
      }).forEach(function forEach(link) {
        if (link.parentNode) {
          link.parentNode.removeChild(link);
        }
      });
      Array.prototype.slice.call(document.getElementsByTagName("style")).filter(function filter(style) {
---->>>        return style.innerText.includes(".gm-");
      }).forEach(function forEach(style) {
        if (style.parentNode) {
          style.parentNode.removeChild(style);
        }
      });

**Comment by xalisys** [comment]
@seansheds  can you provide little more details, or some minimal reproducible repo?

**Comment by JustFly1984** [comment]
@yes, minimal reproduction would be helpful. On other hand it signals to me that you have empty <style/> tag somewhere in your html/jsx. 
I think that is a main reason in your codebase, you can fix yourself by removing empty <style tag, or make it non empty.

You can console.log the style object, before an error line to see exact style tag causing an issue.

**Comment by seansheds** [comment]
I can't post code because of client restrictions.

This is a large codebase and I did find some of the style tags don't have in innerText property. I can't clean all these up because they are in shared components.

Changing the line to the following resolves it, but it doesn't help when npm install is run on the server.

return style.innerText && style.innerText.includes(".gm-");

**Comment by JustFly1984** [comment]
@seansheds ok, wait, I'm publishing new version with bug fix

**Comment by seansheds** [comment]
Awesome! Thanks!!

**Comment by JustFly1984** [comment]
I have published 1.2.3-alpha.9, please test

**Comment by seansheds** [comment]
Tested. Thanks!
