### ISSUE TITLE
Google Map not updated when we change the center postion after onClick(I have used state values), please do the needful, showing empty screen after changed center position

### ISSUE THREAD

**Issue by Mekala-palaniyappan** [JustFly1984/react-google-maps-api#1199]
I am using @react-google-maps, the map initially loaded good, i have changed the latitude and longitude using onClick event in GoogleMap using state, after that the map displaying empty screen, can u pls help me?

![Screenshot 2020-07-30 at 9 33 22 AM](https://user-images.githubusercontent.com/42611462/88879436-e1bd1e00-d247-11ea-9bae-debe70e0425d.png)
![Screenshot 2020-07-30 at 9 34 03 AM](https://user-images.githubusercontent.com/42611462/88879442-e5e93b80-d247-11ea-957c-67643eb1a0b3.png)

![Screenshot 2020-07-29 at 7 18 29 PM](https://user-images.githubusercontent.com/42611462/88811610-679f8180-d1d4-11ea-8df4-1babfa520558.png)

**Comment by JustFly1984** [comment]
@Mekala-palaniyappan please do not post unformatted code in to the issue. Instead kindly provide an example in codesandbox.io

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984 :
I have updated the code format in the posted message. Can you please check it. I need to complete ASAP, can you please guide me this.

**Comment by JustFly1984** [comment]
@Mekala-palaniyappan I can't run this code and see what is wrong. If you provide miimal reproduction in codesandbox.io, I'll send you the link with fixed version.

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984 :

Please check this in  [https://codesandbox.io/s/react-google-maps-api-u9zp1?file=/src/index.js](url).

After changed position it will show the blank screen

**Comment by Mekala-palaniyappan** [comment]
Please use your API key @JustFly1984 in this https://codesandbox.io/s/react-google-maps-api-u9zp1?file=/src/index.js

**Comment by JustFly1984** [comment]
@Mekala-palaniyappan https://codesandbox.io/s/react-google-maps-api-lfxmw?file=/src/index.js

**Comment by JustFly1984** [comment]
@Mekala-palaniyappan PS you can use empty string as google api key in codesandbox.io

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984:
I have checked it, Thanks for your time.  Did you changed the position ? after i changed the position in google maps, showing blank screen again

**Comment by Mekala-palaniyappan** [comment]
[Screen Recording 2020-07-30 at 10.47.21 AM.zip](https://github.com/JustFly1984/react-google-maps-api/files/4998943/Screen.Recording.2020-07-30.at.10.47.21.AM.zip)

Please check this screen recorder video @JustFly1984

**Comment by JustFly1984** [comment]
@Mekala-palaniyappan https://codesandbox.io/s/react-google-maps-api-lfxmw?file=/src/index.js have fixed your bug, you need to keep marker position separate from map center

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984 :
I have checked your code, but 
1. The **marker** icon not visible,
2. After changed position, same blank screen.
[Screen Recording 2020-07-30 at 11.44.38 AM.zip](https://github.com/JustFly1984/react-google-maps-api/files/4999163/Screen.Recording.2020-07-30.at.11.44.38.AM.zip)

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984 :
Fixed that marker icon not visible issue,
Not updated when component mounted
added this in **showLocation**

**setMarkerPosition({
      lat: position.coords.latitude,
      lng: position.coords.longitude,
    });**


Hey cool man, Dragging marker perfectly updating. Only one issue now occurring, that is when clicking on Map, 
**onMapClick** not updated the position for Marker and center, showing blank screen. Hope you got it

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984 :
Is there any update?
[https://github.com/JustFly1984/react-google-maps-api/issues/1199#issuecomment-666102328?](url)

**Comment by Mekala-palaniyappan** [comment]
@JustFly1984 :
Second one is not yet work
[https://github.com/JustFly1984/react-google-maps-api/issues/1199#issuecomment-666149787](url)
