### ISSUE TITLE
[Feature Request] Make the context available in the API to allow access to additional libraries like 'geometry' from other components

### ISSUE THREAD

**Issue by Rennzie** [JustFly1984/react-google-maps-api#125]
# Please provide an explanation

It would be useful if we could access the google object from a useContext hook. I think this would mean that we can then access additional libraries like geometry

## Your Environment

os: mac

node10.15.1

react version 16.8.6

webpack version (using create react app)

@babel version (again using create react app)

@react-google-maps/api version 1.2.3-alpha.9

## How is it behave?

Cannot find it in the docs so Im guessing its not available

## How should it behave correctly?

something like 
``` javascript

import React, { useContext } from 'react';
import { MapContext } from '@react-google-maps/api';

function ContextUsingComponent() {
  const google = useContext(MapContext);

  // a function to leverage the geometry api added in LoadScript
  const polyArea = latLng => {
    const area = google.maps.geometry.spherical.computeArea(latLng);
    return area;
  };

  return(...)
}
```

I tried using the already existing MapContext in the src directly but it look like this only puts `google.maps.Map` onto the context so `google.maps.geometry` is not available.

**Comment by JustFly1984** [comment]
You can get access google object from `window.google` at the same time after onLoad callback is fired. There is single `google` object per browser tab instance anyway, but there is unique `map` element for each `<GoogleMap />` component. 
The context's `map` object is an instance of the google.maps,Map class, not just the reference.

**Comment by Rennzie** [comment]
Ok thanks @JustFly1984  thats clear now.  So the best way would be to access if from `window.google` when I need it?

I would be keen to contribute but I'm pretty new to open source and development in general. Maybe I can help with the docs? Do you have any pointers or suggestions?

**Comment by JustFly1984** [comment]
@Rennzie We do have docs auto-generated from md files by `react-styleguidist` and `react-docgen-typescript`, you can fork the repo, and run `yarn docs:dev` in `./packages/react-google/maps/api`

Docs require some attention to details.

You can make new git branch in your forked repo, and make a Pull Request with changelog description.

If you are keen to join as maintainer, we have slack channel and spectrum community.

If you want to add more value to the project, please look at #122 issue, we need to make E2E tests.

**Comment by Rennzie** [comment]
ok thank @JustFly1984. I've never contributed on a project or used Typscript so would need some guiding. I am keen though.

**Comment by uriklar** [comment]
Hi @Rennzie! 
This is a pretty easy project to contribute to. Feel free to join out [slack channel ](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtNTk2ODk3OTQ2OTYyLWU2ZGMyMjI1ZDQ4NmE3MjRmNGRjYjBjOGEzMTVjMTQyMGYwNzVmMTRkZDAwNzEwZGNkNGNhODBiMWM3ZDUyYTk) where i'd be happy to assist with getting you started with contributing

**Comment by Rennzie** [comment]
Thanks @uriklar I'll do that.
