### ISSUE TITLE
[drawing manager] [type error] Type 'string' is not assignable to type 'OverlayType' error with TS project

### ISSUE THREAD

**Issue by Rennzie** [JustFly1984/react-google-maps-api#126]
# Please provide an explanation

 I am getting a `Type 'string' is not assignable to type 'OverlayType'.` error in my typescript project when I am using the drawing manager. 

## Your Environment

os: mac

node --version
10.15.1
react version
16.8

@react-google-maps/api version
latest

## How is it behave?
The problem appears to point the the OverlayType, which from as far as I can tell does include 'POLYGON' in it. Im at a bit of a loss as this was working fine before I converted my project to Typescript. Any help would be great. 

My drawing manager component is declared like this: 
```javascript
 return (
    <DrawingManager
      drawingMode='POLYGON'
      onLoad={drawingManager => {
        console.log(drawingManager.getDrawingMode());
      }}
      onPolygonComplete={polygon => console.log('the new array is', polygon.getPath())}
    />
  );
```

**Comment by JustFly1984** [comment]
Have you tried lowercase 'polygon' string as it is required by google maps api reference?

```
return (
    <DrawingManager
      drawingMode='polygon'
      onLoad={drawingManager => {
        console.log(drawingManager.getDrawingMode());
      }}
      onPolygonComplete={polygon => console.log('the new array is', polygon.getPath())}
    />
  );
``

https://developers.google.com/maps/documentation/javascript/reference/drawing#DrawingManagerOptions.drawingMode

**Comment by JustFly1984** [comment]
PS

If you just ```console.log(google.maps.drawing.OverlayType.POLYGON)``` in browser console, you'll get returned value as lowercase `'polygon'` string

**Comment by Rennzie** [comment]
Thanks, I can work with that.
