### ISSUE TITLE
GoogleMap inside iframe issues

### ISSUE THREAD

**Issue by regulyarniy** [JustFly1984/react-google-maps-api#127]
## Your Environment

any environment\codesandbox

react version 16.8.6

@react-google-maps/api version 1.2.3-alpha.11

## How is it behave?

Hello! First, thx for nice library, you are doing big work here

If GoogleMap is nested inside iframe it don't get styles(all controls are hidden because no styles) and dragging not working

Example: https://codesandbox.io/s/googlemap-inside-iframe-issues-bbd8b 

## How should it behave correctly?

It should load styles and mouse\touch handlers inside iframe
I think it is related to Google API behavior, but it would be nice if  we together can find workaround

I made some exploration and maybe this could help: https://stackoverflow.com/questions/18190813/how-to-load-a-google-map-in-an-iframe-with-javascript
If LoadScript could determine if maps inside an iframe then it could pass styles or handlers inside this iframe?

**Comment by JustFly1984** [comment]
@regulyarniy I had no time to dig deep, but I think your issue somewhere with `react-frame-component` you are using, cos looking at your  DOM tree of iframe in sandbox - there is an <img /> tag instead of inner iframe.

<img width="1885" alt="Screenshot 2019-05-18 14 39 51" src="https://user-images.githubusercontent.com/2255993/57969083-30500680-797b-11e9-81a6-a8a56300924f.png">
<img width="1883" alt="Screenshot 2019-05-18 14 41 51" src="https://user-images.githubusercontent.com/2255993/57969084-30500680-797b-11e9-94a6-76ae0ef3c44d.png">

**Comment by regulyarniy** [comment]
@JustFly1984 I don't think the problem is in the `react-frame-component`
I modified first example, where I rendered `GoogleMap` with `createPortal` inside manually created iframe without  `react-frame-component`. It crashes with error, but if you close error overlay then you see it rendered same img tag and no iframe.
Link: https://codesandbox.io/s/googlemap-inside-iframe-issues-j655x
Is there any correct way to get `GoogleMap` inside iframe?
Of course it could be used with workarounds, but it don't looks good and it's not a right way I think. Styles cloned from document.head to iframe.head and events passed to document from frame.contentDocument. With effects like this:
```javascript
useEffect(() => {
    const iframe = document.querySelector(`#frame`);
    const getStyles = () => document.head.querySelectorAll(`style`);
    const updateIframeStyles = styles => {
      Array.from(styles).forEach(style => {
        iframe.contentDocument.head.appendChild(
          style.parentNode.removeChild(style)
        );
      });
    };
    updateIframeStyles(getStyles());
    const observer = new MutationObserver(mutations => {
      Array.from(mutations).forEach(() => updateIframeStyles(getStyles()));
    });
    const observerConfig = { childList: true };
    observer.observe(document.head, observerConfig);
    return () => observer.disconnect();
  }, []);
```
```javascript
  useEffect(() => {
    const iframeDocument = document.querySelector(`#frame`).contentDocument;
    const getNewEvent = event => {
      if (event.type.match(/mouse/)) {
        return new MouseEvent(event.type, event);
      } else if (event.type.match(/touch/)) {
        return new TouchEvent(event.type, event);
      } else {
        return new Event(event.type, event);
      }
    };
    const proxyEventHandler = event => {
      document.dispatchEvent(getNewEvent(event));
    };
    const eventTypes = [
      `mousemove`,
      `mouseup`,
      `mousedown`,
      `touchmove`,
      `touchend`,
      `touchstart`,
      `touchcancel`
    ];
    eventTypes.forEach(eventType => {
      iframeDocument.addEventListener(eventType, proxyEventHandler);
    });
    return () => {
      eventTypes.forEach(eventType => {
        iframeDocument.removeEventListener(eventType, proxyEventHandler);
      });
    };
  }, []);
```
Помоги пожалуйста 😥

**Comment by JustFly1984** [comment]
Possibly there is some security measures made by google-maps-api team to prevent exactly this behavior. Please google or post your question at stackoverflow, and make an issue at google-maps-api issue tracker. We have no img replacement in our lib.

**Comment by xalisys** [comment]
@regulyarniy  in you codesandbox example, if you comment out this line, it works:
`frm.setAttribute("src", "http://google.com/");`

The reason being that is, "maps.googleapis.com" has response header as following:
`x-frame-options: SAMEORIGIN`
Which mean you can only open iframs from same domain.

Hope this helps!

**Comment by JustFly1984** [comment]
Can we close an issue?

**Comment by regulyarniy** [comment]
@xalisys yeah, my mistake, loading is fixed. thanks. but the issue still persists with dragging and styles. 
dragging is working only if mouse pointer is moving on root document, not inside iframe.
styles also not applied correctly, as you can see.
I updated the sandbox: https://codesandbox.io/s/googlemap-inside-iframe-issues-j655x

**Comment by regulyarniy** [comment]
@JustFly1984 Thanks for your attention. I close the issue. It's Google API bug. I created sandbox without your library and it shows same behavior: https://codesandbox.io/s/googlemap-inside-iframe-native-loading-dvr81
