### ISSUE TITLE
Add mouse down and mouse up events

### ISSUE THREAD

**Issue by herzuull** [JustFly1984/react-google-maps-api#131]
# Adding mouseDown and MouseUp Events 

On mobile device we are allowed to long-click to add a marker below the spot we clicked on.
Unfortunately the two event we need to create a long click : mousedown and mouseup are not implemented yet.

I have forked the project to test it myself, and as the two methods are already in the Google Maps API, it's not a big deal.

Adding 
```JavaScript
const eventMap = {
  ...,
  onMouseDown: "mousedown",
  onMouseUp: "mouseup",
  ...
};
```

Open for any comments.

**Comment by JustFly1984** [comment]
@herzuull  Please open PR, and I will publish new version.

**Comment by herzuull** [comment]
@JustFly1984 done !
https://github.com/JustFly1984/react-google-maps-api/pull/133

**Comment by herzuull** [comment]
Thanks !
