### ISSUE TITLE
How to make a moving marker like Uber cars? 

### ISSUE THREAD

**Issue by robin-chilliapple** [JustFly1984/react-google-maps-api#132]
I create a marker like this:
<GoogleMapReact bootstrapURLKeys={{ key: GOOGLE_MAP_API_KEY }} center={this.props.center} zoom={this.props.zoom} options={createMapOptions}> <Marker lat={lat} lng={lng} marker_img={IMG} /> </GoogleMapReact>

Now how do I move this marker like a car on location updates?
I use states to update the position of the marker but it doesn't animate. How do I do this?

My issue is when a latlng is updated the marker jumps from one place to another but I want it to move like a car. Have you ever tracked an Uber ride on the web? something like that.

![car animation](https://user-images.githubusercontent.com/17025274/58420747-c555ac80-80ab-11e9-8c66-8939baf2bf03.gif)

This above gif might help you understand my requirement better.

**Comment by uriklar** [comment]
I think you need a combination of location and heading (the direction in angles the car is going to)
You can continue this discussion in this simmilar thread:
https://spectrum.chat/react-google-maps/general/how-to-traverse-a-car-on-the-map-by-longitude-and-latitude-data~21a5d7ba-598f-428c-99a8-2bedee6860c8

Or post your own on our specturm channel. The issues are for bugs/feature requests
