### ISSUE TITLE
Add smooth center change

### ISSUE THREAD

**Issue by regulyarniy** [JustFly1984/react-google-maps-api#134]
How about adding `smoothPan` (`boolean`) prop for GoogleMap component? When value is `true` `center` prop change uses smooth map.panTo method to move the camera (https://developers.google.com/maps/documentation/javascript/reference/map#Map.panTo). 
I could make the PR if it is sounds interesting.

**Comment by JustFly1984** [comment]
@regulyarniy Sure, waiting for your PR.

**Comment by regulyarniy** [comment]
@JustFly1984 https://github.com/JustFly1984/react-google-maps-api/pull/136

After looking at the code architecture, I decided to implement `smoothCenter` prop with same type-shape as `center` for minimal code changes.

**Comment by FredyC** [comment]
@regulyarniy Can you elaborate on some practical example where it might be useful? I mean panning is usually an imperative action caused by the user doing something. Doesn't feel right to be re-rendering whole GoogleMap component because of that.

If can use React Hooks, you can have something like following instead. It's composable and doesn't limit you to trigger panning from the outside of GoogleMap component. You can include that hook 

```tsx
export function useMapPanning() {
  const mapRef = useGoogleMap()

  const prevGps = React.useRef<Maybe<GeoPoint>>(null)

  const panToGps = (gps: GeoPoint) => {
    if (!mapRef) {
      return
    }
    const latLng = gpsToLatLngLit(gps)
    mapRef.panTo(latLng)
    prevGps.current = gps
  }

  return (gps: GeoPoint) => {
    const prev = prevGps.current
    if (
      !prev ||
      (prev.latitude !== gps.latitude && prev.longitude !== gps.longitude)
    ) {
      panToGps(gps)
    }
  }
}

// and then use it in any component like...

const panTo = useMapPanning()

const onClick = () => {
  panTo({ latitude, longitude })
}
```

It also takes care of remembering previous pan position so it's not planning to the same location over again.

**Comment by regulyarniy** [comment]
@FredyC This can be used in the same way as `center` to switch the camera, but if the points are next to each other, the camera will be moved smoothly. This does not trigger the rerender of the component. A practical example: you have a list of markers on the map that center the camera on it with a click on marker. If you want to smoothly switch the camera now, then you need to create additional hook\hoc\wrapper: set callback instanse loaded, save the instanse to internal state, call panTo for the instance and etc.. - its not obvious, and will be able to do with single prop after this proposal will be implemented

Example sandbox: https://codesandbox.io/s/markers-center-on-click-rf2i8

**Comment by FredyC** [comment]
@regulyarniy I do understand what panning does in comparison to center, but I find your approach terribly limiting. You have to write your pan value to some store (PITA with Redux), re-render component that contains GoogleMap to pass the new value in it. Ultimately it will call imperative `panTo` method on map instance. It's kinda crazy when you think about it: *click on marker (imperative) -> write to store -> rerender map with a new value (declarative) -> call panTo (imperative again)*

That hook I suggested above could be even part of this package. The path will change to *click on marker -> call panTo*. No need to go around really.

```jsx
function PannableMarker({ position }) {
  const panTo = useMapPanning()
  return <Marker position={position} onClick={() => panTo(position)} />
}
```

**Comment by UltimateForm** [comment]
what's the status of this?

**Comment by JustFly1984** [comment]
PR is closed due to our plan to stick as close to bare Google Maps API as possible.
