### ISSUE TITLE
Cannot rotate ground overlay in React Google Maps - property “bearing ” is ignored

### ISSUE THREAD

**Issue by carlosedof** [JustFly1984/react-google-maps-api#1349]
# Issue template

## Please provide an explanation

I need to place a image with fixed bounds but it has a rotation, because its like a blueprint of a building. To achieve this, I am using GroundOverlay. My problem is, when I set a property option with bearing property, this property is ignored. It does not rotate.

This is where I found bearing property/fn.
https://developers.google.com/android/reference/com/google/android/gms/maps/model/GroundOverlayOptions#bearing(float)

## Your Environment

os: mac

node 13.7

react 16.8.4

```
<LoadScript googleMapsApiKey="API-KEY">
        <GoogleMap mapContainerStyle={containerStyle} center={center} zoom={18}>
            <GroundOverlay
              key={"url"}
              url={planta}
              options={{ bearing: 30 }}
              bounds={{
                north,
                south,
                east,
                west,
              }}
            />
        </GoogleMap>
</LoadScript>
```
 
If anyone know how can I rotate that image, will be appreciated. I need a solution that could be dynamic and not for that specific image, cause the idea is to render it from backend with the property bearing.

Thank you!!

**Comment by JustFly1984** [comment]
please provide minimal reproduction in codesandbox.io

**Comment by carlosedof** [comment]
> please provide minimal reproduction in codesandbox.io
https://codesandbox.io/s/compassionate-jackson-ul6ws?file=/src/App.js

I need to somehow rotate the image to place blueprint exactly on top of some building, but the bounds of image and the placements must remain even if I change zoom level.

Thanks!!

**Comment by tkornyk** [comment]
> > please provide minimal reproduction in codesandbox.io
> > https://codesandbox.io/s/compassionate-jackson-ul6ws?file=/src/App.js
> 
> I need to somehow rotate the image to place blueprint exactly on top of some building, but the bounds of image and the placements must remain even if I change zoom level.
> 
> Thanks!!



> > please provide minimal reproduction in codesandbox.io
> > https://codesandbox.io/s/compassionate-jackson-ul6ws?file=/src/App.js
> 
> I need to somehow rotate the image to place blueprint exactly on top of some building, but the bounds of image and the placements must remain even if I change zoom level.
> 
> Thanks!!

Did you manage to solve the  problem?

**Comment by carlosedof** [comment]
> > > please provide minimal reproduction in codesandbox.io
> > > https://codesandbox.io/s/compassionate-jackson-ul6ws?file=/src/App.js
> > 
> > 
> > I need to somehow rotate the image to place blueprint exactly on top of some building, but the bounds of image and the placements must remain even if I change zoom level.
> > Thanks!!
> 
> > > please provide minimal reproduction in codesandbox.io
> > > https://codesandbox.io/s/compassionate-jackson-ul6ws?file=/src/App.js
> > 
> > 
> > I need to somehow rotate the image to place blueprint exactly on top of some building, but the bounds of image and the placements must remain even if I change zoom level.
> > Thanks!!
> 
> Did you manage to solve the problem?

There is a suggestion and a sample code at my stackoverflow question, but i didnt try to implement because it is so far from my current structure and I would have to refactor too much. But maybe it can help you, take a look.
https://stackoverflow.com/questions/63603810/cannot-rotate-ground-overlay-in-react-google-maps-property-bearing-is-ignor
