### ISSUE TITLE
Css broken when map component is added

### ISSUE THREAD

**Issue by brunopopf** [JustFly1984/react-google-maps-api#1361]
My app structure: 

//public
//src
*****//components
**********//app
***************-App.css
***************-App.js
**********//map
***************-Map.js
*****//fonts
**********-myFont.ttf
*****-index.css
*****-index.js
*****-serviceWorlers.js
-package.json

Map component:

Basic example -> attached in comment

Workflow without map:

- I define some css styles in index.css (--variables, font import, etc).
- I use the styles in my App component.
- Css working well.

Workflow with map:
- I define some css styles in index.css (--variables, font import, etc).
- I use styles in my App component.
- I use Map component in App component.
- Map working well but css styles stop working

Workaround:
- I moved the css style (--variables, font import, etc) defined in index.css to -> app.css
- Everything is working well

Environment:

@react-google-maps/api  1.9.12

react 16.13.1

**Comment by brunopopf** [comment]
`import React, { Component } from 'react';
import { GoogleMap, LoadScript } from '@react-google-maps/api';
/// <reference types="googlemaps" />


const containerStyle = {
  width: '800px',
  height: '500px',
  marginLeft: '80px',
};

const center = {
  lat: -34.901112,
  lng:  -56.164532
};

class Map extends Component {
  render() {
    return (
      <LoadScript
        googleMapsApiKey='myAPIKey'
      >
        <GoogleMap
          mapContainerClassName ="pepe"
          mapContainerStyle={containerStyle}
          center={center}
          zoom={3}         
        >
        </GoogleMap>
      </LoadScript>
    )
  }
}
export default React.memo(Map)`

**Comment by brunopopf** [comment]
``import React, { Component } from 'react';
import { GoogleMap, LoadScript } from '@react-google-maps/api';
/// <reference types="googlemaps" />


const containerStyle = {
  width: '800px',
  height: '500px',
  marginLeft: '80px',
};

const center = {
  lat: -34.901112,
  lng:  -56.164532
};

class Map extends Component {
  render() {
    return (
      <LoadScript
        googleMapsApiKey='MyAPIKey'
      >
        <GoogleMap
          mapContainerStyle={containerStyle}
          center={center}
          zoom={3}
          // streetView= {false}
          // options = {{
          //   //   streetViewControl: false,
          //   //   zoomControl: false,
          // }}
        >
        

          <></>
        </GoogleMap>
      </LoadScript>
    )
  }
}
export default React.memo(Map)

**Comment by JustFly1984** [comment]
please provide minimal reproduction in codesandbox.io

**Comment by shammahk** [comment]
Facing same issue on unmount. Please how do I fix this? I use styled components so I can't follow the workaround you did.

**Comment by JustFly1984** [comment]
Sorry, can't help with styled components - they do some magic under the hood, which breaks context passing through component tree. I've seen similar issues with framer-motion or react-three-fiber not working correctly with styled components. I had to get rid of styled components in couple of projects.

**Comment by shammahk** [comment]
Thanks, I used the useJsApiLoader hook on the npm example and it works, my css doesn't break anymore.

**Comment by kariyngva** [comment]
So for me the fix was not setting `preventGoogleFontsLoading` to `true` - i think maybe [these lines here](https://github.com/JustFly1984/react-google-maps-api/blob/develop/packages/react-google-maps-api/src/utils/prevent-google-fonts.ts#L49-L64) might cause style unloading in some cases.

**Comment by VinaySehwag14** [comment]
I was facing same issue , while using this package my css is corrupting , by using ( useJsApiLoader ) help me out , please try using this .
