### ISSUE TITLE
add support for client parameter

### ISSUE THREAD

**Issue by modosc** [JustFly1984/react-google-maps-api#137]
google supports client keys instead of api keys:

https://developers.google.com/maps/documentation/javascript/get-api-key#specifying-a-client-id-when-loading-the-api

## How is it behave?
we don't have an api key so LoadScript doesn't work correctly. there's no way to provide a client key instead.

## How should it behave correctly?
client key should be supported

**Comment by uriklar** [comment]
Thanks for the issue! Wanna try creating a PR?
