### ISSUE TITLE
LoadScript used multiple times in app

### ISSUE THREAD

**Issue by FredyC** [JustFly1984/react-google-maps-api#139]
I've already tried to discuss this [on the spectrum](https://spectrum.chat/react-google-maps/general/you-have-included-the-google-maps-javascript-api-multiple-times-on-this-page~99cc4656-9502-4fc4-9fa2-9cdccc8f44f7), but no response, so let's poke a bear in here :)

There is an obvious problem that `LoadScript` injects a script to header every time it is mounted. It's not keeping any information it was already loaded before. This is not only a problem of fetching the same thing multiple times, but Google API seems to have a problem with that and it causes weird issues like __`google` is not defined__

Furthermore, it shouldn't be just a boolean flag to remember it has been loaded, because it might be needed with a different set of props.

The react-google-maps are using `scriptjs` module and I have a feeling it actually tracks fetching the same resource multiple times and that's why it works.

So why you have opted not to use `scriptjs` here I wonder?

**Comment by orta-sanz** [comment]
I'm facing the same issue as you: `google is not defined` :/

**Comment by JustFly1984** [comment]
That is a bug with google-maps-api itself, the only way to get rid of this error is to use `<LoadScript />` in single place in the app, or just ignore an error message. I have posted an issue at google's issue tracker. If you are interested, please support an issue. 
https://issuetracker.google.com/issues/121054556

**Comment by JustFly1984** [comment]
@FredyC I wanted to clean the <head /> section from the garbage generated by google-maps-api script on unMount.

**Comment by FredyC** [comment]
@JustFly1984 Well, I am fairly convinced that using `scriptjs` would fix that. Or at least that's the difference from react-google-maps project and it was working there properly.

**Comment by JustFly1984** [comment]
@FredyC can you make a PR, which will make scriptjs as an option?

**Comment by FredyC** [comment]
That's going to be tough. Any optional dependencies are a problem for Webpack bundlers which would fail in a moment they see `require('scriptjs')`. To this day, I am not aware of the proper way of handling that.

**Comment by JustFly1984** [comment]
I'm not saying that dependency should be optional) I'm saying that there should be boolean prop on `<LoadScript scriptjs={false} />`, which turns `scriptjs` off. I still hope that my issue will get an attention.

**Comment by FredyC** [comment]
I see, ok, I can do that. Not sure though why would anyone want to turn that off since it won't decrease bundle size or anything :)

**Comment by orta-sanz** [comment]
Thanks for the explanation @JustFly1984 ;)

**Comment by FredyC** [comment]
Hm, so I am looking into and it's not true what I've said before about missing check on the mount.

https://github.com/JustFly1984/react-google-maps-api/blob/f5b635cf47dd21cb0e04e9ecd10c3b6dd3b1cf55/packages/react-google-maps-api/src/LoadScript.tsx#L56

However, the problem might be that second part of the condition. If there is `window.google` present but it's currently cleaning up from previous use, it will call `injectScript` anyway. That's a race condition that's hard to reproduce in development.

Why do we need that cleanup anyway? @JustFly1984 is talking about a memory leak in linked issue, but what does that actually mean? From a couple of experiments I have done, it doesn't seem loading that script multiple times is actually a problem, it always overwrites the previous `window.google` object with the latest variant.

What if that cleanup is an actual culprit here? Component starts to unmount, it removes resources from `head` element and then deletes `window.google` with 1ms delay. However, another component with LoadScript can be mounted during that delay and it starts looking for that global variable which was deleted.

I will prepare alternative LoadScriptNext instead of tweaking the current one, most likely rewritten to hooks and without that strange cleanup. I am fairly certain it will solve most of the problems as the old project wasn't doing anything like that and it was working.
