### ISSUE TITLE
Use Yarn workspaces?

### ISSUE THREAD

**Issue by FredyC** [JustFly1984/react-google-maps-api#140]
Would you be inclined to switch over to that instead of Lerna Bootstrap which always felt rather buggy? I can do the change, but want to know first if you have some objections.

https://github.com/lerna/lerna/tree/master/commands/bootstrap#--use-workspaces

**Comment by JustFly1984** [comment]
I do think that switch to workspaces is good idea. please go on :-)

**Comment by uriklar** [comment]
+1 
I've been hearing good things about yarn workspaces.
There are 2 pain points I'm wondering if this could maybe solve easily:

1. An easy way to link between the project packages. I.E - I've developed something on react-google-maps-api and I want to test it on react-google-maps-api-gatsby-example.

2. A way to allow pointing at a specific branch of a package in package.json. I can't find the issue right now but I know this is not possible with lerna

**Comment by FredyC** [comment]
> 1. An easy way to link between the project packages. I.E - I've developed something on react-google-maps-api and I want to test it on react-google-maps-api-gatsby-example.

That does work naturally, it makes symlinks directly to those packages

> 2\. A way to allow pointing at a specific branch of a package in package.json. I can't find the issue right now but I know this is not possible with lerna

That's a bit harder. It's, of course, possible in terms of NPM so it would work when published, but Git is the enemy here. It doesn't allow for partial checkout of different branches for a subdirectory.
