### ISSUE TITLE
Consider using @googlemaps/js-api-loader

### ISSUE THREAD

**Issue by jpoehnelt** [JustFly1984/react-google-maps-api#1411]
@googlemaps/js-api-loader is maintained by Google and should have the latest options and libraries available.

**Comment by JustFly1984** [comment]
If somebody wants to implement this feature, PR is welcome.

**Comment by risaac** [comment]
Hi @JustFly1984, is there anyway to specify the google maps api url? I'm trying to put it behind mulesoft.

**Comment by JustFly1984** [comment]
Sorry, I don't know what is mulesoft

**Comment by JustFly1984** [comment]
@jpoehnelt please test new version.
