### ISSUE TITLE
onRightClick and onMouseUp event not fired simultaneosly (Polygon)

### ISSUE THREAD

**Issue by MalikBagwala** [JustFly1984/react-google-maps-api#1412]
I wanted to implement two functionalities on the `<Polygon/>` component

1. onRightClick - if a right click event is fired on a vertice then the vertice should simply be removed

2. onMouseUp - to record any changes made to the polygon (by dragging, extending its vertices)

However in practice only one of these events is fired i.e onMouseUp. And the MouseEvent object 'e' has no properties which highlight the type of click (When clicked on a Vertice!)

Is there any way I achieve this functionallity? 

@JustFly1984

**Comment by JustFly1984** [comment]
@MalikBagwala  please provide minimal reproduction at codesandbox.io

**Comment by ambr89** [comment]
@MalikBagwala 
do you have implemented your event?

**Comment by kenjdavidson** [comment]
The event not having information about which button was clicked shouldn't make a difference.  This can be completed with:

```tsx
<Polygon
  path={polygonPath}
  onLoad={polygon => setPolygonRef(polygon)}
  onUnmount={() => setPolygonRef(undefined)}
  onMouseUp={event => updatePolygonPath(polygonRef.getPath())} 
  onRightClick={event => event.vertex && removeVertex(event)}
/>
```
