### ISSUE TITLE
Map renders gray in Material Ui Modal / Dialog

### ISSUE THREAD

**Issue by tottivega** [JustFly1984/react-google-maps-api#144]
@react-google-maps/api version 1.2.3
@material-ui version 4.0.1

Loading a GoogleMap Component inside of a Material Ui Dialog Component renders the map completely gray, while outside of the modal the map renders correctly.

Has anyone encountered this issue before, anyone knows a way around it?

**Comment by JustFly1984** [comment]
@tottivega  Can you please provide minimal example at codesandbox?

**Comment by tottivega** [comment]
When I prepared my example at codesandbox it worked, so I went back to my code and traced the issue down to having overflow-x: hidden in my modal. It was causing the map to inherit that I guess.
