### ISSUE TITLE
gatsby local

### ISSUE THREAD

**Issue by FredyC** [JustFly1984/react-google-maps-api#147]
@FredyC 
I have issues with running gatsby-example locally after yarn workspaces merge, can you try to run it, you will see what I mean.

_Originally posted by @JustFly1984 in https://github.com/JustFly1984/react-google-maps-api/pull/143_

**Comment by FredyC** [comment]
Are you seeing this too or is that some other issue? 😆 

![image](https://user-images.githubusercontent.com/1096340/59088891-19ad2780-8909-11e9-9af4-5f480aa1eea2.png)

**Comment by FredyC** [comment]
Ok, so I had the same error before my PRs as well, so you should probably be more specific what issue you have.

**Comment by JustFly1984** [comment]
nope, I see another issue:

<img width="701" alt="Screenshot 2019-06-07 10 50 59" src="https://user-images.githubusercontent.com/2255993/59089177-25511c00-8912-11e9-9d0e-7060509c3b1d.png">

**Comment by FredyC** [comment]
Well, that's kinda obvious, the `api` package is not built to be referenced. I have it built, so when I run it without `--https` it works correctly.

I wonder what would be the best approach here. It would kinda make sense some watch mode for API package running along to have it rebuilt when changing. TSDX does have a watch mode.

**Comment by FredyC** [comment]
Hmm, I take it back, without HTTPS I actually have a different kind of error that does not make any sense...

![image](https://user-images.githubusercontent.com/1096340/59089969-bd97d280-890b-11e9-894a-b9ec73e669be.png)

Apparently, it uses ES variant built by TSDX, but I have no idea why it would be looking for `tsconfig.json` at that moment. How the TypeScript involved there?

**Comment by FredyC** [comment]
Hm, the only workaround I was able to figure out is to disable `failOnError`, then it starts and seems to be working just fine. I think it's a bug somewhere deeper in Gatsby or some plugin. I know nothing about that ecosystem...

https://github.com/JustFly1984/react-google-maps-api/blob/54af7f2ca98ded16b3de7775fbe51d1ec8dea28b/packages/react-google-maps-api-gatsby-example/gatsby-config.js#L28
