### ISSUE TITLE
change from /lib to /dist breaks imports

### ISSUE THREAD

**Issue by kaYcee** [JustFly1984/react-google-maps-api#152]
# Please provide an explanation
Overall great redo of the original package, thanks! Unfortunately, version 1.2.7 seems to break the default imports. Previously (up to version 1.2.3), imports such as 

```
import LoadScript from "@react-google-maps/api/lib/LoadScript"
import GoogleMap from "@react-google-maps/api/lib/GoogleMap"
import Marker from  "@react-google-maps/api/lib/components/drawing/Marker"
```

were possible to reduce bundle size. Now, I get an error `Module not found: Can't resolve '@react-google-maps/api/lib/LoadScript'`. Even if I change from `/lib` to `/dist` (which seems to have been introduced in this build) the error persists.

I would rather not use named imports since 
```
import {LoadScript, GoogleMap, Marker} from "@react-google-maps/api"
```
bloats bundle size from 14 KB to 53 KB. For some reason, tree-shaking seems to be ineffective with CRA 2.0 and this package.

## Your Environment

os: mac

node: 10.15.3

react version: 16.3

@react-google-maps/api version: 1.2.7

## How is it behave?
Tree-shaking together with CRA 2.0 not working for some reason and direct imports not working anymore.

## How should it behave correctly?
ES6 imports should lead to same result as individual imports in CRA 2.0.

**Comment by JustFly1984** [comment]
@FredyC mention

**Comment by FredyC** [comment]
@kaYcee Can you please open an issue at https://github.com/palmerhq/tsdx/issues instead? That's the tool we are using for building and it doesn't really allow for much of configuration. I briefly looked there and not much mention of tree shaking.

**Comment by kaYcee** [comment]
Thanks for responding so quickly @FredyC! I understand your concerns regarding tree-shaking. But the advice to reduce bundle size is explicitly mentioned on the [project page](https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api). Apparently the recent version 1.2.7 has breaking changes - namely changing the distribution folder from `/lib` to `/dist` and removing the references - which asks for a fix on either side. Maybe it was really just a slightly different build configuration.

**Comment by FredyC** [comment]
Ok, I wasn't aware of that advice in docs and @JustFly1984 merged change in build tool without pointing that out. It's indeed a breaking change given that.

Looking at [Webpack docs](https://webpack.js.org/guides/tree-shaking/) and there are some hints on how to make tree shaking working. I will check it out in a few days and see what we can do here. Worst case scenario would be double building to the `/lib` folder as it was before.

**Comment by JustFly1984** [comment]
@FredyC Tree shaking is important, there is a whole world out there, which has no even proper 3g connection. I had no idea that tdsx has no support for tree shaking.

**Comment by FredyC** [comment]
@JustFly1984 Well, it's not about TSDX. Tree shaking, in general, is about dead code elimination. That can happen over the bundle as well. According to a linked document, if the ESM bundle is used, it should be able to do that without any configuration. If CommonJS bundle is used and the Webpack is informed that module is side effect free, it can do tree shaking as well.

**Comment by JustFly1984** [comment]
@FredyC annoying is very opinionated word, especially then you try to fit your bundle size below 100kb. There is a difference between `should` and `does` when we are talking about bundlers like webpack etc.

**Comment by FredyC** [comment]
That was merely a side note... If that's all you have taken from what I said, then it's not good ;) Point is that accessing modules directly in `/lib` is NOT tree shaking as it's falsely named in README. It's only about including specific files in build.

I do wonder what are other known bundlers that do support tree shaking (in any form) that are worth considering? I am kinda living in Webpack bubble and not really paying attention to others.

**Comment by JustFly1984** [comment]
@FredyC 
I agree that tsdx is a great option, but currently tree shaking is very tricky think to achieve, and depends on how lib exporting it's api. I like that TSDX makes better optimized JS output, but I would like to keep lib modular.

https://bundlephobia.com/result?p=@react-google-maps/api@1.2.7 says that it is treeshakable though.

We have two options - get rid of specific imports and remove advise from readme, or build two times.

**Comment by FredyC** [comment]
@kaYcee Any chance you could try if using dist exports instead of the lib actually does tree shaking? I don't mean to rewrite your whole app, but perhaps create a small repo with CRA and commit everything including "build" folder.

**Comment by JustFly1984** [comment]
I have published 1.3.0, temporary getting rid of `/lib` advice on readme.md, please use standard import

@kaYcee 
53 KB looks like the bundle size without gzip, possibly in dev mode. Dev mode of create-react-app` does not use tree-shaking by default. please analyze only production bundle.

**Comment by FredyC** [comment]
> 53 KB looks like the bundle size without gzip

I think bundlephobia is incorrect at this. Looking here, the production bundle has only 39kB, should be even smaller when gzipped. Not that it matters that much with tree shaking :)

https://unpkg.com/@react-google-maps/api@1.3.0/dist/

**Comment by JustFly1984** [comment]
@kaYcee 
We have gatsby-example in packages directory. If you want to help our community, you can create a PR with create-react-app-example, so we could improve on it.
