### ISSUE TITLE
Zoom on StreetViewPanorama not working

### ISSUE THREAD

**Issue by Wintervacht** [JustFly1984/react-google-maps-api#153]
# The issue
I have successfully implemented a StreetViewPanorama using the following method in another component's render function:
`const StreetViewMap = withScriptjs(withGoogleMap((props) =>
            <GoogleMap>
                <StreetViewPanorama defaultPosition={this.state.latlng}
                                    visible/>
            </GoogleMap>
        ));`
I have tried to change the default zoomlevel but nothing seems to work, am I doing something wrong or is this just not implemented?
## My Environment
os: linux
react version: 16.6

## How does it behave?
No matter whow or where i try to define `zoom` or `defaultZoom`, nothing seems to work, not even when playing around with the [documentation](https://react-google-maps-api-docs.netlify.com/#streetviewpanorama).

i have tried adding the options `
defaultZoom={4}
zoom={4}
`
in the parent GoogleMap component, in the StreetViewpanorama subcomponent and in the eventually called component within the main component's `render` method. Nothing works.
## How should it behave correctly?
It *should* render the panorama with a narrower (or wider, depending on zoom level) field of view, to show less or more of the area.

Full disclosure: I'm using the sadly unmaintained React-Google-Maps library, but am willing to change that to this newer version if it solves my problem. I've posted my issue here since this library is basically a newer, rewritten and extended version of that, and this place is more likely to yield  an answer than a dead repository.

**Comment by JustFly1984** [comment]
@Wintervacht Can you please make an basic example at codesandbox?

There is no `default` props on components to simplify API in our lib.

As I see a source code, there is an `options` prop for <StreetViewPanorama />, which accepts an object with next interface:

<img width="420" alt="Screenshot 2019-06-11 19 16 47" src="https://user-images.githubusercontent.com/2255993/59288968-a6474500-8c7d-11e9-80be-8b123ecd6a72.png">

**Comment by JustFly1984** [comment]
please reopen if it does not solve your issue
