### ISSUE TITLE
Custom Marker 

### ISSUE THREAD

**Issue by ksuha2uha** [JustFly1984/react-google-maps-api#1555]
Hi! 
Can you please help me, if I want to display my custom components instead of using default Marker, how can I do it? 
I put my component in  `Marker` 
`<Marker
            key={i}
            position={item.position}
           visible={false}
          >
            <CustomComponent label={i + 1}
           </Marker>` 

but my `CustomComponent` display in right top conner.
In library `react-google-maps` I used `MarkerWithLabel` but now I have only `Marker`

Thanks in advance.

**Comment by JustFly1984** [comment]
Ask questions on Spectrum or Slack, here is issue tracker.
