### ISSUE TITLE
More examples/documentation on clustering

### ISSUE THREAD

**Issue by colemars** [JustFly1984/react-google-maps-api#156]
Documentation right now is a bit unclear (to me). For example, I'm not quite clear on what the clusterer property on Marker does.

I'm stuck figuring out the difference between how clustering is done in the documentation by creating an array of lat/long objects and then mapping them directly versus accessing an already existing list of lat/long points and referencing them in the clusterer property. 

https://codesandbox.io/s/usegooglemap-repro-ljtgp

If you go to Map2.js:61 you'll see how it doesn't seem to be working for me. 

If this can be cleared up here I could work on adding some clarity in the docs.

**Comment by JustFly1984** [comment]
I hope this example sandbox I've done will make things a bit cleaner
https://codesandbox.io/s/usegooglemap-repro-z6syx

**Comment by uriklar** [comment]
@colemars I don't understand, what isn't working? It looks like your example is working fine.

When rendering marker that you want to be clustered, you need to render them inside a ```<MarkerClusterer> ```
This component provides you a ```clusterer``` (via render prop). You then pass this clusterer as a prop to each marker you want to be clustered. 

The important line in Marker.tsx is [this](https://github.com/JustFly1984/react-google-maps-api/blob/6a05231391a4dd5b0850e519d0004a5228ab3ed2/packages/react-google-maps-api/src/components/drawing/Marker.tsx#L157)

If a clusterer was passed, the marker is added to the relevant cluster, if not, it is added to the map as any other component is.

**Comment by colemars** [comment]
Thank you for clearing up my confusion
