### ISSUE TITLE
Anchor is Infowindow error.

### ISSUE THREAD

**Issue by maxleon52** [JustFly1984/react-google-maps-api#1563]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Your Environment

os: windows

node --version: 12+

react version: 16.8

webpack version: last

@babel version: last

@react-google-maps/api version

## basic implementation of incorrect behavior in codesandbox.com

hi, how should i fill in the anchor property?

My code:
```js
<InfoWindow
              position={{
                lat: positionSelectedDoctors?.position.lat as number,
                lng: positionSelectedDoctors?.position.lng as number,
              }}
              onCloseClick={() => setOpenWindow(!openWindow)}
              anchor={new google.maps.Point(10, 10)}
            >
              <MarkerDetails>
                <img src={positionSelectedDoctors?.avatar_url} alt="foto" />
                <span>{positionSelectedDoctors?.genre}</span>
                <span>{positionSelectedDoctors?.name}</span>
                <span>
                  {positionSelectedDoctors?.city} -{' '}
                  {positionSelectedDoctors?.uf}
                </span>
              </MarkerDetails>
            </InfoWindow>
```
Error:
![point](https://user-images.githubusercontent.com/42389997/96542392-5f595e80-1278-11eb-830f-b5877d479e1f.png)

**Comment by JustFly1984** [comment]
Looks like `Point` type object type is not equal to `MVCObject` type

https://developers.google.com/maps/documentation/javascript/reference/event#MVCObject

<img width="1336" alt="Screen Shot 2020-10-20 at 5 44 51 PM" src="https://user-images.githubusercontent.com/2255993/96576355-44c8c900-12fc-11eb-8829-62654e49cedc.png">

anchor prop requires `MVCObject` type.

Could be some changes in google maps API, or bugs in @types/googlemaps.

try 

```
// @ts-ignore
```,

if it is working for you, it is bugs with types, if not - changes in API, and you need to create MVCObject instead of Point.

**Comment by maxleon52** [comment]
did not work. I would like, if possible, an example.

**Comment by JustFly1984** [comment]
@maxleon52 sorry I do not have an example, please refer to official documentation. In case of success, please post the solution here.

**Comment by maxleon52** [comment]
@JustFly1984 the solution was to remove the anchor and pass options = {{pixelOffset: new google.maps.Size (0, -30)}}

**Comment by JustFly1984** [comment]
@maxleon52 thank you for solution

**Comment by bobbyZ94** [comment]
x
