### ISSUE TITLE
Polyline arrow

### ISSUE THREAD

**Issue by telubato** [JustFly1984/react-google-maps-api#1578]
Hi,

I was checking on document and I didn't find how I can put an arrow between polylines, like exemple bellow:

![image](https://user-images.githubusercontent.com/25345398/96793530-791fb080-13f4-11eb-9f7a-31e6b05d03e0.png)

Someone already try this?
Thank you.

**Comment by JustFly1984** [comment]
Ask questions on spectrum or slack. Here is issue tracker.
