### ISSUE TITLE
google api is already presented: AJAX page loading + ReactDOM.render()

### ISSUE THREAD

**Issue by AgamlaRage** [JustFly1984/react-google-maps-api#159]
Hello, _Thx for this plugin, you are doing a great job!_

I'm currently using the latest version of the plugin `"@react-google-maps/api": "^1.3.0"`.

I've created a custom component `<Map/>` containing `<LoadScript/>` and `<GoogleMap/>` inside it.
This custom component is render with `ReactDOM.render()` in my page.

In my app, I've also got an AJAX page loading system that is similar to [JQuery.load()](http://api.jquery.com/load/) to load my pages.
Means, after you click on an internal link, the AJAX page loading system:
- get the new HTML content from the server
- replace the old page content by the new HTML
- re-run the `ReactDOM.render()` to render the `<Map/>`

**When I load the page for the first time, everything works fine.**
The scripts are loaded, the `<GoogleMap/>` is rendered, and triggers the `onLoad`callback, so I can store the map instance for later.

**But if I visit an other page of my app, then go back to the page where the `<Map/>` is rendered, this error message is displayed in the console:**

`google api is already presented`

And the `<GoogleMap/>` component is not rendering or triggering the `onLoad()` calback anymore.

--- 

Is this a normal behavior ?

How can render the `<GoogleMap/>` again if the `<LoadScript/>` was already call and the `window.google` object already initialized ?

**Comment by JustFly1984** [comment]
@AgamlaRage you can use ‘<LoadScript />’ once, the same way you use Redux ‘<Provider />’, or use new alternative ways to load script, you can see the docs

**Comment by AgamlaRage** [comment]
@JustFly1984 Thx for your quick response.

I ended up with a hack that suits my needs.

I extended your original `<LoadScript/>` to prevent this error when `window.google`  is already loaded.
Then changing the `loaded` state if it's the case.
So it will render the children (my  `<GoogleMap/>`).

```javascript
class LoadScriptOnlyIfNeeded extends LoadScript {
  componentDidMount() {
    const cleaningUp = true
    const isBrowser = typeof document !== "undefined" // require('@react-google-maps/api/src/utils/isbrowser')
    const isAlreadyLoaded = isGoogleLoaded() && document.querySelector('body.first-hit-completed')
    if (!isAlreadyLoaded && isBrowser) {
      // @ts-ignore
      if (window.google && !cleaningUp) {
        console.error("google api is already presented")
        return
      }

      this.isCleaningUp().then(this.injectScript)
    }

    if (isAlreadyLoaded) {
      this.setState({ loaded: true })
    }
  }
}
```

I don't know if my code is usefull to you, or if you want your plugin to handle this use case. But here it is :)

Thx for your time

**Comment by OmarKhattab** [comment]
> @JustFly1984 Thx for your quick response.
> 
> I ended up with a hack that suits my needs.
> 
> I extended your original `<LoadScript/>` to prevent this error when `window.google` is already loaded.
> Then changing the `loaded` state if it's the case.
> So it will render the children (my `<GoogleMap/>`).
> 
> ```js
> class LoadScriptOnlyIfNeeded extends LoadScript {
>   componentDidMount() {
>     const cleaningUp = true
>     const isBrowser = typeof document !== "undefined" // require('@react-google-maps/api/src/utils/isbrowser')
>     const isAlreadyLoaded = window.google && window.google.maps && document.querySelector('body.first-hit-completed') // AJAX page loading system is adding this class the first time the app is loaded
>     if (!isAlreadyLoaded && isBrowser) {
>       // @ts-ignore
>       if (window.google && !cleaningUp) {
>         console.error("google api is already presented")
>         return
>       }
> 
>       this.isCleaningUp().then(this.injectScript)
>     }
> 
>     if (isAlreadyLoaded) {
>       this.setState({ loaded: true })
>     }
>   }
> }
> ```
> 
> I don't know if my code is usefull to you, or if you want your plugin to handle this use case. But here it is :)
> 
> Thx for your time

on 2.1.1 i had to use this fix

**Comment by giriawu** [comment]
Use this method in React and get `Uncaught error: Uncaught ReferenceError: google is not defined`. Wonder what happened?
![image](https://user-images.githubusercontent.com/86780745/159880520-5c140427-90a1-4b2c-b62e-8df32a76b68c.png)

**Comment by sherifghonaim** [comment]
@giriawu Facing the same issue; did you find a solution?

**Comment by lylest** [comment]
`{window.google === undefined ?  <LoadScript><GoogleMap /></LoadScript> : <GoogleMap />}`
