### ISSUE TITLE
preventGoogleFonts breaks CSS-in-JS

### ISSUE THREAD

**Issue by slorber** [JustFly1984/react-google-maps-api#160]
Version:     "@react-google-maps/api": "^1.3.0",

Using Emotion 10 css prop for CSS-in-JS.

When using preventsGoogleFontsLoading = true

```
const StepOrderMap = () => {
  const { isLoaded } = useLoadScript({preventGoogleFontsLoading: true, ...otherOptions});
  return (
    <div>
      <div
        css={{
          backgroundColor: 'green',
        }}
      >
        GREEN
      </div>
      {isLoaded && (
        <div
          css={{
            backgroundColor: 'red',
          }}
        >
          RED
        </div>
      )}
      <div
        css={{
          backgroundColor: 'blue',
        }}
      >
        BLUE
      </div>
    </div>
  );
};
```

The RED div has the correct Emotion className, but your option prevented emotion to insert the desired CSS in the stylesheet or something.

![image](https://user-images.githubusercontent.com/749374/59554198-93937f80-8f9f-11e9-8bc5-407886cd28ae.png)

![image](https://user-images.githubusercontent.com/749374/59554213-c76ea500-8f9f-11e9-9da9-6718231fc5a8.png)

When removing the option, emotion works fine again

**Comment by JustFly1984** [comment]
Well, it means that emotion loads google fonts exactly the same way as google maps, and/or using same class name prefix as our library. In general I would not recommend to use CCS in JS for performance reasons, as well as style prop object. Please install eslint-plugin-react-perf, and you will understand what I mean

**Comment by slorber** [comment]
> Well, it means that emotion loads google fonts exactly the same way as google maps, and/or using same class name prefix as google-maps-api.

Emotion does not load google fonts.
The classNames look like this: css-9tf9ac


> In general I would not recommend to use CCS in JS for performance reasons, as well as style prop object.

IMHO this statement is not really well funded. I use CSS in JS with Gatsby so my CSS-in-JS is most of the time extracted as CSS files at build time. + approaches like RNW (used by Twitter in prod) have been reported to actually be better than most carefully hand written CSS due to their "atomic" approach. As for style prop objects there's babel tooling to inline those into constants (but avoiding temporary object creation is a micro optim, not really of a huge impact)

**Comment by JustFly1984** [comment]
@slorber
if you provide a PR, I will test it and merge.

**Comment by rafael-sa** [comment]
Just a heads up, it removes CSS generated from Emotion 9 as well.

**Comment by liamcmitchell-sc** [comment]
I got bitten by this too. This condition here matches the style elements created by emotion:
https://github.com/JustFly1984/react-google-maps-api/blob/0f58a8cf2dbe22bbcb9a0f0758472d671ddcdbfd/packages/react-google-maps-api/src/utils/prevent-google-fonts.ts#L33-L41

This way of blocking fonts is hacky. Noone wants to track down bugs to find that a library is overriding DOM methods. Please document *how* this option works so that others know what they are opting into.

**Comment by JustFly1984** [comment]
@liamcmitchell-sc your PR is welcome

**Comment by dasniko** [comment]
I'm noticing similar behaviour, but not using emotion at all. I'm using material-ui.

As soon I use `preventGoogleFontsLoading`, several Google Maps related CSS definitions won't be inserted in the `<head>` section of my HTML page. When I remove the flag, all CSS is inserted right.
