### ISSUE TITLE
Heatmap 'google' is not defined

### ISSUE THREAD

**Issue by redimongo** [JustFly1984/react-google-maps-api#1600]
So I am using the demo code available on the website https://react-google-maps-api-docs.netlify.app/#heatmaplayer

However I have ran into an issue.

```
 data={[
  new google.maps.LatLng(37.782, -122.447),
  new google.maps.LatLng(37.782, -122.445),
  new google.maps.LatLng(37.782, -122.443),
  new google.maps.LatLng(37.782, -122.441),
  new google.maps.LatLng(37.782, -122.439),
  new google.maps.LatLng(37.782, -122.437),
  new google.maps.LatLng(37.782, -122.435),
  new google.maps.LatLng(37.785, -122.447),
  new google.maps.LatLng(37.785, -122.445),
  new google.maps.LatLng(37.785, -122.443),
  new google.maps.LatLng(37.785, -122.441),
  new google.maps.LatLng(37.785, -122.439),
  new google.maps.LatLng(37.785, -122.437),
  new google.maps.LatLng(37.785, -122.435)
]}
```

I get the error 'google' is not defined, how do I fix this please.

**Comment by redimongo** [comment]
Also side note : https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api-gatsby-example/src/examples/example-heatmap.js

this is missing the part where you load the API key

**Comment by JustFly1984** [comment]
@redimongo please read the component tree. there is single api key for all examples together.

google is not defined until `<LoadScript />` does async script loading and execution, you need to use google references only in component tree below the `<LoadScript />`. There is a ton of issues about google is undefined, please read other iussues.

**Comment by redimongo** [comment]
> @redimongo please read the component tree. there is single api key for all examples together.
> 
> google is not defined until `<LoadScript />` does async script loading and execution, you need to use google references only in component tree below the `<LoadScript />`. There is a ton of issues about google is undefined, please read other iussues.

why wont the example work though?

**Comment by JustFly1984** [comment]
Please render the components which uses google object conditionally, if script is loaded. Look at gatsby example implementation. Do not stuff all your code in one component. Use PureComponent or React.memo to reduce re-rendering.

**Comment by SKempin** [comment]
@JustFly1984  Can we have a clear example of how to implement the heatmap please? The number of issues about google being undefined is because there is not clear documentation. I am similarly stuck on this. Thank you.
