### ISSUE TITLE
Dashed Line Symbols (Polyline)

### ISSUE THREAD

**Issue by Angelk90** [JustFly1984/react-google-maps-api#1606]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Please provide an explanation

Hi @JustFly1984 , it would be possible to give the possibility to create Dashed Lines.

![Dashed Line Symbols -Polyline-  -  Maps JavaScript API 26-10-2020 12-57-46](https://user-images.githubusercontent.com/20476002/97169765-e6339d00-178a-11eb-90a8-d4e8077cca4c.png)

## Your Environment

os: linux

node --version: 12+

react version: 16.8

webpack version: last

@babel version: last

@react-google-maps/api version

## How is it behave?

At the moment it is only possible to create solid lines.

## How should it behave correctly?

Link: [Dashed Line](https://developers.google.com/maps/documentation/javascript/examples/overlay-symbol-dashed#maps_overlay_symbol_dashed-javascript)

**Comment by JustFly1984** [comment]
@Angelk90 There is nothing blocking you from using `<Polyline /> with options from docs link.

**Comment by Angelk90** [comment]
@JustFly1984 : What are the options to pass to `<Polyline />` to do this?

**Comment by JustFly1984** [comment]
same as in your example
