### ISSUE TITLE
Make `console.log` statements configurable

### ISSUE THREAD

**Issue by altJake** [JustFly1984/react-google-maps-api#161]
There are a quite few `console.log` calls in several place in the code (you can hit the search query [here](https://github.com/JustFly1984/react-google-maps-api/search?q=console.log)).

I can see some were intended for debugging and/or logging to the console upon unforeseeable errors. In our production environment we noticed that due to this line here:
https://github.com/JustFly1984/react-google-maps-api/blob/84e240277a4882f76719c25a6996f3954c5468c2/packages/react-google-maps-api/src/utils/prevent-google-fonts.ts#L49

Which was added in 4ea0041 (_"debugging prevent google fonts"_)

I can see the benefit of having those debug/logs at hand, but was thinking of adding the possibility / flag to hide those (maybe opposite logic here, disabled by default and opt-in when needed) via a prop on the [`LoadScript`](https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/LoadScript.tsx#L16-L23) component for example:
```ts
export interface LoadScriptProps extends LoadScriptUrlOptions {
  ...
  preventGoogleFontsLoading?: boolean;
  debugMode?: boolean;
}
```

I could start preparing a PR, wanted to validate my approach and hear your thoughts about it, whether it's feasible or maybe why not 🤔 

## Environment

os: mac

node --version: "10.5.3"

react version: "^16.8.4"

webpack version: "^4.28.4"

@babel version: "^7.2.2" (@babel/core)

@react-google-maps/api version: "^1.2.3"

**Comment by JustFly1984** [comment]
I think we can remove those console.logs safely. your PR is welcome. No need in debug prop.
