### ISSUE TITLE
Style Map by addng Map ID

### ISSUE THREAD

**Issue by moneszarrugh** [JustFly1984/react-google-maps-api#1616]
I created a Map ID and added a style to it. But I couldn't get it to work. I tried using id prop and mapId but style doesnt change. Please cover this in the documentation on how to set a map id to change the map style.

Thanks

**Comment by JustFly1984** [comment]
I'm sure someone did that before successfully, can't really spare time for research now. If you succeed, please post your solution here. Official documentation usually helps. Ask questions in community or on slack.

**Comment by moneszarrugh** [comment]
> I'm sure someone did that before successfully, can't really spare time for research now. If you succeed, please post your solution here. Official documentation usually helps. Ask questions in community or on slack.

I did research this problem quite a bit.

According to this https://stackoverflow.com/questions/62780394/how-do-i-change-the-mapid-of-a-google-vector-map
The author mentions passing mapId prop the the Map object.

But in the docs https://react-google-maps-api-docs.netlify.app/#googlemap
Theere is no mapId prop. Maybe that's why it's not passing down to google's official Map object.

I tried using the id prop but it had no affect.

**Comment by Kjagd** [comment]
As mentioned in https://github.com/JustFly1984/react-google-maps-api/pull/1443 the types are not up to date yet. Since this is essentially a configuration, I don't think we would have add any additional documentation here.

But be sure to use the beta channel and add the mapId to both the load script and the map element itself.

**Comment by moneszarrugh** [comment]
> As mentioned in #1443 the types are not up to date yet. Since this is essentially a configuration, I don't think we would have add any additional documentation here.
> 
> But be sure to use the beta channel and add the mapId to both the load script and the map element itself.

I updated to the latest version and now it works! thanks.

**Comment by nathanaelphilip** [comment]
Full example if anyone else needs it.

```
<LoadScript
      googleMapsApiKey={process.env.NEXT_PUBLIC_GOOGLE_API_KEY}
      mapIds={['d22d3e5e4ad3ba33']}
    >
      <GoogleMap
        mapContainerStyle={containerStyle}
        center={center}
        zoom={10}
        options={{ mapId: 'd22d3e5e4ad3ba33' }}
      >
        <Marker
          position={{ lat: 37.772, lng: -122.214 }}
        />
      </GoogleMap>
    </LoadScript>
```

**Comment by captDaylight** [comment]
I'm having an issue getting my styles to work when I try using hooks:

``` js
  const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: 'API_KEY,
    mapIds: ['MAP_ID'],
  });
```

``` error
Error: Loader must not be called again with different options. 
```
However, when I comment out the `mapIds` line, it the display works (but no styles are attached).

**Comment by niccolosaurus** [comment]
@captDaylight Did you ever get this working for you? I am having the same issue and I have not been able to get it to work?

**Comment by coreyar** [comment]
You can make this work by calling `setMapId` on the `onLoad` map callback.

**Comment by manuelgeek** [comment]
@niccolosaurus did you ever get this working?

@coreyar there's no such function as `setMapId`. Also, mapId cannot be updated after map is initialized

**Comment by coreyar** [comment]
@manuelgeek 
```
const onLoad = useCallback((map: any) => {
    const bounds = new window.google.maps.LatLngBounds(center);
    map.fitBounds(bounds);
    map.setMapId(MAP_ID)
    setMap(map)
  }, [])```
