### ISSUE TITLE
getPixelPositionOffset in OverlayView is called only once with width and height equal zero

### ISSUE THREAD

**Issue by vvmarulin** [JustFly1984/react-google-maps-api#165]
## Environment

os: MacOS Mojave 10.14.3
node: 10.16.0
react: 16.8.6
webpack: 4.29.6
@babel 7.4.0
@react-google-maps/api: 1.3.0 

## How is it behave?

If `OverlayView` component is rendered only after some event (for example after click on a marker) then `getPixelPositionOffset` function is fired only once with `offsetHeight` and `offsetWidth` equal to `0`. But if I move the map or change zoom value then the function will be called with correct values of `width` and `height`.

https://codesandbox.io/s/react-google-maps-overlay-view-issue-94o34

It happens because `getPixelPositionOffset` function is called before children of an `OverlayView` component were mounted in DOM by `createPortal`.

## How should it behave correctly?

It would be great if the function is called only when content of `OverlayView` is mounted to DOM, i.e. only with correct width and height. But it's also fine if the function is called twice (once with zero values and second time with correct values). For example, the function is called twice in other react google map repository. There are two calls in other repository because old `unstable_renderSubtreeIntoContainer` function is used to render children. This unstable function has a callback as the forth argument so `onPositionElement` is called again in `OverlayView` after children are mounted. Unfortunately `createPortal` doesn't accept a callback.

**Comment by JustFly1984** [comment]
Can you make a PR?

**Comment by vvmarulin** [comment]
@JustFly1984 
I created a PR. I'm not sure if it's the best solution but it solves the issue. I also added a gatsby example because I didn't manage to find another way to test the changes.

**Comment by tmasunda** [comment]
Hi @JustFly1984 is this issue resolved in version 1.3.0? I am getting the same problem discussed here with getPixelPositionOffset.

**Comment by JustFly1984** [comment]
Sorry had no time to publish next version, will do that tomorrow. it will be 1.4.0

**Comment by tmasunda** [comment]
> Sorry had no time to publish next version, will do that tomorrow. it will be 1.4.0

Thanks for the update.

**Comment by JustFly1984** [comment]
it is published, please test

**Comment by tmasunda** [comment]
> it is published, please test

Thank you. Its now working beautifully.
