### ISSUE TITLE
useLoadScript() throws "invariant requires an error message argument"

### ISSUE THREAD

**Issue by filingroove** [JustFly1984/react-google-maps-api#170]
# Please provide an explanation

## Your Environment

os:
```mac```
node --version
```v10.15.3```
react version
```16.8.7```
webpack version
```4.28.3```
@babel version
``` @babel/core@7.2.2```
@react-google-maps/api version
```1.3.0```
## How is it behave?
When trying to use `useLoadScript()` hook, I get following error: 
```
browser.js:22 Uncaught Error: invariant requires an error message argument
    at invariant (browser.js:22)
    at reactgooglemapsapi.es.production.js:331
    at commitHookEffectList (react-dom.development.js:18059)
    at commitPassiveHookEffects (react-dom.development.js:18086)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at commitPassiveEffects (react-dom.development.js:19712)
    at wrapped (scheduler-tracing.development.js:177)
    at flushFirstCallback (scheduler.development.js:99)
    at flushWork (scheduler.development.js:216)
    at MessagePort.push../node_modules/scheduler/cjs/scheduler.development.js.channel.port1.onmessage (scheduler.development.js:619)
```

The code is simple:
```js
export default function Map( props ) {
    const { isLoaded, loadError } = useLoadScript( {
        googleMapsApiKey: googleConfig.apiKey,
        id: props.id + '-script-loader',
    } );

    if ( loadError ) {
        return <div>Map cannot be loaded right now, sorry.</div>
    }

    return (
       <>{  isLoaded ? <GoogleMap {...props} /> : <LoadingAnimation /> }</>
    )
}
```
## How should it behave correctly?
It should not throw the error :)

**Comment by JustFly1984** [comment]
did you forget to include libraries prop? I know this is a bug with calling invariant, I will fix it then I have time, or if somebody provides a PR.

**Comment by shobishani** [comment]
By using useGoogleMap() hook I get this same issue
`Uncaught Error: invariant requires an error message argument
    at invariant (browser.js?40b6:24)
    at v (reactgooglemapsapi.es.production.js?4639:1)
    at NewGoogleMap (NewGoogleMap.tsx?f44d:10)
    at ProxyFacade (react-hot-loader.development.js?c2cb:766)
    at renderWithHooks (react-dom.development.js?61bb:12938)
    at mountIndeterminateComponent (react-dom.development.js?61bb:15020)
    at beginWork (react-dom.development.js?61bb:15625)
    at performUnitOfWork (react-dom.development.js?61bb:19312)
    at workLoop (react-dom.development.js?61bb:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:149)`

**Comment by JustFly1984** [comment]
@shobishani sorry about that, but check libraries prop.

**Comment by shobishani** [comment]
@JustFly1984 
I have the libraries prop
`const libs = ['places', 'visualization', 'drawing', 'geometry'];`

 > const { isLoaded, loadError } = useLoadScript({
 >    googleMapsApiKey: 'some-super-api-key',
 >    libraries: libs,
 >  });

**Comment by shobishani** [comment]
`useGoogleMap()` does not have any props.

**Comment by Sigizmund2012** [comment]
> By using useGoogleMap() hook I get this same issue
> @shobishani sorry about that, but check libraries prop.

Same issue when call useGoogleMap(). What libraries prop do you mean? Explain please.

**Comment by shobishani** [comment]
@Sigizmund2012  do you happen to know how to stop map fitting bounds.
Whenever map is updated `map.fitBounds()` is being called somewhere in the library.
I don't want that I want it to `fitBounds` when I want according to my Application.

**Comment by Sigizmund2012** [comment]
> do you happen to know how to stop map fitting bounds.

No, sorry, I'm not very expirienced in React

**Comment by filingroove** [comment]
@JustFly1984 

I think the docs are not complete for `useLoadScript()` :) 

Please include `libs` in the docs if it's a required argument https://react-google-maps-api-docs.netlify.com/#useloadscript

**Comment by filingroove** [comment]
@JustFly1984 

> I know this is a bug with calling invariant, I will fix it then I have time, or if somebody provides a PR.

For me, this exception in Map component causes UI to break completely :) I think I'll to revert to using `LoadScriptNext` for the time being

**Comment by Sigizmund2012** [comment]
If just remove invatiant calls and import from https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/map-context.ts it fix the problem?

**Comment by Sigizmund2012** [comment]
Is there another way to get map instance without call useGoogleMap() ?

**Comment by shobishani** [comment]
Yes use onLoad with GoogleMap component and you’ll get the map instance
Defiantly you can pass to parent with callback.

**Comment by Sigizmund2012** [comment]
> Yes use onLoad with GoogleMap component and you’ll get the map instance Defiantly you can pass to parent with callback.
It's work, but hacky :)

**Comment by JustFly1984** [comment]
I consider this issue closed.

**Comment by hc-12** [comment]
Stumbled into the same issue with `useGoogleMap()`. Perhaps leave this issue open until it is resolved so we can track it?

**Comment by JustFly1984** [comment]
@hc-12 can you please make a reproduction in codesandbox?

**Comment by JustFly1984** [comment]
considering issue closed
