### ISSUE TITLE
setStreetView()  not an instance of StreetViewPanorma

### ISSUE THREAD

**Issue by shobishani** [JustFly1984/react-google-maps-api#172]
With these options to 
 ```
    streetView: false,
    streetViewControl: false,
```
to GoogleMap component
```
    <GoogleMap
      onLoad={ onLoad }
      mapContainerStyle={ { width: '100%', height: '100%' } }
      options={ mapoptions }
    >
      { props.children }
    </GoogleMap>;
```
It throws Error

`InvalidValueError: setStreetView: not an instance of StreetViewPanorama`

But if I don't pass these two, by default these are false then it works well, So I thought worth mentioning.

**Comment by xalisys** [comment]
@shobishani , "streetView" in google maps options is not boolean its object instead, here are [google map ocs](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions)

We pass map options as it is to google map instance without any manipulation.

**Comment by shobishani** [comment]
Oh! Thanks @xalisys
