### ISSUE TITLE
How to fetch places from Google API

### ISSUE THREAD

**Issue by vnscriptkid** [JustFly1984/react-google-maps-api#174]
# Please provide an explanation

Hi, now I want to fetch places from Google API by creating new instance of google.maps.places.PlacesService

I managed to use useLoadScript to get access to `map` and `google` instance. But it turned out that though maps do exist in google but it has no `places`. I got error `Can not access PlacesService of undefined` as you might guess. 

So what is the solution for this. Is there anyway I can fetch places ?

**Comment by JustFly1984** [comment]
You need to add property `libraries` with array of libraries, in your case `libraries=["places"]`
