### ISSUE TITLE
How to determine that maps isn't loaded

### ISSUE THREAD

**Issue by ILoyso** [JustFly1984/react-google-maps-api#176]
# Please provide an explanation

Hi! I want to connect other maps if google maps aren't loaded (for test it is enough to put the flag "block request domain" in chrome devtools).

I tried to use`useLoadScript`, but it didn't help. Variable loadError returns undefined anyway, my app crashed and console error is `Uncaught ReferenceError: google is not defined'`.

Waiting: when access to Google cards is blocked, start the user function and load other cards

Thanks in advance!

**Comment by JustFly1984** [comment]
@ILoyso 
I think you can use <ErrorBoundary around google maps component, and handle `Uncaught ReferenceError: google is not defined` error in fallback

**Comment by ReiiYuki** [comment]
Hey I think this is same as what I found in #184

**Comment by Ksenia0479** [comment]
`loadError` is still `undefined`. Is there a way to get rid of this issue besides of using <ErrorBoundary />?
