### ISSUE TITLE
Uncaught TypeError: a.url.substr is not a function when requiring url in <GroundOverlay />

### ISSUE THREAD

**Issue by itsmarkodonnell** [JustFly1984/react-google-maps-api#1787]
Using typescript when importing a *.png for use in the ``<GroundOverlay />`` component - the browser throws a ``Uncaught TypeError: a.url.substr is not a function`` error.

Everything compiles correctly, but seeing the issue in the browser - I can't seem to track where the issue is 🤷‍♂️ 
 
## Your Environment

Using an out-of-the-box CRA with typescript template 
``npx create-react-app my-app --template typescript``

with `` @react-google-maps/api": "^1.13.0"``

## Code Snippet
    import React from "react";
    import styled from "styled-components";
    import {
      GoogleMap,
      useLoadScript,
      Marker,
      Circle,
      GroundOverlay,
    } from "@react-google-maps/api";
    import { UseLoadScriptOptions } from "@react-google-maps/api/dist/useLoadScript";
    import { Libraries } from "@react-google-maps/api/dist/utils/make-load-script-url";
    import { RouteComponentProps } from "@reach/router";
    import mapStyles from "./styles";
    import markerData from "./data";
    require("dotenv").config();

    const MAP_BOUNDS = {
      north: 54.58497002626005,
      south: 54.57637503025374,
      east: -5.924422572667526,
      west: -5.939446041311975,
    };

    const libraries: Libraries = ["geometry", "places"];

    export const MapPage = (props: RouteComponentProps) => {
      const loadScriptOptions: UseLoadScriptOptions = {
        googleMapsApiKey: process.env.REACT_APP_GOOGLE_API_KEY!,
        libraries,
      };
      const { isLoaded, loadError } = useLoadScript(loadScriptOptions);
      if (loadError) return <h1>Error loading maps</h1>;
      if (!isLoaded) return <h1>Loading maps</h1>;
      return (
        <MapContainer>
          <GoogleMap
            mapContainerStyle={{ width: "100vw", height: "100vh" }}
            zoom={16}
            center={{ lat: 54.5824, lng: -5.9325 }}
            options={{ styles: mapStyles, disableDefaultUI: true }}
          >
            <GroundOverlay
              bounds={MAP_BOUNDS}
              url={require("./botanic-map.png")}
            ></GroundOverlay>
          </GoogleMap>
        </MapContainer>
      );
    };

    const MapContainer = styled.div`
      width: 100vw;
      background-color: pink;
      position: relative;
      min-height: 100%;
      display: flex;
      justify-content: center;
      align-content: center;
      overflow: hidden;
      z-index: 30;
    `;

**Comment by JustFly1984** [comment]
@itsmarkodonnell  try to replace styled components with simple jsx/css. I have another project where styled components conflicts with framer-motion, preventing the context passing through component tree.
Also possible that require works not as you expecting. - Try to use simple string url - without require, and move png to public directory of your create-react-app.

Please instead of posting your code, provide minimal reproduction in codesandbox.io

**Comment by itsmarkodonnell** [comment]
Thanks @JustFly1984 - removing styled components resolved  the problem. Strangely however styled components works in codesandbox.io with the exact same library versions.

 https://codesandbox.io/s/naughty-wu-i3iwb?file=/src/App.tsx

Thanks for your help, was able to work around it.

**Comment by JustFly1984** [comment]
It is not about styled components version, but about how react context is passed through component tree, and styled components architecture does not support to pass additional contexts. They do care to pass its own context, and react-redux context, but fails to care about other custom contexts.

If you have single component per page, you can miss this issue, but if your app requires performance for animation or 3d, and you have a lot of state management, you need to have a lot of smaller memorised components, to limit re-rendering, and here styled components bites painfully.

If somebody have solution how to fix this behaviour, please pm me.
