### ISSUE TITLE
Question: can we display a loader while gmpa is loading, and display the map after load ?

### ISSUE THREAD

**Issue by Aarbel** [JustFly1984/react-google-maps-api#179]
Gmap is sometimes slow to load (the library and the tiles inside it), could be great to display a beautifull loader while tiles / marker are loading.

Do you know how to achieve this UI feature with this lib ?

Thanks a lot for your help !

**Comment by uriklar** [comment]
The `GoogleMap` component has an `onTilesLoaded` callback. You can use some kind of `areTilesLoaded` flag and show a loader until that flag is set to true by `onTilesLoaded`

Please use our [Spectrum channel](https://spectrum.chat/) for usage questions
