### ISSUE TITLE
<section/> html tag

### ISSUE THREAD

**Issue by isaacewing** [JustFly1984/react-google-maps-api#1795]
# Issue 

just curious, has anyone else faced this issue, when using a `<section/>` tag, the map renders the basic buttons, but the map itself does not load anything. however, if you use a `<div/>` tag, it works fine... anyone else find this issue odd... and maybe know why that is happening 

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Please provide an explanation
`<div/>` tags work find when building the render portion, 
`<section/>` tag allows rendering but the map is always blank

## Your Environment

os: mac 

node: 16.x

react: version 16.18.x

webpack version 4.x

@babel version latest

@react-google-maps/api version latest

## How is it behave? 
it's extra naughty 

## How should it behave correctly? 
it should render like in the examples, but the map (those cute little slices of visual data) fail to load when nesting the map inside a `<section/>` tag

## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/happy-archimedes-p9fpx?file=/src/App.js

**Comment by JustFly1984** [comment]
Sorry, but I do not understand your issue without reproduction on codesandbox.io

**Comment by isaacewing** [comment]
no problem, i've thrown together a simple example
https://codesandbox.io/s/happy-archimedes-p9fpx?file=/src/App.js

**Comment by JustFly1984** [comment]
you had a typos

https://codesandbox.io/s/recursing-burnell-js5du?file=/src/App.tsx
