### ISSUE TITLE
Version 1.4.0 regression - DependencyNotFoundError Could not find dependency: 'invariant' relative to '/node_modules/@react-google-maps/api/dist/reactgooglemapsapi.cjs.development.js'

### ISSUE THREAD

**Issue by uriklar** [JustFly1984/react-google-maps-api#181]
This error happens in codesandbox but not in locally ran create-react-app:
https://codesandbox.io/s/distracted-thunder-r4doq

When changing version to 1.3.0 the error goes away

**Comment by JustFly1984** [comment]
have published 1.4.1, please test
