### ISSUE TITLE
DrawingManager onOverlayComplete not firing when setting drawingMode null

### ISSUE THREAD

**Issue by mjcampagna** [JustFly1984/react-google-maps-api#182]
Using the native Google Maps API, while drawing a polygon, setting `drawingManager.setDrawingMode(null)` fires the 'overlaycomplete' event.

Using react-google-maps-api, this does not appear to be the case.

Given boilerplate like this:

```js
const [cancelFlag, setCancelFlag] = useState(false)
const [drawingMode, setDrawingMode] = useState(null)

const handleOverlayComplete = (e) => {
  if (cancelFlag) {
    e.overlay.setMap(null) // deletes the shape
  } else {
    // do things with the shape ...
  }

const onClickOutsideMap = () => {
  setCancelFlag(true)
  setDrawingMode(null)
}

const onPressEscapeKey = () => onClickOutsideMap()
...
<DrawingManager
  drawingMode={drawingMode}
  onOverlayComplete={handleOverlayComplete}
  ...
```

Two handlers, `onClickOutsideMap` and `onPressEscapeKey`, do `setCancelFlag(true)`, then `setDrawingMode(null)`. 

The latter, I would expect to trigger the onOverlayComplete event, which **IS** the case when using the native Google Maps API. However, `setDrawingMode(null)` does **NOT** trigger the 'overlaycomplete' event using react-google-maps-api.

The purpose of the above is to cancel a polygon mid-draw.

**With react-google-maps-api, `setDrawingMode(null)` mid-draw causes the shape to "auto-complete" -- the last point connects to the first, completing the shape -- but the 'overlaycomplete' event does not fire.**

**Comment by mjcampagna** [comment]
For what its worth, the workaround I've had to employ for this is:

```js
        <DrawingManager
          drawingMode={drawingMode}
          onLoad={(drawingManager) => {
            event = window.google.maps.event.addListener(
              drawingManager, 'overlaycomplete', onOverlayComplete
            )
          }}
          onUnmount={() => {
            window.google.maps.event.removeListener(event)
          }}
          ...
```

And then to NOT use the `onOverlayComplete` prop on DrawingManager. =(

**Comment by uriklar** [comment]
Hi @mjcampagna I've been trying to get this exact behaviour in my app! I didn't know about `onOverlayComplete` being fired. I'll work on a PR to add this.

**Comment by uriklar** [comment]
@mjcampagna mmm... I guess it wasn't fixed :-/
I'll try giving it another look. I was sure I had it working already...

**Comment by JustFly1984** [comment]
@uriklar what is the status?

**Comment by uriklar** [comment]
@mjcampagna Maybe i'm missing something, but I tried getting the desired behaviour with vanilla google maps api and i don't see the overlaycomplete event being called here as well.
Check out this sandbox (code is in index.html)
https://codesandbox.io/s/lucid-rain-v3wsc

**Comment by uriklar** [comment]
@mjcampagna also, i've revisited my codesandbox and it works!
https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-8y7jo

So I guess we can close this issue?
