### ISSUE TITLE
LoadScript, set mapIds or single country id

### ISSUE THREAD

**Issue by Kiredam9102** [JustFly1984/react-google-maps-api#1833]
Hi, how can i set a single country? Is it possible using LoadScript?
I tried passing it as prop mapIds = ["us"] but it doesn't work.

```
import { LoadScript } from "@react-google-maps/api";
```
```
    <LoadScript
      id="script-loader"
      googleMapsApiKey={apiKey}
      language={"en"}
      region={"EN"}
      version={"weekly"}
      mapIds={["us"]}
      libraries={["places"]}
    >
```
Would anyone know how to help me? 
Thanks

**Comment by JustFly1984** [comment]
please use discussions instead of issues.

You can use onLoad callback to receive map object, and work with it according official docs.
