### ISSUE TITLE
`onload` doesn't confirm that `google` is initialized!

### ISSUE THREAD

**Issue by ReiiYuki** [JustFly1984/react-google-maps-api#184]
Hi

https://github.com/JustFly1984/react-google-maps-api/blob/5dd1be2cf435f5ab5f711ff63e86ff6eabd0ee43/packages/react-google-maps-api/src/utils/injectscript.ts#L24

`onload`  doesn't confirm that `google` is initialized!

```html
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>
```

I think you should resolve loaded status by trigger some callback function like initMap.

**Comment by JustFly1984** [comment]
@ReiiYuki  Can you make a PR please?

**Comment by ReiiYuki** [comment]
@JustFly1984 OK! now it's on #187

**Comment by baldmountain** [comment]
I just ran into this. Sometimes google is ready, but most times not.

**Comment by ReiiYuki** [comment]
@JustFly1984 From the latest MR I found that it doesn't cover every case of loaded script.

The case I found is I use `useLoadScript` in multiple components.

The logic of `injectScript` which is used in `useLoadScript` is the following:
- if existing script tag resolve it as loaded!
- otherwise create new script tag then make it resolve when callback (`initMap`) is called.

This mean if we call useLoadScript with the same id multiple times, if `initMap` doesn't call yet, it will resolve as loaded because it found existing script tag.

**Comment by ReiiYuki** [comment]
I suggest that we should check if script is already loaded by create new window attribute as save the value of loaded id in that attribute.

**Comment by JustFly1984** [comment]
@ReiiYuki can you make a PR?

**Comment by coulson84** [comment]
Have added a PR here https://github.com/JustFly1984/react-google-maps-api/pull/194 that should fix this
