### ISSUE TITLE
Markers are not always correctly removed from map when Marker unmounts.

### ISSUE THREAD

**Issue by jwalton** [JustFly1984/react-google-maps-api#1848]
## Please provide an explanation

Sometimes when removing a marker from the set rendered by react, the marker gets left behind and is not removed from the map.

## Your Environment

os: mac

node --version: v12.19.1
react version: 16.13.1
webpack version: 4.44.1
@babel version: 7.11.6
@react-google-maps/api version: 2.0.2

## How is it behave?

[Here's a quick demo](https://codesandbox.io/s/stupefied-worker-8vqt8?file=/src/Map.tsx) which renders a bunch of points using `supercluster`.  This is (very nearly) following the [supercluster tutorial for google maps](https://www.leighhalliday.com/google-maps-clustering).

supercluster gives us a set of points to render.  At the start, we're zoomed out enough that we just render one:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/1771003/102547891-db5d0080-4087-11eb-9691-e4f0b399cae0.png">

Note the "Rendering 1 markers" at the top of the page.  As we zoom in, supercluster adds more markers.  Here we're zoomed in 4 steps:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1771003/102548025-0c3d3580-4088-11eb-8622-8da7758a781b.png">

Then when we zoom back out, supercluster removes markers again, until we're back at 1:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1771003/102548071-195a2480-4088-11eb-8073-8b1202173344.png">

But, there is obviously more than just one marker being rendered.  The problem is that react-google-maps-api is leaking markers - markers are unmounting but are not being removed from the map.

You can also verify this with a quick change to [Marker.tsx](https://github.com/JustFly1984/react-google-maps-api/blob/develop/packages/react-google-maps-api/src/components/drawing/Marker.tsx).  In `componentDidMount()`:

```diff
    const marker = new google.maps.Marker(markerOptions)
+    this._marker = marker
```

And in `componentWillUnmount()`:

```diff
  componentWillUnmount(): void {
    if (this.state.marker !== null) {
      if (this.props.onUnmount) {
        this.props.onUnmount(this.state.marker)
      }

      unregisterEvents(this.registeredEvents)

      if (this.props.clusterer) {
        this.props.clusterer.removeMarker(
          // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
          // @ts-ignore
          this.state.marker,
          !!this.props.noClustererRedraw
        )
      } else {
        this.state.marker && this.state.marker.setMap(null)
      }
+    } else if (this._marker) {
+      console.log('Would have leaked');
+      this._marker.setMap(null);
    }
  }
```

This will log a bunch of "Would have leaked" and will fix the problem (although this is a bit of a hack, obviously).

## How should it behave correctly?

Markers should be removed from the map when Marker unmounts.

## basic implementation of incorrect behavior in codesandbox.com

https://codesandbox.io/s/stupefied-worker-8vqt8?file=/src/Map.tsx

**Comment by JustFly1984** [comment]
If somebody wants to champion this issue - your PR is welcome.

**Comment by jwalton** [comment]
If no one else is looking at it by then, I’ll start working on a PR in the new year. When I tried the “hacky ” fix I listed above, I noticed performance for removing markers was obnoxiously slow - I’d like to figure out if this is something specific to my environment or figure out a fix for this while I’m poking around here.

**Comment by JustFly1984** [comment]
@jwalton your PR is welcome
