### ISSUE TITLE
Dynamically changing language or libraries

### ISSUE THREAD

**Issue by slorber** [JustFly1984/react-google-maps-api#186]
Hi,

On 1.4.2

It is complicated to change at runtime the language or libraries supported. Clearly it's not the fault of this library, google does not make it easy. 

One can't simply pass a language prop to the map or places autocomplete to customize to the needed language/libraries, we have to reload the global google script with the correct language/libraries.

Even in this page, the demo which allow to change languages do that (reloading the page with a new script with language in querystring): https://developers.google.com/maps/documentation/javascript/localization

The workaround to solve this issue is:
- remove old google script
- add new one with a new url

Demo: http://jsfiddle.net/2AKqM/

--------------------------

I think it would be cool if this lib made all this process easier.

As it's not possible to use multiple languages on the same page, I think:
- The lib should recommend loading the script at most once at the same time
- The lib should ensure at most one google script is in <head>, and eventually do the cleanup

Currently, if the language change, the url will change, and we will try to insert a new script but this will be [prevented](https://github.com/JustFly1984/react-google-maps-api/blob/5dd1be2cf435f5ab5f711ff63e86ff6eabd0ee43/packages/react-google-maps-api/src/utils/injectscript.ts#L14), unless we change the id of the script.

But if we change the id of the script (for example, by putting language and libraries in it), then the older script tags remains in the dom and are not cleaned. The more we use the app and the more scripts get loaded over time and no cleanup is done.

I don't have a proper solution to this problem yet but would like to have your insight on this topic

-----

Related:
- https://github.com/JustFly1984/react-google-maps-api/issues/186
- https://github.com/JustFly1984/react-google-maps-api/pull/188
- https://github.com/JustFly1984/react-google-maps-api/pull/189

**Comment by slorber** [comment]
Also, if we call again injectScript (due to a changing url/id) the state "loaded" remains true. I think in cases we are loading a new script, we want to reset the state so that we can show a spinner on something on our apps

**Comment by JustFly1984** [comment]
The language change does reloads the script, but libraries change does not.

**Comment by slorber** [comment]
@JustFly1984 not sure what you mean.

The libraries are included in the url:
https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/utils/make-load-script-url.ts#L9

Which means if the libraries chance, the url change, and the script reloads.

Is there another way to add a maps library dynamically without reloading the script?

**Comment by JustFly1984** [comment]
@slorber there is no way to reload libraries or languages dynamicaly without reverse engineering google maps api itself
