### ISSUE TITLE
Reverse engineer google maps script, download it and use as part of library.

### ISSUE THREAD

**Issue by JustFly1984** [JustFly1984/react-google-maps-api#190]
@uriklar @FredyC @slorber 

Just my ideas

I think to try an idea: download whole script with and without libraries, transform it with some tool like lebab to ES6, and use it as stable version.

Use chained lazy-loading and code splitting.

Advantages: 
- We are in control of all the content, and can organize more efficient code loading and execution.
- We can typecheck and audit google's code. Potentially - optimize code.
- Better understanding of under-the-hood of google maps API
- Our community could get more traction, and more attention.

Downsides: 
- Obviously more work
- Maintaining that when new google maps api version is released.

Complications: 
- How many languages is there supported?

Could sound crazy, but in general it could improve performance. Only god knows which kind of legacy code is there :)

**Comment by FredyC** [comment]
Well, it definitely sounds crazy, but why not :) Perhaps we could ask Google people first if they would be willing to provide access to the source code. It's a long shot but could save some nerves for sure. But don't tell them you want to remove tracking 😆

It's a huge responsibility imo. You might have some spare time now to set up the whole thing, but what about a year later? Google people are paid for maintaining it. Unless you want to set up donations and hope for the best, it's unlikely you will have the same motivation long therm. Sure, there are other people, but not that many to cover for such a big endeavor.

Besides, I think it's kinda out of the scope of this project. You will hardly convert whole maps api to React. That would be even worse to maintain changes. And vendor locking to React sounds nice to us, but considering other frameworks opens the door for more maintainers. If anything, it would need to be a separate open-source project which could be used here.

> * Our community could get more traction, and more attention.

Perhaps that's something that should improve first. Much more people are still stuck with "old project" and if it works for them, why would they bother with this project? Without increasing visibility, there won't be any traction.

![image](https://user-images.githubusercontent.com/1096340/61583210-34dc9b00-ab35-11e9-9825-1545a9954cf1.png)

![image](https://user-images.githubusercontent.com/1096340/61583208-2d1cf680-ab35-11e9-83f9-fed801927217.png)

Frankly, I am not so sure it's worth the hassle. Maps are usually something that can get loaded later and doesn't block other interactions with the page. The speed of loading mostly depends on connectivity with a server which in case of google might be always better than hosting it on your own. You could gain a couple of ms by some techniques, but the overall noticeable performance might not be that different. It's hard to measure something like that now.

**Comment by JustFly1984** [comment]
@FredyC React will move on to 17 pretty much soon, and then there will be much more people searching for alternative to react-google-maps. Patching forks as they do now will be too much tedious task. 

As of now, there is a lot of people who just use most searchable stuff with more stars, even if docs are not updated, but eventually people are looking at issues, and I'm maintaining a constant noise there.

Do you have any ideas how to connect with people from google? or how to bring more attention to our project?

**Comment by FredyC** [comment]
> React will move on to 17

There is a way more breaking changes and maps will be the least concern imo. There are still way too many libraries that are not either maintained or don't worry about StrictMode yet.

Luring people in isn't probably some exact science, but perhaps some article which goes through some aggregators can bring some attention. Or actively seeking questions regarding react google maps and redirecting people to an active community here.

> Do you have any ideas how to connect with people from google

No idea. I suppose through the public issue tracker is not the best way. I suppose it will have to go through some email communication until you reach relevant people.

**Comment by JustFly1984** [comment]
One more thing is that google maps team constantly updates new api, and it is not possible to update tomchew's lib, since it has broken build.

**Comment by slorber** [comment]
Not sure it's a good idea imho, many google maps scripts seems lazy loaded and they probably want to keep the ability to upgrade their code live without asking your permission. Maybe they use private apis and want ability to do breaking changes or whatever... I don't know, but if they are ok with your idea, why not. But I doubt they will answer or be ok.
