### ISSUE TITLE
How migrate from react-google-maps@9.4.5

### ISSUE THREAD

**Issue by NicoSan20** [JustFly1984/react-google-maps-api#1915]
Hello everybody,

I want to migrate react-google-maps to @react-google-maps/api.

In my example code, I use those :

import { withScriptjs, withGoogleMap, GoogleMap } from "react-google-maps";
import { SearchBox } from "react-google-maps/lib/components/places/SearchBox";

Being new in development, let me ask you what is the best adaptation to use to migrate easily to @react-google-maps/api ?

Thank you in advance at all for your answers.

Best regards

**Comment by JustFly1984** [comment]
@NicoSan20 take a look at examples and docs, @eact-google-maps/api is simpler than react-google-maps

**Comment by linkb15** [comment]
I cant find SearchBox from the components. on which page shld i find it?

**Comment by linkb15** [comment]
> I cant find SearchBox from the components. on which page shld i find it?
Found it

https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api-gatsby-example/src/examples/example-search-box.js
