### ISSUE TITLE
how to draw not overlapping polygons 

### ISSUE THREAD

**Issue by zilkenberg22** [JustFly1984/react-google-maps-api#1936]

**Comment by mikevb3** [comment]
you would have to do your own implementation, i did one with turf.js just this past week.

on the onPolygonComplete event, each time you draw a new one, you iterate your existing polygons, and do a validation with booleanOverlaps, if true, then you can do a "difference" of the polygon paths. Later i will share a modified snippet, hope it could help you or someone else.

**Comment by MuhmdRaouf** [comment]
Hey @mikevb3, Would you share with us ur implementation please 😄
