### ISSUE TITLE
GoogleMap causing "Maximum update depth exceeded"

### ISSUE THREAD

**Issue by FredyC** [JustFly1984/react-google-maps-api#195]
This is quick and dirty but should be roughly what my component looks like: https://codesandbox.io/s/wonderful-sun-2jqp2

You'll need to set your own google maps key in `YOUR_API_KEY`

This actually get a CORS error, but the structure should be correct.

_Originally posted by @baldmountain in https://github.com/JustFly1984/react-google-maps-api/pull/187#issuecomment-514654127_

**Comment by FredyC** [comment]
Well, looks like you might have actually discovered a bug. Here is the modified sandbox that actually works...

https://codesandbox.io/s/optimistic-worker-19frf

However, when options object is not memoized, the GoogleMap goes into an endless update loop. Basically, because it's a PureComponent which compares shallowly only. But there are some shenanigans does inside the `applyUpdatersToPropsAndRegisterEvents` which I don't fully understand yet.

https://github.com/JustFly1984/react-google-maps-api/blob/4f27159804c3d3b052a310dda58f614262088ef0/packages/react-google-maps-api/src/utils/helper.ts#L65

**Comment by JustFly1984** [comment]
@FredyC 
Sure, I think we can rewrite it all to hooks, since hooks are here for long)

@uriklar

**Comment by tawfek** [comment]
hi , im facing same bug here !

**Comment by tawfek** [comment]
this is my **3rd day trying to fix this bug** 
any help  ? 

errors im getting : 
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate.`

---- 

`The above error occurred in the <GoogleMap> component:`

---- 
`A cross-origin error was thrown. React doesn't have access to the actual error object in development.`


my code :

`
import _ from "lodash";
import '../../styles/map.scss';
import { compose, withProps,withHandlers } from "recompose";
import React,{createRef, useMemo, useRef, useState} from 'react' ;
import ReactDOM from 'react-dom';
import circleVector_m1 from '../../styles/images/map/dot.png'
import Marker_vector from '../../styles/images/map/t2.png'
import {  useTranslation  } from 'react-i18next';
import MAP_DATA from '../../fake_data/map_data.json'
import {GoogleMap,useGoogleMap  ,MarkerClusterer,useLoadScript ,Marker} from "@react-google-maps/api";
import { useCallback ,useEffect } from "react";


   const enhance = _.identity;
   const API_KEY = process.env.REACT_APP_GOOGLE_MAP_API;

    
   const MapC = (props)=>{
  const p = props
  const realRef = useRef(null)
  const defaultCenter =p.defaultCenter
  const defaultZoom = p.defaultZoom;
  const [MapCenter,setMapCenter] = useState({center:defaultCenter})  
  const [t,st] = useState(null)
  const [MapZoom,setMapZoom] = useState(defaultZoom)
  const mapOptions ={ MapData :{positions:p.markers}}
 
  const onMapLoad = ((map)=>{
    realRef.current = map
    const google = window.google; // yeah, I know...
    const DrawButtonDiv =(<p>{MapCenter.lng}</p>)
    const controlButtonDiv = document.createElement('div');
    ReactDOM.render(DrawButtonDiv, controlButtonDiv);
    map.controls[google.maps.ControlPosition.TOP_CENTER].push(controlButtonDiv);
    
  })
  const CenterCallback = useCallback((e)=>setMapCenter(e))
const handleMapCenter = useCallback(()=> {
  if(!realRef.current) return ;
    if(realRef){
      const newPos = realRef.current.getCenter().toJSON();
      CenterCallback((p)=>({...p,center:{lat:newPos.lat,lng:newPos.lng}}))

    }else{alert('not loaded')}
   },[realRef,MapCenter,setMapCenter,CenterCallback])

const HandlePanTo = useCallback((location)=>{
  if(!realRef.current) return console.log('shit',location) ;
  const google = window.google; // yeah, I know...
  console.log('panning to :' ,location)
   realRef.current.panTo({lat:location.lat,lng:location.lng})
},[realRef,window])


const handelUnmount = useCallback((map)=>{
  realRef.current = map
},[])

const RealmapOptions= ()=>({
  zoom:MapZoom,
  center:MapCenter.center
})
const ContainerStyles = ()=>({
  width:'100%',
  height:'80vh'
})

const memoMapOptions  = useMemo(RealmapOptions,[MapZoom,MapCenter])
const memoContainerStyles = useMemo(ContainerStyles)
    return (
        <GoogleMap 
         mapContainerStyle={memoContainerStyles}
         options={memoMapOptions}
         onLoad={onMapLoad}
         onCenterChanged={handleMapCenter}
         onUnmount={handelUnmount}
        > 
      
        </GoogleMap>
        
       )
      }
   

      
const GMap = ()=>{
  const {i18n} =  useTranslation(); 
  const [mapLoadSettings,setMapSettings] =useState({
    googleMapsApiKey:API_KEY,
    language:i18n.language,
    region:i18n.language=='ar'?'iq':'us',
    version:'weekly'
   });
   const { isLoaded, loadError } = useLoadScript(mapLoadSettings)
   
   const MemoizedMapCWithHook = useMemo(()=><MapC defaultCenter={{lat: 33.782, lng: 33.447 }} defaultZoom={8} markers={MAP_DATA} />)
  if(isLoaded){
    return MemoizedMapCWithHook
    }else{return  'map is loadding...'}

} 


    

export default (GMap);

`

**Comment by wwwhatley** [comment]
Why was this closed? It was not resolved... @JustFly1984
