### ISSUE TITLE
Autocomplete/Standalone not firing onPlaceChanged/onPlacesChanged

### ISSUE THREAD

**Issue by Mrman** [JustFly1984/react-google-maps-api#196]
# Samples on https://react-google-maps-api-docs.netlify.com/#autocomplete do not trigger onPlaceChanged events

## Your Environment

react-google-maps-api sample website

## How is it behave?

Console logs 'Autocomplete is not loaded yet!' initially, but does not search selections as the code example suggests.

Is this a bug?

**Comment by JustFly1984** [comment]
@uriklar @FredyC mention

**Comment by fbellagamba** [comment]
Facing the same issue. The workaround I found is to directly add the event listener to the "autocomplete" instance inside the onLoad event handler.

```javascript
  onLoad (autocomplete) {
    console.log('autocomplete: ', autocomplete)

    this.autocomplete = autocomplete
    this.autocomplete.addListener('place_changed', onPlaceChanged)
  }

  onPlaceChanged () {
    if (this.autocomplete !== null) {
      console.log(this.autocomplete.getPlace())
    } else {
      console.log('Autocomplete is not loaded yet!')
    }
  }
```

Hope it helps!
