### ISSUE TITLE
Can't set zoom or initial center on GoogleMap component.

### ISSUE THREAD

**Issue by shammahk** [JustFly1984/react-google-maps-api#1983]
I updated the package and applied the method in the example on the NPM doc, setting center and zoom props but they don't seem to have any effect.

```javascript
   <GoogleMap
        mapContainerStyle={containerStyle}
        center={{
          lat: 46.13033,
          lng: -90.346771,
        }}
        zoom={1}
        options={{
          styles: isDark ? darkMapStyle : lightMapStyle,
        }}
        onLoad={onLoad}
        onUnmount={onUnmount}
    ></GoogleMap>
```
## Your Environment

os: windows

node --version

react version
16.13.1

webpack version

@babel version

@react-google-maps/api version
1.13.0

## How is it behave?
initial center is in another coordinate, and zoom is not the zoom I set.
## How should it behave correctly?
Map should have the center position entered, and the zoom.

**Comment by candrescastel** [comment]
Check your onLoad function

**Comment by joobacca** [comment]
As @candrescastel  mentioned already, you should check your onLoad function! I had the same issue because I copy pasted the whole Maps component at first.

`  const onLoad = React.useCallback(function callback(map) {
    const bounds = new window.google.maps.LatLngBounds();
    map.fitBounds(bounds); // Omit this line
    setMap(map)
  }, [])`

**Comment by CamTheWebGuy** [comment]
> As @candrescastel mentioned already, you should check your onLoad function! I had the same issue because I copy pasted the whole Maps component at first.
> 
> ```js
> const onLoad = React.useCallback(function callback(map) {
>   const bounds = new window.google.maps.LatLngBounds();
>   map.fitBounds(bounds); // Omit this line
>   setMap(map)
> }, [])
> ```

This is the answer OP. I had the same issue, this is how I fixed it.

**Comment by rafagomes** [comment]
> > As @candrescastel mentioned already, you should check your onLoad function! I had the same issue because I copy pasted the whole Maps component at first.
> > ```js
> > const onLoad = React.useCallback(function callback(map) {
> >   const bounds = new window.google.maps.LatLngBounds(); //omit this too
> >   map.fitBounds(bounds); // Omit this line
> >   setMap(map)
> > }, [])
> > ```
> 
> This is the answer OP. I had the same issue, this is how I fixed it. Thank you @joobacca

You can actually ommit both lines. :)

**Comment by RTIMichael** [comment]
You guys should probably update your docs because this is the default onLoad method that you specify when getting started.  This causes a lot of confusion when the map initially loads with an arbitrary center instead of the one specified in our code.

**Comment by hashkazi00** [comment]
We fixed the issue by removing the `onLoad` prop and the method was being passed altogether, 

things are just working as expected,

is that a good thing to remove it?
