### ISSUE TITLE
allow to style autocomplete

### ISSUE THREAD

**Issue by eh-am** [JustFly1984/react-google-maps-api#201]
Right now it's not possible to style the[ wrapping div.](https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/components/places/Autocomplete.tsx#L136) I believe just supporting style/className ought to be enough.

@react-google-maps/api@1.5.4

**Comment by JustFly1984** [comment]
@eh-am if you provide PR, I can publish it asap

**Comment by rvilgalys** [comment]
Tried to adjust this, but wasn't able to get a build on my clone.

Only change needed is to pass `{...this.props}` on the wrapping div to give the ability to style or add id / className, etc.
