### ISSUE TITLE
How to modify opacity of KML layer programmatically ?

### ISSUE THREAD

**Issue by fromsujay** [JustFly1984/react-google-maps-api#207]
Hello, 

I am a beginner in programming, so please be patient with me. 
os: mac
node --version : v10.10.0
react version : 16.6.1
webpack version : 4.29.6 (as dependency in react-scripts)
@babel version : 1.11.0 (babel-plugin-import as dependency)
@react-google-maps/api version: 1.6.0 

# How does it behave? No access to opacity property of KmlLayer

## How should it behave correctly? I would like to modify the opacity property of KmlLayer. How can I achieve this ? It doesn't work if I apply css style using and id or classname. 

Can you please help me ?

**Comment by JustFly1984** [comment]
please provide minimal reproduction on codesandbox.com

**Comment by fromsujay** [comment]
Hello, 

Please find a minimal reproduction of the case at hand. I would like to apply an opacity of 40% to this KML layer in order to see information on the map in the background. 

https://codesandbox.io/embed/jolly-wilson-slhed

**Comment by JustFly1984** [comment]
Sorry, but klmlayer is part of google-map-api, and there is no possibility to style is. I would recommend to try to use png with transparency as url

**Comment by uriklar** [comment]
I had the same requirement once and the solution was to convert kml to polygons and map them. The kml layer is not very flexible...

**Comment by fromsujay** [comment]
I have 731 images to position as a part of the KML layer. It was going to be fastidious to convert them all and apply opacity on each one of them. So I posted the question on Stackoverflow and a developer found a very clever workaround to this problem. You can see the implementation in my codesandbox : https://codesandbox.io/embed/jolly-wilson-slhed

It is possible to change the opacity in the KML but apparently it doesn't work if it's part of a GroundOverlay (particularly in Google Maps). It may work in Google Earth. I tried that but it doesn't work in Google Maps due to partial implementation as confirmed in the 2nd stackoverflow anwser to my question : https://stackoverflow.com/questions/57589514/how-to-change-opacity-of-image-imported-as-icon-in-kml-document/57593176?noredirect=1#comment101663380_57593176
