### ISSUE TITLE
Support for Map markers with labels customization

### ISSUE THREAD

**Issue by FatehAK** [JustFly1984/react-google-maps-api#211]
# Please provide an explanation
Just wanted to ask whether this package supports marker label customization such as setting a background for the label, colour and so on? If so how to add it or is there any alternative?

## Your Environment

os: mac/linux/windows/android/ios
linux
node --version
10.x
react version
16.9.x
webpack version

@babel version

@react-google-maps/api version
1.6.0

**Comment by JustFly1984** [comment]
Please ask questions in our spectrum community
