### ISSUE TITLE
How to capture the center of the map using onCenterChanged method ?

### ISSUE THREAD

**Issue by fromsujay** [JustFly1984/react-google-maps-api#212]
Hello, 

I am trying to capture the center of the map using the onCenterChanged method in order to keep the map centered around the new centre after a set state has occurred and avoid relapsing to the initial centre. 

os: macOS Sierra version 10.12.6  
node --version v10.10.0
react version 16.6.1
webpack version 4.29.6
@babel version 7.0.0 (code-frame)
@react-google-maps/api version 1.6.0

Impossible to capture the map center because I am not being able to apply the map.getCenter() method of Google Maps Javascript API. I am using the onCenterChanged method and but I am not being able to access the map object. 

Your documentation mentions that I must use the onLoad method but I need to capture the latest know center which is not possible with the onLoad method. I can't use the onClick method to capture the coordinates because the KML layer covers the whole screen/map. 

Please find a Codesandbox to demonstrate the problem : https://codesandbox.io/embed/great-http-kmk91

Thanks in advance for your guidance.

**Comment by JustFly1984** [comment]
@fromsujay I have forked your codesandbox and solve your puzzle, enjoy
https://codesandbox.io/s/epic-fermat-kr12d

**Comment by fromsujay** [comment]
Brilliant solution Alexey. Thank you very much. Have a good day.
