### ISSUE TITLE
Issue with diplaying map

### ISSUE THREAD

**Issue by CentroneF** [JustFly1984/react-google-maps-api#2129]
I used the Functional component from the documentation, I added my api key but the map is gray and I cannot make it work.
## Your Environment

os: mac
react version: 17.0.1
@react-google-maps/api version: latest

<img width="1433" alt="Screenshot 2021-02-18 at 14 13 19" src="https://user-images.githubusercontent.com/11270732/108361990-76db3080-71f3-11eb-9a8c-4ed7c4eed6b1.png">

My code is: 
```
const MapView = () => {
  return (
    <LoadScript googleMapsApiKey={apikey}>
      <GoogleMap
        mapContainerStyle={containerStyle}
        center={center}
        zoom={10}
      >
        { /* Child components, such as markers, info windows, etc. */ }
        <></>
      </GoogleMap>
    </LoadScript>
  )
}

export default React.memo(MapView)
```
No Error in console. In the network tab, I can see the images downloaded correctly but nothing is showing on the map
Any suggestion?

**Comment by CentroneF** [comment]
Issue with overflow: hidden. Closing

**Comment by Oleksandr-Korniienko-IS** [comment]
@CentroneF Hi, how did you fix this issue?
