### ISSUE TITLE
fitBounds not working correctly

### ISSUE THREAD

**Issue by zackperdue** [JustFly1984/react-google-maps-api#214]
# Please provide an explanation
AirBnB-style map
I am displaying search results on a map based on location and using a radius. Starting with 2-3 markers on the map, I fit map to the marker bounds. The markers are children of the map component, but sometimes the maps `props.children` are inexplicably null when I try to fit to bounds.

## Your Environment

os: mac

node --version: v8.15.0

react version 16.8.4

webpack version

@babel version 7.4.4

@react-google-maps/api version 1.2.4

## How is it behave?
When I update my searching location, which has the same results as the previous search (markers should be the same) the markers aren't there according to react (props.children) is empty.

## How should it behave correctly?
Props.children shouldn't be empty & Markers should remain inside the bounds of the map and map should not pan to new location - the bounds of the map should still remain on the markers that were previously there (because they never changed when new search query submits)

**Comment by uriklar** [comment]
Please provide a minimal reproduction via codesandbox and we'll be able to help

**Comment by JustFly1984** [comment]
Please use eslint-plugin-react eslint-plugin-react-hooks and eslint-plugin-react-perf

Looks like you have unnecessary updates
