### ISSUE TITLE
Autocomplete suggestion container isn't cleaned up

### ISSUE THREAD

**Issue by fabyeah** [JustFly1984/react-google-maps-api#2141]
The `pac-container` HTML element, housing the suggestions from Autocomplete isn't removed upon unmount of Autocomplete. So in a SPA, navigating back and forth will create multiple `pac-container` elements.

My current workaround is to remove an existing `pac-container` in the Autocomplete `onLoad`. This means it's still around on other pages when navigating away from the Autocomplete page though. There should be an `onUnmount` method for Autocomplete, too. Or just build it into the code that the suggestions container is removed upon unmount of the Autocomplete.

**Comment by JustFly1984** [comment]
@fabyeah your PR is welcome, I will merge it and release new version.
