### ISSUE TITLE
onClick and onDblClick fired with the same event.

### ISSUE THREAD

**Issue by victorferreira** [JustFly1984/react-google-maps-api#215]
# Please provide an explanation

## Your Environment

os: mac

react version: ^16.8.6

@react-google-maps/api version: ^1.2.7

## How is it behave?

When I double click the map to zoom it also fires the onClick event, but want to have deferent behaviours for each of them.

## How should it behave correctly?

Ideally when using double click to zoom, it should only fire the onDblClick callback.

**Comment by JustFly1984** [comment]
@victorferreira  Please update to 1.6.0 and confirm an issue

**Comment by victorferreira** [comment]
I updated the version to 1.6.0 and the issue didn't go away.

**Comment by JustFly1984** [comment]
Can you please make a minimal reproduction in codesandbox?

**Comment by victorferreira** [comment]
Sure. Here's the sandbox: https://codesandbox.io/s/hungry-goldberg-shgqy

As you can see, both events are fired when you double click on the map.

**Comment by JustFly1984** [comment]
Your example is broken, I have fixed it here: https://codesandbox.io/s/clever-shirley-cm71s

I see everything as expected, onClick fires for first clich, and onDoubleClick fires on second click. This is normal behaviour.

**Comment by victorferreira** [comment]
Let me explain my use case and maybe you can help me. I want to add a maker on the map whenever a user clicks on the map, but I don't want to add the marker when the user uses the double click to zoom. Right now, a marker is been added on single click and double click. and that's annoying because it sets a marker when the user just wanted to zoom. How do I prevent this from happening?

**Comment by JustFly1984** [comment]
Well, double click has a delay between first and second click, you can set timeout from the first click little bit more than a delay between clicks, and cancel this timeout on second click if it set, so no marker is set on zoom.
