### ISSUE TITLE
Marker component not working correctly(Ipad/iOS)

### ISSUE THREAD

**Issue by AleksandrSerov** [JustFly1984/react-google-maps-api#216]
The label on the marker sometimes does not appear
**Demo**
https://youtu.be/3VYF_U8PNc0

Example code on codeSandBox
https://codesandbox.io/s/priceless-water-dhvxn

## Your Environment
os: ios 12+

node --version 7.0.0

react version 16.6.0

webpack version 4.2.20

@babel version 7.1.0

@react-google-maps/api version 1.6.0

## How is it behave?
Open map in Google Chrome/Safari on Ipad. Some labels does not appear
## How should it behave correctly?
All markers must display labels

**Comment by JustFly1984** [comment]
@FredyC @uriklar
