### ISSUE TITLE
InfoBox is not exported correctly

### ISSUE THREAD

**Issue by torresandres** [JustFly1984/react-google-maps-api#217]
# Please provide an explanation
I updated to version 1.6.0 because of the new InfoBox support but it throws an error when I try to import this component. I'm working on a webapp that requires several maps and this is the only one that is not working after updating the package. 
```
import { InfoBox } from '@react-google-maps/api';
```
This causes my webapp to crash with the following error message: 
```
Attempted import error: 'InfoBox' is not exported from '@react-google-maps/api'.
```
Also, looks like [InfoBox's example in the docs](https://react-google-maps-api-docs.netlify.com/#infobox) is broken too:
```
ReferenceError: InfoBox is not defined
```

## Your Environment
```
Node: 11.9.0
React: 16.8.6
@react-google-maps/api: 1.6.0
```
## How is it behave?
Webapp crash with the following error message: 
```
Attempted import error: 'InfoBox' is not exported from '@react-google-maps/api'.
```

## How should it behave correctly?
It should export `InfoBox` component correctly.

**Comment by JustFly1984** [comment]
InfoBox  will be available in next version 1.7.0
Currently docs are built from master. Please wait for new release this week.

**Comment by JustFly1984** [comment]
there is 1.7.5 released, please test

**Comment by JustFly1984** [comment]
it does work in latest version. closing an issue
