### ISSUE TITLE
Multiple Markers with InfoWindows: onClick adds focus ring to first marker in array instead of clicked marker

### ISSUE THREAD

**Issue by hexagoncircle** [JustFly1984/react-google-maps-api#2181]
In version [3.44.1](https://developers.google.com/maps/documentation/javascript/releases#3.44.1) of the maps javascript api released on Feb 18th:

* Non-optimized markers are now focusable and keyboard accessible.

This is a fantastic new feature for navigating multiple markers! However, since this updated, in my app I noticed that when a marker is clicked, it focuses on another marker in the array. You can see the issue presents itself in [this older CodeSandbox example](https://codesandbox.io/s/ir5ks) as well as my testing example below. From what I can tell, the first marker in the array gets focused every time an infowindow is opened.

### Testing

CodeSandbox: https://codesandbox.io/s/react-google-mapsapi-multiple-markers-infowindow-h6vlq

* Click a map marker. See it focus the first item in the `markers` array which is "Chicago, Illinois".
* While marker is focused, use keyboard arrow keys to navigate markers.
* Click space bar on new marker. See it focus on first marker as explained above.

### Notes

This issue doesn't seem to happen in [this vanilla JS implementation on Codepen](https://codepen.io/ahmadawais/pen/NQdWQx?editors=1010) pulled from the selected answer in [this StackOverflow question](https://stackoverflow.com/questions/3059044/google-maps-js-api-v3-simple-multiple-marker-example). You can try the testing steps here and see the difference. I wonder if this has something to do with the Map re-rendering when a marker is clicked. Perhaps there is a better way to handle marker infowindows?

I will add more to this ticket as I continue to troubleshoot this issue but wanted to get eyes on what I have so far to see if anyone else has ideas. Thank you in advance!

**Comment by justinkahrs** [comment]
I'm also seeing this issue.

**Comment by wzFLE** [comment]
Got the same issue. Seems ok with `version="3.43.8"` . Thanks a lot for the tip ! ! ! 

Opened a stackOverflow question here: https://stackoverflow.com/questions/66615177/black-square-appears-around-1st-marker-when-a-marker-onclick-triggers-a-state-up

Will reference this ticket in it. 

Happy to help to investigate but I don't know how I can have the react-google-map-api package installed locally. Still have to improve with npm/yarn. 

Test case I built (in case of): 

```
git clone https://gitlab.com/flelirzin/bug-marker-map.git
cd bug-marker-map
yarn install 
# please set google map api key in src/mapApiKey.js
yarn start
```
