### ISSUE TITLE
Marker component not showing icon?

### ISSUE THREAD

**Issue by treetruth** [JustFly1984/react-google-maps-api#223]
Hi, I'm migrating my code from `react-google-maps` package to this but when I wrap my `<Marker  position={ { lat: 37.772, lng: -122.214 } } />` component inside  `GoogleMap` component it's not showing marker icon?

**Comment by JustFly1984** [comment]
please create the minimal reproduction at codesandbox.com

**Comment by treetruth** [comment]
@JustFly1984 Here is the [codesandbox](https://codesandbox.io/s/1461-fhe3n) link.

**Comment by JustFly1984** [comment]
I have played a bit, and have no time today

my version, maybe it will help you to go from here
https://codesandbox.io/s/1461-gryy6

**Comment by treetruth** [comment]
@JustFly1984 I'm struggling with this problem, Could you help me in your free time?

**Comment by colemars** [comment]
https://codesandbox.io/s/1461-oq3pp

**Comment by treetruth** [comment]
@colemars Thank for the fix, but what are the things I'm missing?
