### ISSUE TITLE
Use custom React Component as Marker

### ISSUE THREAD

**Issue by MagdaxMai** [JustFly1984/react-google-maps-api#225]
Is there a way to use my own react component as marker or the ability to place a custom component anywhere on the map I want?

**Comment by uriklar** [comment]
Try OverlayView

**Comment by Aarbel** [comment]
@uriklar @MagdaxMai do you have an example with OverlayView ?

**Comment by Aarbel** [comment]
@uriklar how OverlayView can manage clusters ?
