### ISSUE TITLE
Map is gray and empty without setting zoom and center

### ISSUE THREAD

**Issue by seeseesky** [JustFly1984/react-google-maps-api#226]
There will not be any content in the map if zoom or center is not set. Maybe it is better to add these two params in the "Getting Started" instead of just showing ```{...other props}```.

**Comment by JustFly1984** [comment]
it is required props for google maps api. there is no possible to have default zoom and center.
Please PR your improvements to docs MD. Thank you for your contribution.

**Comment by rostgoat** [comment]
@seeseesky could you please provide your code.. I cannot get it to work when applying those args and all I see is the grey box

```
<div className="map">
        <LoadScript googleMapsApiKey={process.env.REACT_APP_GOOGLE_KEY}>
          <GoogleMap zoom={14} center={{ lat: 48, lng: -123 }} />
        </LoadScript>
      </div>
```

![Screenshot from 2019-09-22 23-22-43](https://user-images.githubusercontent.com/22672124/65405063-f6ab6400-dd8f-11e9-81fc-fbbb430aa64b.png)

**Comment by seeseesky** [comment]
> @seeseesky could you please provide your code.. I cannot get it to work when applying those args and all I see is the grey box
> 
> ```
> <div className="map">
>         <LoadScript googleMapsApiKey={process.env.REACT_APP_GOOGLE_KEY}>
>           <GoogleMap zoom={14} center={{ lat: 48, lng: -123 }} />
>         </LoadScript>
>       </div>
> ```
> 
> ![Screenshot from 2019-09-22 23-22-43](https://user-images.githubusercontent.com/22672124/65405063-f6ab6400-dd8f-11e9-81fc-fbbb430aa64b.png)

``` <GoogleMap
          id='example-map-2'
          mapContainerStyle={{ height: '100%', width: '100%' }}
          zoom={12}
          center={{ lat: 22.334949, lng: 114.235340 }}
        />
```
