### ISSUE TITLE
Property 'google' does not exist on type 'Window & typeof globalThis'

### ISSUE THREAD

**Issue by reinvanimschoot** [JustFly1984/react-google-maps-api#227]
# Please provide an explanation

## Your Environment

os: mac

react version: 16.9.0

webpack version: using create-react-app

@babel version: using create-react-app

@react-google-maps/api version: 1.7.5

## How is it behave?

I'm getting the error:

`Property 'google' does not exist on type 'Window & typeof globalThis'`

## How should it behave correctly?

So this is my component: 

```
import { useQuery } from '@apollo/react-hooks';
import Paper from '@material-ui/core/Paper';
import { makeStyles } from '@material-ui/core/styles';
import { GoogleMap, useLoadScript } from '@react-google-maps/api';
import * as React from 'react';

function AssetMapPage(props: Props) {
  const { isLoaded, loadError } = useLoadScript({ googleMapsApiKey: 'key' });

  const bounds = new window.google.maps.LatLngBounds();

  const { data, loading } = useQuery<assetQuery>(ASSET_QUERY);

  const classes = useStyles();

  if (loadError) {
    return <div>Map cannot be loaded right now, sorry.</div>;
  }

  return (
    <Paper className={classes.paper} elevation={4}>
      {isLoaded && (
        <GoogleMap
        // onLoad={map => {
        //   map.fitBounds(bounds);
        // }}
        />
      )}
    </Paper>
  );
}

const useStyles = makeStyles(theme => ({
  paper: {
    padding: theme.spacing(2),
    display: 'flex',
    overflow: 'auto',
    height: '90vh',
  },
}));
`;

export default AssetMapPage;
```

And I'm getting the error above:

`Property 'google' does not exist on type 'Window & typeof globalThis'`

I have no idea what I'm doing wrong, if someone could help I would be very thankful!

**Comment by reinvanimschoot** [comment]
When I try to do it as the docs suggest, I get the same error:

```
import { useQuery } from '@apollo/react-hooks';
import Paper from '@material-ui/core/Paper';
import { makeStyles } from '@material-ui/core/styles';
import { GoogleMap, useLoadScript, LoadScriptNext } from '@react-google-maps/api';
import * as React from 'react';

type Props = {
  latitude: string;
  longitude: string;
  setLatitude: (lat: string) => void;
  setLongitude: (lat: string) => void;
};

function AssetMapPage(props: Props) {
  const { data, loading } = useQuery<assetQuery>(ASSET_QUERY);

  const { isLoaded, loadError } = useLoadScript({ googleMapsApiKey: 'key' });

  const renderMap = () => {
    const onLoad = React.useCallback(function onLoad(mapInstance) {
      const bounds = new window.google.maps.LatLngBounds();
    }, []);

    return <GoogleMap onLoad={onLoad} />;
  };

  const classes = useStyles();

  if (loadError) {
    return <div>Map cannot be loaded right now, sorry.</div>;
  }

  return (
    <Paper className={classes.paper} elevation={4}>
      {isLoaded && renderMap()}
    </Paper>
  );
}

const useStyles = makeStyles(theme => ({
  paper: {
    padding: theme.spacing(2),
    display: 'flex',
    overflow: 'auto',
    height: '90vh',
  },
}));
`;

export default AssetMapPage;
```

**Comment by reinvanimschoot** [comment]
And when I try to circumvent the error by doing `new (window as any).google.maps.LatLngBounds();` I get back the following error:

`React Hook "React.useCallback" is called in function "renderMap" which is neither a React function component or a custom React Hook`

So I'm not sure if the docs are actually correct in this case

**Comment by FredyC** [comment]
You hack with "any" is good enough. The second error is because you are really breaking rules of hooks, you cannot have useCallback inside the renderMap 😆

**Comment by JustFly1984** [comment]
you can't use google object in component, before
```
const { isLoaded, loadError } = useLoadScript({ googleMapsApiKey: 'key' }); 
```
done it's job. 

I would recommend a wrapper component, which calls useLoadScript, and renders AssetMapPage conditionally, depends on` isLoaded === true`

**Comment by JustFly1984** [comment]
@reinvanimschoot  if you provide a basic reproduction in codesandbox, we can help you to setup proper flow

**Comment by jon64digital** [comment]
> You hack with "any" is good enough. The second error is because you are really breaking rules of hooks, you cannot have useCallback inside the renderMap 😆

Which is strange because that's how it's done in the official documentation....

https://react-google-maps-api-docs.netlify.com/

I have tried to use the example code but I don't think it's been tested at all because it's just error after error. The documentation is extensive but the getting started section provides pretty much zero explanation of how to use the basic components.

**Comment by JustFly1984** [comment]
We have react-google-maps-gatsby-example with all possible examples

**Comment by vitorlimadev** [comment]
The official documentation really tells us to do it. It would be very helpful to update it.

![image](https://user-images.githubusercontent.com/30941353/77069204-bcc9bc00-69c6-11ea-9837-e8e1e0415eed.png)

**Comment by JustFly1984** [comment]
Sorry, this part of documentation is incorrect. If someone wants to update it, your PR is welcome.

renderMap should be a component itself, exported with `export default React.memo(RenderMap)` from another file to make it pure.

**Comment by vitorlimadev** [comment]
Thank you, I'll try to make it work, and if I do, I'll happily make a PR for updating the docs.

**Comment by albertdugba** [comment]
I have the same issue

**Comment by bongkumtim** [comment]
so what is the solution ???
