### ISSUE TITLE
How to fitBounds inside of onLoad??

### ISSUE THREAD

**Issue by zning** [JustFly1984/react-google-maps-api#229]
Firstly, thanks for rewriting the old unmaintained library, we really really appreciate this. 

I understand that we could use map instance inside of onLoad callback, but I have some difficulties to make it works. So basically, I want the map to fitbounds some markers on the map.
What I did: 
`onLoad={map => {
            const bounds = new window.google.maps.LatLngBounds();
            dataObjectArray.forEach(
              (dataObject) => {
                dataObject.forEach((data)=>{
                  bounds.extend(new window.google.maps.LatLng(
                    data.Latitude,
                    data.Longitude
                  ));
                });
              }
            );
            map.fitBounds(bounds);
          }}`
But this does not working somehow. The dataObjectArray is an array of objects, in which each object contains the lat and lng as part of many data. I want to use the google.maps.LatLng()method to extend the bounds. (or if there's better way to not use it)
Could someone please help me to make this works , thanks a lot!

**Comment by zning** [comment]
figure it out myself. Case closed.

**Comment by michalica** [comment]
How did you do that @zning ?

**Comment by zning** [comment]
> How did you do that @zning ?

See the example here:
https://codesandbox.io/s/googlemap-popup-tesing-xuhp4
