### ISSUE TITLE
how to click marker show infowindow?

### ISSUE THREAD

**Issue by Eviwang** [JustFly1984/react-google-maps-api#230]
# Please provide an explanation

how to click marker show infowindow?
like this:
https://developers.google.com/maps/documentation/javascript/infowindows#open
## Your Environment
os: mac/linux/windows/android/ios
windows
node --version
latest
react version
v10.15.3
webpack version
latest
@babel version
latest
@react-google-maps/api version
latest

**Comment by uriklar** [comment]
https://spectrum.chat/react-google-maps/general/how-to-use-infowindow~d711efb9-62c2-4b87-a725-a0fcfc4c205b

**Comment by glinda93** [comment]
## TL DR;
https://codesandbox.io/s/react-google-maps-api-ir5ks
