### ISSUE TITLE
Marker change icon size

### ISSUE THREAD

**Issue by iKeeko** [JustFly1984/react-google-maps-api#232]
Hi, I'm trying to change the size of the marker icon with the size property inside the icon prop of the Marker component.

I expected the outcome would be just the same as the previous version react-google-maps

scaledSize: new window.google.maps.Size(25, 25)

error:
TypeError: Cannot read property 'maps' of undefined

obviously that error is clear enough but I have no idea where to change this icon size. it's on the documentation or I just can't find it.

I tried to delay rendering the DOM but still getting this error

**Comment by jessepinho** [comment]
@iKeeko where are you passing `scaledSize`? 

I'm dealing with this issue too, and not seeing anywhere in the docs that I can change the icon size.

**Comment by jessepinho** [comment]
@iKeeko ah, I figured it out. You need to make a `google.maps.Icon` object and pass it to the marker's `icon` property. As you mentioned, `scaledSize` requires a `google.maps.Size` object, but `window.google` may not exist at the time you wish to create the icon object.

My solution to this was to use a state hook to keep track of when the Google Maps API had loaded:

```
  const [isGoogleMapsAPILoaded, setIsGoogleMapsAPILoaded] = useState(false)
```

Then, in the `LoadScript` component's `onLoad`, set it to `true`:

```
    <LoadScript
      googleMapsApiKey={process.env.GATSBY_GOOGLE_MAPS_API_KEY}
      onLoad={() => {
        setIsGoogleMapsAPILoaded(true)
      }}
    >
```

Lastly, only render the markers once the Google Maps API has loaded:
```
        {isGoogleMapsAPILoaded &&
            <Marker
              icon={{
                url: markerIcon,
                scaledSize: new google.maps.Size(26, 40),
              }}
              />}
```

Make sense?

**Comment by zning** [comment]
import { GoogleMap,LoadScript, Marker, } from '@react-google-maps/api'
{data&&data.map(
            item => {
              return <Marker
               position={{
                 lat: item.lat,
                 lng: item.lng,
               }}
               icon={{
                 url:terminal,
                 scaledSize: new window.google.maps.Size(40,40),
                /** or scaledSize: {height:40, width:40}, **/
               }}
               zIndex={99}

              />
            }
          )}
1. Please do not forgot to import the Marker because the docs sometimes just ignore that.
2. Make sure the data is true and then render the Marker(keep lat,lng valid).
3. You could use new window.google.maps.Size(40,40) or {height:40, width:40} after the scaledSize inside of icon. Both works for me.

**Comment by zning** [comment]
> Hi, I'm trying to change the size of the marker icon with the size property inside the icon prop of the Marker component.
> 
> I expected the outcome would be just the same as the previous version react-google-maps
> 
> scaledSize: new window.google.maps.Size(25, 25)
> 
> error:
> TypeError: Cannot read property 'maps' of undefined
> 
> obviously that error is clear enough but I have no idea where to change this icon size. it's on the documentation or I just can't find it.
> 
> I tried to delay rendering the DOM but still getting this error

import { GoogleMap,LoadScript, Marker, } from '@react-google-maps/api'
{data&&data.map(
            item => {
              return <Marker
               position={{
                 lat: item.lat,
                 lng: item.lng,
               }}
               icon={{
                 url:terminal,
                 scaledSize: new window.google.maps.Size(40,40),
                /** or scaledSize: {height:40, width:40}, **/
               }}
               zIndex={99}

              />
            }
          )}
1. Please do not forgot to import the Marker because the docs sometimes just ignore that.
2. Make sure the data is true and then render the Marker(keep lat,lng valid).
3. You could use new window.google.maps.Size(40,40) or {height:40, width:40} after the scaledSize inside of icon. Both works for me.

**Comment by iKeeko** [comment]
> @iKeeko ah, I figured it out. As you mentioned, the `<Marker />` component's `icon` prop accepts an object with a `scaledSize` property. `scaledSize` requires a `window.google.maps.Size` object, but `window.google` may not exist at the time you wish to create the icon object.
> 
> My solution to this was to use a state hook to keep track of when the Google Maps API had loaded:
> 
> ```
>   const [isGoogleMapsAPILoaded, setIsGoogleMapsAPILoaded] = useState(false)
> ```
> 
> Then, in the `LoadScript` component's `onLoad`, set it to `true`:
> 
> ```
>     <LoadScript
>       googleMapsApiKey={process.env.GATSBY_GOOGLE_MAPS_API_KEY}
>       onLoad={() => {
>         setIsGoogleMapsAPILoaded(true)
>       }}
>     >
> ```
> 
> Lastly, only render the markers once the Google Maps API has loaded:
> 
> ```
>         {isGoogleMapsAPILoaded &&
>             <Marker
>               icon={{
>                 url: markerIcon,
>                 scaledSize: new google.maps.Size(26, 40),
>               }}
>               />}
> ```
> 
> Make sense?

Thank you. That did the trick. The old version react-google-maps do not require to do this that's why I was confused
