### ISSUE TITLE
Autocomplete, select first option on enter

### ISSUE THREAD

**Issue by ljrodriguez1** [JustFly1984/react-google-maps-api#2331]
When i am searching a place on autocomplete i would like that when i press enter if no suggestion is focused the first suggestion is automaticaly focused so i get the cords of that place.

I have tried firing a keyboard event on onPlaceChanged, but when i press enter the autocomplete window is closed so i cant with the key down press select automatically the first option.

Is there a work around for this, i really need this on my project.

**Comment by fabyeah** [comment]
I do this, but it's not very straightforward. I get the complete text of the first suggestion from the HTML and then run a `findPlaceFromQuery` on it.

**Comment by ljrodriguez1** [comment]
Thanks @fabyeah, could you provide me a code snippet of how are you doing it? it would really help me because with your explanation i am still a little lost

**Comment by ljrodriguez1** [comment]
@madisvain i have not find the time to solve this issue, when i do i will post the answer. if anyone does this before please share the answer because this is a feature really needed

**Comment by fabyeah** [comment]
My current solution:

```javascript
  const autocompleteOnPlaceChanged = () => {
    const res = autocompleteRef.getPlace();

    // If user pressed enter instead of selecting a suggestion,
    // only { name: <user text input> } is returned.
    // Automatically use the first suggestion.
    if (res.place_id === undefined) {
      const pacItemQuery = document.getElementsByClassName('pac-item-query');
      const autocompleteInput = document.getElementsByClassName('pac-target-input')[0] as HTMLInputElement;
      // The user pressed return in empty autocomplete: Search anywhere
      if (autocompleteInput.value.trim() === '') {
        handleSearchAnywhereBtnClick();
      // Get first suggestion and search for that
      } else if (pacItemQuery.length) {
        const next = pacItemQuery[0].nextSibling;
        let inputText = pacItemQuery[0].textContent;
        if (next.textContent !== '') {
          inputText += `, ${next.textContent}`;
        }
        autocompleteInput.value = inputText;
        autocompleteInput.blur();
        const attribution = document.createElement('div');
        const x = new window.google.maps.places.PlacesService(attribution);
        x.findPlaceFromQuery({
          query: inputText,
          fields: ['name', 'place_id', 'geometry', 'types'],
        }, (r) => {
          if (r.length) {
            getPlacesForQuery(r[0]);
          }
        });
      }
    } else {
      const autocompleteInput = document.getElementsByClassName('pac-target-input')[0] as HTMLInputElement;
      autocompleteInput.blur();
      getPlacesForQuery(res);
    }
  };
```

**Comment by madisvain** [comment]
@fabyeah thank you I'll take a look. I managed to find a solution also so I'll share mine as well.
