### ISSUE TITLE
useLoadScript is blocking main thread

### ISSUE THREAD

**Issue by pzpsofficial** [JustFly1984/react-google-maps-api#2355]
Hi. 
I am using @react-google-maps/api and I have an issue. I am using useLoadScript, but it results in very low lighthouse scores (what is interesting - only on mobile). Is there any way how to load the maps in the background? Just as I would do with ```defer``` in a vanilla js app? 

```
const { isLoaded } = useLoadScript({
    googleMapsApiKey: 'key',
  });

  if (!isLoaded) return "Loading maps..."

  return (
    // map
  )
```

^Here is how I am doing it at the moment

**Comment by JustFly1984** [comment]
@pzpsofficial You should not use maps loading without user interaction - mouse click on button will go for your case.
Google maps API script is heavy and codebase is a huge mess. It was made in times then there was no lighthouse or even single page applications.
