### ISSUE TITLE
Map position re-centres when re-rendering

### ISSUE THREAD

**Issue by maxfi** [JustFly1984/react-google-maps-api#240]
This is possibly expected behaviour and if so can be avoided by wrapping the map component using `React.memo`. I found it counter intuitive though that only the centreing of the map is reset on a re-render but the rest of the map's state appears to remain the same.

## Your Environment

CodeSandbox `create-react-app` environment

react version: 16.8.6

@react-google-maps/api version: 1.7.7

## How is it behave?

Clicking on a `Marker` that is a child of `MarkerClusterer`, and changes parent state, causes the map to reposition to centre. 

## How should it behave correctly?

The map should not reposition to centre.

## Basic implementation of incorrect behavior in codesandbox.com

https://codesandbox.io/s/react-google-mapsapi-state-issue-neel6

**Comment by JustFly1984** [comment]
@maxfi 
please don't pass arrays and objects as props to components, it causes them to re-render

https://codesandbox.io/s/react-google-mapsapi-state-issue-zg7hp

**Comment by maxfi** [comment]
Oh. My bad! 😳 I wasn't aware of this. Thanks for your help @JustFly1984 and for the great package!

For anyone interested you can read more about this here in the section _2. Avoid inline objects_:

https://itnext.io/6-tips-for-better-react-performance-4329d12c126b

**Comment by MokhammadDaniyal** [comment]
@JustFly1984 
Hello, I am facing the same problem. 
I am have lat and lng in state. I have to use state as I have search bar through which user can search for a city and recenter map to it, so I am stuck with using state for lat and lng.  What would you suggest to do?

**Comment by JustFly1984** [comment]
@MokhammadDaniyal please provide minimal reproduction in codesandbox.io
