### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by banibanc** [JustFly1984/react-google-maps-api#241]
# Please provide an explanation

The map is not shown and when I'm inspecting the source, the iframe's body is empty.
I've got no errors in console whatsoever.

## Your Environment

os: windows

node --10.16.3

react version 16.10.2

webpack version 4.41.10

@babel version

@react-google-maps/api version 1.7.7

## How is it behave?
Map not displayed without any error

## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/nice-sky-ur0w0

Quite sure I made a mistake but can't find out where :/

**Comment by bitttttten** [comment]
I think I am in the same position?

This is my tree:

![Screenshot 2019-10-15 at 16 45 34](https://user-images.githubusercontent.com/19930241/66842269-3d454600-ef6b-11e9-86b1-fa0863bd8329.png)

**Comment by CasanaT** [comment]
I think you need to add styles to the Google map component. My map was white and not showing and added height and width to it and then it displayed.

` <GoogleMap
                  mapContainerStyle={{ height: '100%', width: '100%' }}
                  id="example-map"
                />`

**Comment by banibanc** [comment]
Thanks for your answer !
