### ISSUE TITLE
infobox with cluster

### ISSUE THREAD

**Issue by samuelpucat** [JustFly1984/react-google-maps-api#245]
Hey,

I want to create custom infowindow (different styling than google IW) with support of clustering. I created InfoBox with custom style, put it into Marker and MarkerClusterer. Works good, until I dynamically add new custom infowindow, then it won't cluster itself. When I use classic InfoWindow, it works fine, but I don't want to hack styles of google components.

after adding new marker:
![image](https://user-images.githubusercontent.com/18383653/67110543-489aaa80-f1d3-11e9-8210-6e4d715496a1.png)

desired effect: 
![image](https://user-images.githubusercontent.com/18383653/67110568-5b14e400-f1d3-11e9-86c9-450b254d59a4.png)

thanks in advance

os: windows
node --version 10.16.0
react version 16.8.6
@react-google-maps/api version 1.7.7

repro: 
https://codesandbox.io/s/jolly-franklin-tec5h

**Comment by samuelpucat** [comment]
I figured, I could call repaint() on clusterer in componentDidMount() after array changes but it only works in setTimeout()?

**Comment by dogofpavlov** [comment]
I'm also having an issue that is very similar/related issue.

If a drag that Marker that is currently not clustered, into an area that has a cluster... the cluster doesnt seem to update. manually calling the repaint does seem to have fixed it

**Comment by rico-et22** [comment]
How were you able to call the repaint function? I'm having a similar issue and can't find a way to do it, even through refs.
