### ISSUE TITLE
Maps API not working on localhost

### ISSUE THREAD

**Issue by FatehAK** [JustFly1984/react-google-maps-api#246]
# Explanation
I am trying to load the Maps API on localhost (specifically the Places API for the StandaloneSearchBox component) but it fails to load and gives me this error.

`This API key is not authorized to use this service or API. Places API error: ApiTargetBlockedMapError`

I've searched online and have added the following referrers in API restrictions too. 
```
localhost
localhost:3000/*
http://localhost/*
http://localhost:3000/*
```
I even tried with a totally unrestricted API key but still I get the same error in localhost. It works in production though. How do I test the Places API in development with localhost?

## Environment
os: linux
node - 10.16.3
react - 16.10.2
@react-google-maps/api version - 1.7.7

**Comment by FatehAK** [comment]
Works now just had to restart the server sigh..

**Comment by vivekkadoli** [comment]
Use these steps if still not works...
1. Go to this address: https://console.developers.google.com/apis
2. Create new project and Create Credentials (API key)
3. Click on "Library"
4. Click on any API that you want
5. Click on "Enable"
6. Click on "Credentials" > "Edit Key"
7. Under "Application restrictions", select "HTTP referrers (web sites)"
8. Under "Website restrictions", Click on "ADD AN ITEM"
9. Type your website address (or "localhost", "127.0.0.1", "localhost:port" etc for local tests) in the text field and press ENTER to add it to the list
10. SAVE and Use your key in your project
