### ISSUE TITLE
How to use Geocode API with this library?

### ISSUE THREAD

**Issue by FatehAK** [JustFly1984/react-google-maps-api#247]
# Please provide an explanation
Just wanted to ask whether this library supports the Geocoder API?

**Comment by JustFly1984** [comment]
Please ask your question in https://spectrum.chat/react-google-maps

**Comment by makenova** [comment]
@FatehAK hi from the future! I saw that this was also asked in spectrum and did not get an answer.
Adding my current solution here for posterity.

I ended adding an `initMap` function that runs after googleMaps is loaded on the page.
The `initMap` function checks if `window.google.maps` is defined and sets the geocoder to a state variable.
Here is a minimal example. You will need more checks to make sure everything is defined and that the init function runs only once.

```
// load googlemaps
const { isLoaded: isGoogleMapsLoaded } = useLoadScript({ googleMapsApiKey: 'googleApiKey' });

// setup state variable
const [googleMapsGeocoder, setGoogleMapsGeocoder] = React.useState({});

// create init func
const initMaps = React.useCallback(() => {
  const gmObj = window?.google?.maps;

  if (!gmObj) return;

  const gmGeocoder = new gmObject.Geocoder();
  setGoogleMapsGeocoder(gmGeocoder);
}, []);

// call init func when google maps is ready.
React.useEffect(() => {
  if (isGoogleMapsLoaded) {
    initMaps();
  }
}, [initMaps, isGoogleMapsLoaded]);
```

After all that the geocoder will be available as a state variable and you can get coordinates for and address with `googleMapsGeocoder.geocode`.

I hope this helps anyone else that stumbles across this. If you have a better way to do this, please share!
