### ISSUE TITLE
Map in New Popup Window Bug (Drag event was decoupled between new window and the existing window )

### ISSUE THREAD

**Issue by zning** [JustFly1984/react-google-maps-api#248]
Could someone help with this issue please:
I'm using the react portal to pop up a new window(using Window.open()) to show google maps. Most events fires normally but not drag. When I trying to drag around the map inside the popup window, only the onDragStart fired, the onDrag and onDragEnd events were stoped until I click back to the main app window, these two event resumed... Weird behavior. Could some code god help please?

**Comment by JustFly1984** [comment]
@zning  Do you render <ScriptLoader /> in Window.open() or outside?

**Comment by zning** [comment]
> @zning Can you please provide minimal example in codesandbox ?

I try to create an example. but  it seems that  the codesandbox won't allow me due to some cross origin issue.

**Comment by zning** [comment]
> @zning Can you please provide minimal example in codesandbox ?

Codesandbox not works due to the cross origin issue. So I created a testing repository here:
https://github.com/zning/map-testing
I'm also testing another package called '@googlemap-react/core'.  
Please switch to the Map1 inside of the App.js to see the issue.
Thanks a lot for your help ~

**Comment by JustFly1984** [comment]
then you render separate tab with react portal, you got completely new javascript context. You need to render `<LoadScript />` inside the Portal rendered component, so google-maps-api rendered correctly. It will work independent from main tab, but you still can use props and context passed from main tab.

**Comment by zning** [comment]
> @zning
> Then you render separate tab with react portal, you got completely new javascript context. You need to render `<LoadScript />` inside the Portal rendered component, so google-maps-api rendered correctly. It will work independent from main tab, but you still can use props and context passed from main tab.

In the App.js, 

<Window>
  <Map1 />
</Window>

(The window will be the new popup window. )The <LoadScript > has already been placed inside of <Map1 />. Does that means the <Loadscript/> already been rendered inside the portal?

**Comment by JustFly1984** [comment]
look at the `<head>` of your Portal window tab. if there is a `<script />` with google-maps-api, it is rendered correctly. I would advise to do not use Portal, but just use separate route and open it with `<a href target='_blank' />` as simplest

**Comment by zning** [comment]
> look at the `<head>` of your Portal window tab. if there is a `<script />` with google-maps-api, it is rendered correctly. I would advise to do not use Portal, but just use separate route and open it with `<a href target='_blank' />` as simplest

Unfortunately, I have to use window.open() with portal because base on the app design, almost any part of the app section could be pop out. open it with a new tab wound not 'work'. I tried to add the script tag with google map api to the popup window. It still not working. Almost seems that the map inside of the pop up window would not recognize it and still using the main window's script.

**Comment by svmx-abhaydesai** [comment]
@zning where you able to solve this?

**Comment by zning** [comment]
> @zning where you able to solve this?

Not only I didn't, but couldn't figure out what cause this. The real cause of this may help solve the problem.

**Comment by anuruddhar** [comment]
I'm doing similar using Angular. I also faced the same issue zning was facing. I also couldn't figure out yet.
