### ISSUE TITLE
Polyline is drawing boxes around the line

### ISSUE THREAD

**Issue by greendinosaur** [JustFly1984/react-google-maps-api#2485]
I am having problems using `Polyline` to draw a polyline on a map. It is drawing some kind of boundary box around my line. I've tried replacing my code with the Polyline example and I have the same issue. 

I do not have this problem when plotting Markers. It seems to be Polyline causing the problem.

## Your Environment

Mac os 11.2.3

node v15.6.0

react 17.0.1

@react-google-maps/api version 2.1.1

## How is it behave?
Here is a screenshot of the map.
![Screenshot 2021-05-03 at 12 48 06](https://user-images.githubusercontent.com/10242083/116925308-e024ea00-ac0d-11eb-9225-5f5b47f8c5e1.png)

## How should it behave correctly?
The black boxes should not be shown

Here is the code I am using. The only difference to the code in the docs is I am using hooks.

```
import React from "react";

import {
  GoogleMap,
  useJsApiLoader,
  Polyline,
} from "@react-google-maps/api";

function MyMap(props) {

  const { isLoaded } = useJsApiLoader({
    id: "google-map-script",
    googleMapsApiKey: process.env.REACT_APP_GOOGLE_MAP_API,
  });

  const [map, setMap] = React.useState(null);

  const onLoad = React.useCallback(function callback(newMap) {
    setMap(newMap);
  }, []);

  const onUnmount = React.useCallback(function callback(newMap) {
    setMap(null);
  }, []);

const mapContainerStyle = {
    height: "400px",
    width: "800px",
  };

  const center = {
    lat: 0,
    lng: -180,
  };

  const path = [
    { lat: 37.772, lng: -122.214 },
    { lat: 21.291, lng: -157.821 },
    { lat: -18.142, lng: 178.431 },
    { lat: -27.467, lng: 153.027 },
  ];

  const options = {
    strokeColor: "#FF0000",
    strokeOpacity: 0.8,
    strokeWeight: 2,
    fillColor: "#FF0000",
    fillOpacity: 0.35,
    clickable: false,
    draggable: false,
    editable: false,
    visible: true,
    radius: 30000,
    zIndex: 1,
  };

  return isLoaded ? (
    <GoogleMap
      id="surveys"
      mapContainerStyle={mapContainerStyle}
      zoom={2}
      center={center}
      onLoad={onLoad}
      onUnmount={onUnmount}
    >
      <Polyline path={path} options={options} />
    </GoogleMap>
  ) : (
    <p>not loaded</p>
  );
}
```

**Comment by JustFly1984** [comment]
Please do not post code, instead post the link for minimal reproduction on codesandbox.io

**Comment by greendinosaur** [comment]
I've found the issue. Inside some css imported into my App.js file I had some code for the Canvas element. This was causing the black lines.  I had: 

`
canvas {
  border: 1px solid #000000;
}`

I removed this and the black line went away. I guess the google maps API makes use of the canvas element when drawing a polyline but not when it is just drawing markers.
