### ISSUE TITLE
Indicate required fields in documentation and via console

### ISSUE THREAD

**Issue by nspaeth** [JustFly1984/react-google-maps-api#250]
# Please provide an explanation
The `GoogleMap` component requires both `zoom` and `center`, but this is isn't indicated in the documentation or via any error message. At least two issues have been created because these things are missing: #241 and #185. If it isn't already, these should also be required via typescript types.

I imagine there are other places that this is the case.

**Comment by JustFly1984** [comment]
Both props required in typescript, and in docs both required
