### ISSUE TITLE
How to get the current zoom level?

### ISSUE THREAD

**Issue by keita-makino** [JustFly1984/react-google-maps-api#251]
# Please provide an explanation

I want to get the current zoom level but not sure how to achieve that.

## Your Environment

os: windows

node 10.16.3

react 16.10.2

webpack 4.41.0

@babel 7.6.2

@react-google-maps/api 1.7.7

## Code

```typescript
// imports and consts
const Map: React.FC = (props: Props) => {
  // brahbrah

  const mapRef = useRef(null);
  const [zoom, setZoom] = useState(12);
  const changeZoom = () => {
    if (mapRef.current !== null) {
      const newZoom = mapRef.current!.props.zoom;
      console.log(newZoom);
      setZoom(newZoom);
    }
  };

  return (
    <>
      // hogehoge
      <GoogleMap
        center={someCenter}
        zoom={zoom}
        ref={mapRef}
        onZoomChanged={changeZoom}
      >
        // fugafuga
      </GoogleMap>
    </>
  )
}
```

## How is it behave?

Whenever the zoom level changed, the output in the console is 12.

## How should it behave correctly?

The output should be changed?

## basic implementation of incorrect behavior in codesandbox.com

Working on it.

**Comment by JustFly1984** [comment]
there is no ref on <GoogleMap /> but there is onLoad prop calback function, which has an argument - instance to map.getZoom()

please look at examples.

**Comment by keita-makino** [comment]
@JustFly1984 
Thank you for your advice.  
Did you mean `useGoogleMap` hooks [here](https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/GoogleMap.md)?  
Is there an example to set the map instance on load using this?

**Comment by JustFly1984** [comment]
Example in read me and on npm package page

Also look docs
![DEF8A0C8-E766-4540-BD7A-DA1F112CA31D](https://user-images.githubusercontent.com/2255993/68047842-f20b9100-fce7-11e9-83ac-34451142ae6d.png)

**Comment by keita-makino** [comment]
@JustFly1984 
Aw I meant the docs for `useGoogleMap`.
I found the usage of onLoad props, but am using react16.8+ so if it's more convenient I like to go for the option :)
But thank you.

**Comment by JustFly1984** [comment]
@keita-makino well, this `useGoogleMap` is kind of new stuff, and we are going to refactor whole library to react hooks. If you want, you can look at source code, and add docs and examples. We are looking for contributors.

**Comment by keita-makino** [comment]
@JustFly1984 
Understood, thanks.
I did my work done with the old-fashion style but if any chance I like to contribute for the new approach :)

**Comment by JustFly1984** [comment]
@keita-makino you can look source. Also I have PR with attempt to refactor @react-google-maps/api to hooks. You can jump in and contribute.

**Comment by arthurhovhannisyan31** [comment]
I've done it like this
```
  const RenderMap = () => {
    // any code on load
    const onLoad = map => {
      map.addListener('zoom_changed', () => {
        setZoom(map.zoom)
      });
    };
      return (
        <GoogleMap
          options={options}
          onLoad={onLoad}
          id='example-map'
          mapContainerStyle={{
            height: `${mapHeight}px`,
            width: `${mapWidth}px`
          }}
          center={center}
          {...props}
        >
          <MapContent/>
          <MapSelectors/>
        </GoogleMap>
      )
  };
```

**Comment by JustFly1984** [comment]
@arthurhovhannisyan31 
Don't pass objects as props to components! this causes re-renders

**Comment by vcanales** [comment]
> Don't pass objects as props to components! this causes re-renders

What is then the correct way of setting  `center` and `mapContainerStyle`?

**Comment by JustFly1984** [comment]
You can keep `center` in state, or just in simple const outside the component scope.

`mapContainerStyle` could be a simple const outside the component, or memoized value with `React.useMemo`

**Comment by russmenum** [comment]
How do we update that center and zoom state onChange?

```js
onZoomChanged={ (event) => {
            //reCenterZoomHelper(event)
            console.log("onZoomChanged", event, GoogleMap.getZoom() );
} }
```

When I try and do this everything is coming back `undefined`. I need a way to access the current `center` and `zoom` values so I can update the state value when changed

**Comment by Sadman211** [comment]
Any update on this? onZoomChanged I am not getting any zoom level data.

**Comment by russmenum** [comment]
@Sadman211  what I ended up doing with trial and error was this:

```js

const {mapZoom, setMapZoom} = useState(UserContext);

const reCenterZoomHelper = () => {
    if (map && map.zoom) {
      setMapZoom(map.zoom)
    }
}


<GoogleMap
    zoom={forceNoZoom ? null : mapZoom}
    onZoomChanged={reCenterZoomHelper}
    ...
>

```

I have noticed some of the map refreshes can create a detached refresh so you may need helpers in some cases depending on what you are doing. But the ```zoom``` value is actually in the ```map``` object not actually returned by onZoomChanged it seems
