### ISSUE TITLE
Cursor doesn't works when hover on Markers (Safari)

### ISSUE THREAD

**Issue by pichjinnapat** [JustFly1984/react-google-maps-api#2514]
os: MacOS Safari

node --version v14.15.0

react version 17.0.1

@react-google-maps/api version ^2.0.2

## How is it behave?
I already input cursor props on Maker component `  <Marker cursor="pointer" position={position} /> ` when hovering on Markers, the cursor still be a regular cursor, not pointer. It does work on Chrome.

## How should it behave correctly?
The cursor should be pointer.

**Comment by breeze9527** [comment]
It seems to be a bug in Safari

see:
https://stackoverflow.com/questions/8820979/css-cursorpointer-in-mac-safari-doesnt-work
https://www.sitepoint.com/community/t/safari-mac-wont-show-cursor-pointer/102786

and test in here:
https://css-tricks.com/almanac/properties/c/cursor/
