### ISSUE TITLE
Infobox (and possibly other components) are badly extended

### ISSUE THREAD

**Issue by samuelpucat** [JustFly1984/react-google-maps-api#254]
Hi, I already mentioned this issue on spectrum:
https://spectrum.chat/react-google-maps/general/infobox-doesnt-react-to-options-change~fc8e01bd-3d2a-485c-880d-4a5002a13481 
and provided a possible solutions, but I'm hesitant to create a PR, because I'm not sure about the solution and the thread seems to be ignored now. Maybe a creator of Infobox could decide what to do. thanks

**Comment by JustFly1984** [comment]
@samuelpucat 
The thread is not ignored. All this incorrect extensions is legacy from original react-google-maps

If you want to try to fix it, your PR is welcome.

**Comment by JustFly1984** [comment]
published in 1.7.10

**Comment by samuelpucat** [comment]
@JustFly1984 thank you for a quick merge, however, after updating npm package to 1.7.10, I don't see the change in node modules. Did you publish @react-google-maps/infobox too?

**Comment by JustFly1984** [comment]
@samuelpucat sorry missed that, now should work, released 1.7.11

**Comment by JustFly1984** [comment]
@samuelpucat please confirm

**Comment by samuelpucat** [comment]
@JustFly1984 it's working, we can close this
