### ISSUE TITLE
Docs are broken due to conflict acorn@6.3.0 and @7 in react-styleguidist

### ISSUE THREAD

**Issue by JustFly1984** [JustFly1984/react-google-maps-api#255]
link to the issue
https://github.com/styleguidist/react-styleguidist/issues/1321#issuecomment-549135648

possible we need to change solution for docs

**Comment by kpascascio** [comment]
[GitBook](https://www.gitbook.com/) is a good solution, there is also a [mdx](https://mdxjs.com/) plugin so you can add in React components like in the initial docs

**Comment by JustFly1984** [comment]
@uriklar what do you think?

**Comment by kpascascio** [comment]
I would be open to helping migrate if needed, just let me know 😄

**Comment by JustFly1984** [comment]
@kpascascio sure, tell me if you need something.

**Comment by JustFly1984** [comment]
@kpascascio I think we need to consider switch to Docusaurus
https://docusaurus.io/ as an option
https://twitter.com/dai_shi/status/1197816235058069504

**Comment by gtherond** [comment]
Docusaurus is awesome and that would greatly help us new comer to integrate the library correctly and see if the component that we're using is really the one we're looking for at glance and not having to implement it before noticing that nope it's definitely not the correct component, like for infoBox and InfoWindow for instance ^^

**Comment by JustFly1984** [comment]
fixed docs by adding next lines to package.json
```json
{
"resolutions": { "acorn": "6.4.0" }
}
```

and also using `;` in markdown files :)|
