### ISSUE TITLE
[Autocomplete] How to get input value when select value from dropdown.

### ISSUE THREAD

**Issue by hungvtitdng** [JustFly1984/react-google-maps-api#2550]
I have used Autocomplete and select value from the dropdown. The value will be filled out to the input field. but I can't get value from it.

how to get that value on the input field. not callback value. just on the input field value

thanks,

**Comment by piotrbartnik** [comment]
No sure if there is a prop in the package for that but you can try react refs with something like:

```javascript
import React, { useRef } from 'react';

...

const ref = useRef(null);
console.log(ref.current?.value);

...
<Autocomplete
  onLoad={onAutocompleteLoad}
  onPlaceChanged={onPlaceChanged}
>
  <input
    ref={ref}
   />
</Autocomplete>
```

**Comment by hungvtitdng** [comment]
Thanks for your support, but I think that should be implemented on the callback `onPlaceChanged`

Thanks,
