### ISSUE TITLE
When offline not all calls to useLoadScript resolve correctly

### ISSUE THREAD

**Issue by coulson84** [JustFly1984/react-google-maps-api#262]
If there are multiple calls to useLoadScript when an app is offline (or, presumably, if some other area caused the google maps script to error) then only the first call to useLoadScript has its state correctly updated to show that there is an error. All the ones after this fail to be updated correctly.

**Comment by coulson84** [comment]
Have added a PR to fix this issue already but thought I would raise it as in issue for visibility
https://github.com/JustFly1984/react-google-maps-api/pull/261

**Comment by JustFly1984** [comment]
published 1.7.11
