### ISSUE TITLE
react-select is braking when I am using @react-google-maps/api

### ISSUE THREAD

**Issue by subhendukundu** [JustFly1984/react-google-maps-api#263]
# Please provide an explanation
https://i.stack.imgur.com/clrkJ.png
When I am using `@react-google-maps braking` the ui for `react-select`.
## Your Environment
```
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0
    Safari: 12.1.1
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-dom: 16.11.0 => 16.11.0 
    react-scripts: 3.2.0 => 3.2.0 
  npmGlobalPackages:
    create-react-app: Not Found
```
webpack version => using create-react-app

@babel version => using create-react-app

@react-google-maps/api version 1.7.10

## How is it behave?
https://i.stack.imgur.com/clrkJ.png
Braking css
## How should it behave correctly?
https://react-select.com/home like these examples
## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/usegooglemap-repro-x3q37

**Comment by JustFly1984** [comment]
your code is pretty messy. try to use typescript, it should help.

**Comment by JustFly1984** [comment]
please cleanup your code in example
