### ISSUE TITLE
Without `center` property GoogleMap component is empty.

### ISSUE THREAD

**Issue by Oleksandr-Korniienko-IS** [JustFly1984/react-google-maps-api#2637]
Related issues:
- https://github.com/JustFly1984/react-google-maps-api/issues/185

I am using TypeScript. The next code has no errors in terms of TypeScript:
```
        <GoogleMap
            mapContainerClassName="Map"
            zoom={0.8}
        />
```

but the map is empty:

![image](https://user-images.githubusercontent.com/55439839/120518078-d8599080-c3d9-11eb-96c0-ef9f28233323.png)

Even if I render Markers in GoogleMap as children - same situation.

And once I have added the center property - the issue was fixed.

```
        <GoogleMap
            center={{ lat: 0, lng: 0 }} // you can put here any other needed value
            mapContainerClassName="Map"
            zoom={0.8}
        />
```

Would be great to make `center` as required.

P.S. Many thanks for the library!

**Comment by JustFly1984** [comment]
center is required prop. look at console logs

**Comment by ruggiadufour** [comment]
Do you know how I could put a street  position / direction string instead coordinates?

**Comment by on3dd** [comment]
The documentation states that `center` is not required and may be undefined, check for yourself - https://react-google-maps-api-docs.netlify.app/#googlemap. There are also no console logs on this. Is there any valid reason why can't I use a map without an initial center position?
