### ISSUE TITLE
Improper warning related to libraries prop inside of useLoadScript hook

### ISSUE THREAD

**Issue by joshuascott** [JustFly1984/react-google-maps-api#265]
In this call to the useLoadScript hook:
```
const { isLoaded, loadError } = useLoadScript({
    id: 'script-loader',
    googleMapsApiKey: process.env.REACT_APP_GOOGLE_API_KEY,
    libraries: (process.env.REACT_APP_GOOGLE_LIBRARIES || '').split(','),
  });
```

**The browser shows a warning:**
Performance warning! Loadscript has been reloaded unintentionally! You should not pass `libraries` prop as new array. Please keep an array of libraries as static class property for Components and PureComponents, or just a const variable outside of component, or somewhere in config files or ENV variables

Given that we are pulling this value from an env variable, the message should either:
1. Not display at all.
2. Have a clearer message to describe what is going.

*The only extenuating circumstance that I can think of is this is being called from within a functional component rather than a class component.*

**Comment by JustFly1984** [comment]
you need to save `(process.env.REACT_APP_GOOGLE_LIBS || '').split(',')` into const outside of component scope, and pass it to libraries.
