### ISSUE TITLE
How to get `LatLngBounds`?

### ISSUE THREAD

**Issue by bitttttten** [JustFly1984/react-google-maps-api#266]
I am looking at to fit a map within some bounds. Usually, you can do it like so:

```js
    const boundary = new google.maps.LatLngBounds()
    locations.forEach(({ lat, lng }) => {
        boundary.extend({ lat, lng })
    })
    map.fitBounds(boundary)
```

I have looked through the docs for an example like this but I came up short. What's the "@react-google-maps/api" way to do this?

**Comment by lluisrojass** [comment]
Functionality not directly related to rendering objects related to a map instance would flow through the lib as you are doing now. This lib doesn't expose any helpers, and seems to take an opinionated stance against exposing any internals. Even onLoad hooks only give you formal g-maps objects.

**Comment by bitttttten** [comment]
Yeah, so sadly it doesn't look like it's easily possible. Especially when trying to keep your UI declarative.

**Comment by bitttttten** [comment]
I ended up just using the literal.

```js
    const markerBoundary: google.maps.LatLngBoundsLiteral = {
        north: 0,
        south: 0,
        east: 0,
        west: 0,
    }
```
