### ISSUE TITLE
Page is scrolling to the map's position when it loads.

### ISSUE THREAD

**Issue by gotplitz** [JustFly1984/react-google-maps-api#2668]
## Please provide an explanation

The pages that has the map they are scrolled automatically to the map position when the pages loads the first time, this is one example [https://libe.ferociousmediaweb.com/](https://libe.ferociousmediaweb.com/). It happens with React and NextJS. I updated to the new version, but I'm still having the issue. What I'm doing right now is using LazyLoad to fix the issue temporary, but if you see, when the map is in the view port it jumps weirdly too.

## Your Environment

os: I work on Mac and deploy to Ubuntu Droplet in DO

node --version 14.15.4

react version 17.0.2

@react-google-maps/api version 2.1.1

**Comment by JustFly1984** [comment]
you should open the map only on user interaction with website, never preload it for SSR. You can use an image as failback.

**Comment by gotplitz** [comment]
> you should open the map only on user interaction with website, never preload it for SSR. You can use an image as failback.
> Also you can use IntersectionObserver to load the map then user scrolls close.

Yes, that was my solution, I'm using LazyLoad from react-lazy-load, but this was just recently, I never had that issue? It is something about new updates? Now I have to change all my websites that have the map. BTW, that site is not SSR, is Client Side, was created with React, I have others that are SSR with NextJS. 

Thanks for your response.

**Comment by JustFly1984** [comment]
@gotplitz I don't know. I only maintain this lib at this point, not using it for myself.
