### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by siddique-qazi-viabletree** [JustFly1984/react-google-maps-api#2781]
In 3 to 4 days, an example code works 2 times and then does not work even if i did'nt make any changes to the code,just refreshed the page and it says uncaught reference error:google is not defined. I am using this code in react admin. Attached zip is code.It also has screenshot of error i am getting
[Maps.zip](https://github.com/JustFly1984/react-google-maps-api/files/6839592/Maps.zip)

**Comment by JustFly1984** [comment]
please provide minimal reproduction in codesandbox

**Comment by petarproko** [comment]
I'm having the same issue and I noticed that it happens when you start loading script and then you quickly go back to previous page and then this error happens. In my case it's because it's trying to load script on unmounted component. Hope it helps.

**Comment by siddique-qazi-viabletree** [comment]
using isLoaded and useJsApiLoader solved the issue for me
const { isLoaded } = useJsApiLoader({
    id: "google-map-script",
    googleMapsApiKey: 'google-api-key',
  });
    return isLoaded ? (
    <div className="map">
      <div className="map-container">
        <GoogleMap
          id="shapes-example"
          mapContainerStyle={styles.container}
          zoom={12}
          center={mapCenter}
          onClick={(e) => handleClick(e)}
        >
          <Polygon path={coords} options={m_sfPolygonOptions} />;
        </GoogleMap>
      </div>
    </div>
  ) : (
    <></>
  );

**Comment by siddique-qazi-viabletree** [comment]
Resolved by doing above changes
