### ISSUE TITLE
Provide ESM module also.

### ISSUE THREAD

**Issue by thescarymelon** [JustFly1984/react-google-maps-api#28]
The package.json module field points to a bundled commonjs format output. The module field in package.json is not an NPM officially supported field but is supported by Webpack so we can consume an ESM format and get the benefits of treeshaking. 

I'm more than happy to put in a PR to change your build set up so the output of the dist folder is not bundled and is also in the ESM format. I should have the time in the next day or two to put in the PR 👍

**Comment by JustFly1984** [comment]
@thescarymelon I think it is tree shakable as it is, but if you want to add one more directory with mjs files, I think it is ok.

**Comment by JustFly1984** [comment]
Done in 1.2.3
