### ISSUE TITLE
How to make all markers show in a map using fitBounds()?

### ISSUE THREAD

**Issue by MarkCay** [JustFly1984/react-google-maps-api#2814]
# Issue template

If you want to ask question, ask it in Github Discussions, [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Your Environment

OS: mac

Node: v14.17.3

Ionic React: 6.16.3

react version: ^17.0.1

@react-google-maps/api version: ^2.2.0

## How does it behave?
I am using this in my Ionic React project. I want to make all the `<Marker>` I put in my `<GoogleMap>` to be shown (dynamic zoom, not to the point where I have to zoom out to its maximum to see all the markers). I tried researching and found out that I have to use `fitBounds()` but I cannot find a way to access the map's LatLngBounds. Please help me. Thank you.

**Comment by ShayanAliAbbasi** [comment]
You can try this function.
Call it when the map has loaded and position of the markers (latitude, longitude) is loaded or changes.

``` javascript
 fitBounds() {
   // window.google.maps is automatically added to global window object after map loads
    const bounds = new window.google.maps.LatLngBounds();

   // array containing positional data of markers
    markers.forEach(marker => {
      bounds.extend({lat: marker.latitude, lng: marker.longitude);
    });
   
   // The map object you get from <GoogleMap> onLoad
    map.fitBounds(bounds);
  }
```

**Comment by MarkCay** [comment]
> You can try this function.
> Call it when the map has loaded and position of the markers (latitude, longitude) is loaded or changes.
> 
> ```js
>  fitBounds() {
>    // window.google.maps is automatically added to global window object after map loads
>     const bounds = new window.google.maps.LatLngBounds();
> 
>    // array containing positional data of markers
>     markers.forEach(marker => {
>       bounds.extend({lat: marker.latitude, lng: marker.longitude);
>     });
>    
>    // The map object you get from <GoogleMap> onLoad
>     map.fitBounds(bounds);
>   }
> ```

But this is the error I receive whenever I try to access window.google inside the onLoad of my google map
: Property 'google' does not exist on type 'Window & typeof globalThis'.

**Comment by MarkCay** [comment]
I already found a solution in Stackoverflow: [https://stackoverflow.com/questions/55464196/property-google-does-not-exist-on-type-window](https://stackoverflow.com/questions/55464196/property-google-does-not-exist-on-type-window).

It turns out I just need to install `@types/googlemaps` or at least access the `window.google` as `(window as any).google`. Thank you for responding! I really appreciate the help.
