### ISSUE TITLE
onCenterChanged trigger infinite loops

### ISSUE THREAD

**Issue by mjr** [JustFly1984/react-google-maps-api#2841]
## Describe the bug

onCenterChanged trigger infinite loops.

## To Reproduce

1. Go to https://codesandbox.io/s/zealous-poincare-0idq2?file=/pages/index.js
2. Drag map.
3. See the console to see react warning.

## Screenshots

<img width="918" alt="Screen Shot 2021-08-25 at 21 30 32" src="https://user-images.githubusercontent.com/9324986/130881649-41ed809d-2805-49b8-9f1b-a7a3ab4d463d.png">

**Comment by cesalberca** [comment]
This is still happening, are there any workarounds?
