### ISSUE TITLE
Directions language on first load is incorrect. 

### ISSUE THREAD

**Issue by georgeiliadis91** [JustFly1984/react-google-maps-api#2848]
# Issue template
On first load the language of the directions in English, despite being asked to return in German. 

The issue I am facing is that i am using this library and on my german domain inside the script loader i pass the prop 
`language: 'de'` yet if it is the first time the website. is loaded. (tried with cleaning cache/cookies) the language is English. 
## Your Environment

browser: chrome, firefox, didnt test. on safari. 

os: mac/windows/ios did not test android linux

react version 16.9

@react-google-maps/api version. latest

## How is it behave?
On first load. of. the component dispite passing the correct props for the language to be german, the directions feature is in english.

## How should it behave correctly?
It should be in german as passed in the props.

**Comment by JustFly1984** [comment]
I guess it could be google issues

**Comment by georgeiliadis91** [comment]
I will close this issue, since I found the reason this was happening. Per the docks I was using the LoadScript component, that is not. suggested anymore + there was a second instance of it on a sub component. Leading to all sorts of unexpected behaviours.

**Comment by JustFly1984** [comment]
There should be only one instance of LoadScript or useLoadScript hook per application
