### ISSUE TITLE
Events not triggered

### ISSUE THREAD

**Issue by Alin13** [JustFly1984/react-google-maps-api#2851]
Hello,

I'm using the GoogleMap component in a project where I need to listen for two events: **onDragStart** and **onDblClick**. Everything worked just fine until two weeks ago, when these events stopped being triggered. I also tried the rest of the events and it seems that the ones that are related to the mouse are not working (_onDrag, onDragStart, onDragEnd, onClick, onRightClick, onDblClick, onMouseMove, onMouseOut, onMouseOver..._)

This is how the code looks like:

```
<GoogleMap
      zoom={14}
      clickableIcons={false}
      mapContainerStyle={mapContainerStyle}
      onLoad={handleMapLoad}
      onDragStart={() => setFreeMap(true)}
      center={DEFAULT_MAP_CENTER}
      options={{
        backgroundColor: 'transparent',
        zoomControl: true,
        mapTypeControl: false,
        scaleControl: true,
        streetViewControl: false,
        rotateControl: false,
        fullscreenControl: false,
        disableDoubleClickZoom: true,
        draggableCursor: 'pointer',
        draggingCursor: 'pointer'
      }}
      onDblClick={({ latLng }) => {
        if (!isMapRoute) {
          setLocation({ lat: latLng.lat(), lng: latLng.lng() }, true);
        }
      }}
    >

...

</GoogleMap>
```

Environment:
- react ^16.14.0
- @react-google-maps/api ^2.2.0

The code wasn't changed, the packages were not updated.

Any ideas how to fix this? Thank you!

**Comment by gemilangpermata** [comment]
This also happens in my project, I try to specify the version of google-map script to `3` and now it works again.

```
useLoadScript({
  googleMapsApiKey: <your_key>,
  version: '3',
})
```

**Comment by Alin13** [comment]
Yep, you are right. Adding the version on LoadScript component solved the problem.

Thank you very much!
