### ISSUE TITLE
onLoad and onUnmount are required in typing of KmlLayerProps

### ISSUE THREAD

**Issue by kuzkokov** [JustFly1984/react-google-maps-api#2869]
Hey, guys. Thanks for your work here!

## Please provide an explanation
So, as it says in the title, onLoad and onUnmount callbacks are required in typing of KmlLayerProps, but I believe they shouldn't be.

**Comment by JustFly1984** [comment]
@kuzkokov if you want, you can provide a PR, and I will release new version

**Comment by kuzkokov** [comment]
sure, thanks

**Comment by kuzkokov** [comment]
@JustFly1984 here you go #2870

**Comment by JustFly1984** [comment]
released 2.4.1
