### ISSUE TITLE
InfowWindow overwrited styles messed up

### ISSUE THREAD

**Issue by AlexOros** [JustFly1984/react-google-maps-api#288]
Hello I am using @react-google-maps/api and it's awesome, but I ran in the following problem: 
I have multiple map instances on multiple pages (works well, no more "included multiple times" errors ) and when I unmounted the first map instance the InfoWindow component (for which I have overwritten some styles) is back to default CSS settings. The overwritten CSS classes don't apply anymore. Here is an example of the CSS classes I overwrite:
```sass
.gm-style .gm-style-iw-c {
  max-width: 96% !important
  width: 300px !important

  .gm-ui-hover-effect {
    font-size: 30px !important 
    top: -2px !important
    right: 6px !important
    img {
      height: 25px !important
      width: 22px !important
    }
  }
  .gm-style-iw-d {
    max-width: 96% !important
    width: 300px !important
  }
}
```
I think it has something to do with "cleaninig up window.google object on Unmount" but I might be wrong

**Comment by JustFly1984** [comment]
@AlexOros  yeah, we are cleaning up all <style> tags with .gm_style classes

can't give you advice on how to workaround now

**Comment by hoango7604** [comment]
https://github.com/JustFly1984/react-google-maps-api/issues/1361#issuecomment-762813572
@JustFly1984 I think using useJsApiLoader hook could help you
