### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by cdakin1** [JustFly1984/react-google-maps-api#29]
Hi, just migrating over here from `react-google-maps`.

I tried recreating the example in the [demo](https://react-google-maps-api.netlify.com/) but I'm unable to get past an `regeneratorRuntime is not defined` error that breaks the application.

I thought maybe it had something to do with the application I'm running it in, but I also could not get the example working in a [code sandbox](https://codesandbox.io/s/wyp131oz7w).

Any help or suggestions would be greatly appreciated!

![image](https://user-images.githubusercontent.com/21347228/51283702-ad0fab80-19ae-11e9-8f4d-ab3bd4ec40f4.png)

**Comment by JustFly1984** [comment]
@cdakin1 we are using gatsby.js as example, it has built-in babel. 
Please refer to https://github.com/gatsbyjs/gatsby/tree/master/packages/babel-preset-gatsby

**Comment by uriklar** [comment]
So if I understand correctly this means the lib currently doesn't work with babel 6? Sounds like something we should support. From some short googling it looks like adding: https://babeljs.io/docs/en/6.26.3/babel-plugin-transform-runtime could do the trick.
@cdakin1 do you want to give it a try?

**Comment by cdakin1** [comment]
I'm using the latest gatsby.js which includes babel @7.2 and it's still broken.

**Comment by anton-nagornyi** [comment]
Please try to 
npm install @babel/plugin-transform-runtime --save-dev

**Comment by JustFly1984** [comment]
Ok, I've got this error, working on it right now.

**Comment by JustFly1984** [comment]
@cdakin1 Actually you need to use `babel-polyfill` to fix your issue.

**Comment by cdakin1** [comment]
Okay so I tried all the fixes above but none of them were working. I knew they SHOULD be though, those were definitely the things I was missing, which lead me to believe they weren't being utilized despite being included in the project. 

Since gatsby.js already includes all the @babel stuff I needed I removed all the manually added @babel libraries and did this instead:

![image](https://user-images.githubusercontent.com/21347228/51397463-ed823d00-1b06-11e9-82a3-38e294cb80a8.png)

Adding `path.resolve("./node_modules/react-google-maps-api")` to my `gatsby-node.js` fixed the issue!

Thanks for your help guys.

**Comment by JustFly1984** [comment]
@cdakin1 Ok, I got it, you just need to conditionally check for typeof document, you do not need to provide `@babel/polyfill` for node.

```
typeof document !== 'undefined' && (
  <LoadScript><GoogleMap/></LoadScript />
)
```

You need to import `@babel/polyfill` only in dev

There is no document, window or google objects in node stage, so you can't render `react-google-maps-api` with SSR or statically. I would advise you to set the height of container, so layout do not jump in runtime.

**Comment by JustFly1984** [comment]
@cdakin1 
minimal code for gatsby.browser.js
```
import "@babel/polyfill";
export function onClientEntry () {};
```

**Comment by uriklar** [comment]
@cdakin1 when using the latest lib version (@react-google-maps/api v1.0.3) your codesandbox works. 
Can you try updating?

**Comment by JustFly1984** [comment]
@cdakin1 please update to latest version @react-google-maps/api@1.0.8
