### ISSUE TITLE
Map is not responsive 

### ISSUE THREAD

**Issue by udemezue01** [JustFly1984/react-google-maps-api#2900]
# Issue template

If you want to ask question, ask it in Github Discussions, [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Please provide an explanation
The map is not responsive, cannot adjust based on screen size

## Your Environment

os: windows

node -- version - v14.17.0

react version - 17.0.1

webpack version - 

@babel version

@react-google-maps/api version - 2.5.0

## How is it behave?

Map is not responsive.

## How should it behave correctly?

Map should be responsive.

## basic implementation of incorrect behaviour in codesandbox.com

![Screenshot (278)](https://user-images.githubusercontent.com/16034417/140927555-cba5b82a-ddac-4642-903f-d4e07f5880b6.png)

**Comment by zeeking786** [comment]
Try to use ```containerElementStyle``` like this and it will be mobile responsive too:
```const containerElementStyle = { width: "100%", height: "height_in_px" };```
