### ISSUE TITLE
Zoom Property not Working 

### ISSUE THREAD

**Issue by Sheraz008** [JustFly1984/react-google-maps-api#2923]
# Zoom Behaviour not working 
zoom or default zoom of map not working even after passing value from 0 to 10 according to documentation ,Please have look on this issue also

**Comment by lacepek** [comment]
Are you calling fitBounds on Map object by any chance? Default zoom seems to get ignored if you call it. Hope this helps.

**Comment by abhimanyu95** [comment]
> Are you calling fitBounds on Map object by any chance? Default zoom seems to get ignored if you call it. Hope this helps.

@lacepek Thanks for your answer, i was struggling with this issue.
