### ISSUE TITLE
DirectionsService component making too many calls to Google Direction API

### ISSUE THREAD

**Issue by gadishimwe** [JustFly1984/react-google-maps-api#2924]
## How is it behave?
DirectionsService component causes too much re-rendering and results in making too many calls to Google API which only stops when you hit OVER_QUERY_LIMIT.

## How should it behave correctly?
I should only make one API call because Directions API can be costly.

## basic implementation of incorrect behavior
https://react-google-maps-api-docs.netlify.app/#directionsrenderer-and-directionsservice-example

You can see this in the official documentation example. If you open the browser console, you will be able to view these calls after putting in origin and destination coordinates.

**Comment by MishaKav** [comment]
Same issue. It's a bug?

**Comment by gadishimwe** [comment]
> Same issue. It's a bug. Found solution here [#447 (comment)](https://github.com/JustFly1984/react-google-maps-api/issues/447#issuecomment-621994263)

Yeah. Thanks, @MishaKav I'll give it a try

**Comment by JustFly1984** [comment]
use eslint + eslint-plugin-react-perf
