### ISSUE TITLE
There is no  information about long and lat when we drag the marker

### ISSUE THREAD

**Issue by MehmetCanBOZ** [JustFly1984/react-google-maps-api#2939]
# Issue template

 `{latLng: Object, domEvent: MouseEvent, pixel: Object, jb: undefined, stop: ƒ ()…}
 latLng: Object
  lat: ƒ () {}
  lng: ƒ () {}
  toString: ƒ () {}
  toJSON: ƒ () {}
  equals: ƒ () {}
  toUrlValue: ƒ () {}
  domEvent: MouseEvent
  pixel: Object
  jb: undefined
  stop: ƒ () {}
  👍 ƒ () {}
`

## Please provide an explanation
When drag the marker, there is no information about lat,long but just empty function.
## Your Environment

os: mac

react version
 "react": "17.0.1",
webpack version
    "webpack": "5.56.0",
    "webpack-cli": "4.9.0",
@babel version
"@babel/core": "7.15.5",

@react-google-maps/api version
"@react-google-maps/api": "2.7.0",

## How is it behave?
When drag the marker, there is no information about lat,long but just empty function.
## How should it behave correctly?
It must gives lat and long
## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/react-google-maps-api-simple-draggable-marker-forked-on02e?file=/src/App.js

**Comment by scottboyd-ai** [comment]
I am currently dealing with an issue that would be resolved if the drag event had a regular MapMouseEvent variable passed in. Is this a possibility to fix? Or is this something limited by Google?
