### ISSUE TITLE
global.reactDom not found (it should be global.ReactDOM?)

### ISSUE THREAD

**Issue by zwarmapapa** [JustFly1984/react-google-maps-api#295]
We use the UMD version of the library. 

It accesses ReactDOM with global.reactDom (like window.reactDom), which is not defined. 

It should be global.ReactDOM, as window.ReactDOM is defined. 

In file /react-google-maps--api/dist/reactgooglemapsapi.umd.development.js it's found on line 4 as "global.reactDom". 

In file /react-google-maps--api/dist/reactgooglemapsapi.umd.production.min.js it's found on line 1 as "e.reactDom".

**Comment by zwarmapapa** [comment]
Here, on line 15, it can be seen that the variable that ReactDOM defines is global.ReactDOM (window.ReactDOM): https://unpkg.com/browse/react-dom@16.12.0/umd/react-dom.development.js

**Comment by JustFly1984** [comment]
@zwarmapapa we are using tsdx to build umd. Could be an issue with build tool. can't really tell what is an issue, co I'm not using umd myself. your PR is welcome

**Comment by zwarmapapa** [comment]
Ah I see. I think tsdx tries to guess the correct global variable from how it's used in the code. Maybe it's failing because the code does this:

`import { createPortal } from "react-dom"`

Instead of this:

`import * as ReactDOM from "react-dom"`

I've tested it out and indeed, that change fixed it. I'll make a PR.

**Comment by zwarmapapa** [comment]
Made a PR (on my other account) here: https://github.com/JustFly1984/react-google-maps-api/pull/302#issue-346836229

**Comment by JustFly1984** [comment]
@zwarmapapa  published 1.7.13 please test

**Comment by JustFly1984** [comment]
@zwarmapapa thank you for contribution

**Comment by zwarmapapa** [comment]
Great it worked! It uses global.ReactDOM now which is correct. Thanks for the quick update.
