### ISSUE TITLE
InfoBox disappear when map update.. 

### ISSUE THREAD

**Issue by Resource-3** [JustFly1984/react-google-maps-api#2954]
I have four tabs, where i am using map on those tabs when click on tab it's changes render,

I have wrapped INfoBox inside the Marker to show specific icon.. 

On first load it working fine in first tab showing InfoBox.

But when i switch tabs it disappear in other tabs. Would you please help me out

<Marker
        icon={{
            path: window.google.maps.SymbolPath.CIRCLE,
            fillColor: color,
            fillOpacity: 0.15,
            scale: Math.pow(2, 5.0) / 0.5,
            strokeColor: "white",
            strokeWeight: 0,
            position: "relative"
        }}
        position={MarkerPosition}
        draggable={false}
    >
        <InfoBox
            position={MarkerPosition}
            onLoad={onLoadMark}
        >
            <div className="marker_cricle">
                <div className="icon-Location" style={{ color: color }}></div>
            </div>
        </InfoBox>
    </Marker>

**Comment by JustFly1984** [comment]
use useMemo for icon prop
