### ISSUE TITLE
Map doesn't load after navigating away and coming back to map view

### ISSUE THREAD

**Issue by rajat5107** [JustFly1984/react-google-maps-api#2963]
Map doesn't load after navigating away and coming back to map view

PFA the link for small demo
https://codesandbox.io/s/react-google-maps-api-multiple-markers-infowindow-forked-ltgyjr?file=/src/Map.js
Steps to reproduce
1-When I Click on change view button it goes to map view
2- When clicking on change view button again it goes to text view  containing hii
3- Click on change view button again , then map doesn't load

Can you tell me what's the issue?

**Comment by drchorney** [comment]
yeah I'm noticing the same thing, just started today, I think it has to do with the `map.fitBounds()` function, there was a release today to 'fix' the `map.fitBounds()` function.... https://developers.google.com/maps/documentation/javascript/releases

**Comment by drchorney** [comment]
yeah looks like `3.48.6` has some breaking changes. In the meantime, when setting up useJsApiLoader you can set an older google maps javascript api version.

```
const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: "YOUR_API_KEY"
    version: '3.47'
  })
```

if you are using next.js you can do:

```
<LoadScriptNext
  googleMapsApiKey="YOUR_API_KEY"
  version="3.47"
>
...
```
Some references:
* [javascript google maps api release notes](https://developers.google.com/maps/documentation/javascript/releases)
* [note on javascript google maps api versioning](https://developers.google.com/maps/documentation/javascript/versions)

**Comment by ninjacarr** [comment]
All 3.48.x versions seems to have this issue, so probably not related the the `fitBounds()` fix.
Last working version is 3.47.6. Workaround from @drchorney works for now.

**Comment by hyunjoogo** [comment]
@drchorney Thank you. I didn't solve this problem until you commented.

**Comment by giriawu** [comment]
@drchorney Thank you so much! It really helps me a lot. Here is my demo to solve this situation, if anyone need.
https://codesandbox.io/s/googlemap-popup-tesing-forked-hk3ugw?file=/src/map.js
