### ISSUE TITLE
Loader must not be called again with different options error in ssr

### ISSUE THREAD

**Issue by giriawu** [JustFly1984/react-google-maps-api#2972]
# Code: 
```javascript
const MyMap = ({
  bounds,
  center,
  children,
  googleMapsApiKey,
  loadingElement,
  zoom,
}) => {
  const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey,
    version: '3.46',
  });
  const [map, setMap] = useState(null);

  if (!bounds && !center) {
    throw new Error('Provide either `bounds` or `center` props.');
  }

  const onLoad = useCallback(
    (mapInstance) => {
      if (mapInstance && bounds) {
        mapInstance.fitBounds(bounds);
      }
      setMap(mapInstance);
    },
    [bounds],
  );

  const onUnmount = useCallback(() => {
    setMap(null);
  }, []);

  if (!isLoaded) {
    return loadingElement;
  }

  return (
    <GoogleMap
      onLoad={onLoad}
      onUnmount={onUnmount}
      center={center}
      zoom={zoom}
    >
      {children}
    </GoogleMap>
  );
};

export default memo(MyMap);

```

## Your Environment

os: mac

node: v16.4.2

react: v16.14.0

@react-google-maps/api: v2.7.0

## How is it behave?
It throws Error: Loader must not be called again with different options in SSR packages

And according to the log, it firstly new Loader with googleApiKey is `""`, then it called again with the right googleApiKey.

## How should it behave correctly?
It should call new Loader with the same right googleApiKey.

It seems that google-map-react has some fix on this bug by this PR: https://github.com/google-map-react/google-map-react/pull/968

How can we control not allowing it to call new Loader when googleApiKey is null in SSR?

**Comment by JustFly1984** [comment]
This is only Client Side Rendering package. You can't mount the script in Node.js environment, cos there is no DOM API.

You should consider to test for browser conditionally rendering component using `useLoadScript` hook or `<LoadScript />`
