### ISSUE TITLE
Tries to get Google Fonts even when `preventGoogleFontsLoading` is set

### ISSUE THREAD

**Issue by polys** [JustFly1984/react-google-maps-api#2981]
# Issue template

If you want to ask question, ask it in Github Discussions, [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Your Environment

OS: Windows

Node 16.14.2

React 17.0.2

@react-google-maps/api 2.8.1

## How is it behave?
It makes requests to https://fonts.gstatic.com and https://fonts.googleapis.com

## How should it behave correctly?
It shouldn't make those requests.

**Comment by JustFly1984** [comment]
@polys your PR is welcome

**Comment by JustFly1984** [comment]
@polys  please check latest version 2.10.1
