### ISSUE TITLE
Please avoid inline styles and make it CSP friendly

### ISSUE THREAD

**Issue by polys** [JustFly1984/react-google-maps-api#2982]
# Issue template

If you want to ask question, ask it in Github Discussions, [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Your Environment

OS: Windows

Node 16.14.2

React 17.0.2

@react-google-maps/api 2.8.1

## How is it behave?
Uses inline styles

## How should it behave correctly?
Not use inline styles

**Comment by JustFly1984** [comment]
@polys your PR is welcome.

**Comment by JustFly1984** [comment]
Originally the code was written long time ago when nobody cared about CSP at all. It is an old legacy, so if you ready to replace style logic with css, your PR is welcome.

**Comment by polys** [comment]
By looking into it a bit more, I think all the inline styles I came across recently are coming from Google Maps itself.

I guess there's nothing we can do about it here, so happy to close this issue.

**Comment by JustFly1984** [comment]
@polys You can file an issue in google's bug tracker
