### ISSUE TITLE
i can't change mode with custom button

### ISSUE THREAD

**Issue by amirhosein-rafeie** [JustFly1984/react-google-maps-api#2995]
# Issue template

If you want to ask question, please ask it in Github Discussions, [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR's or feature requests are allowed. Minimal reproduction in codesandbox.io is required.

## Your Environment

os: windows

node --16.13.0

react version 17.0.2

@react-google-maps/api version 2.8.1

## How does it behave?
we don't have acccess to setDrawingModes by ref

## How should it behave correctly?
we should be able to change drawingModes by Ref

## Basic implementation of incorrect behavior in codesandbox.com
const drawingRef = useRef();

<DrawingManager
          ref={drawingRef}
          drawingMode="polygon"
          onLoad={(e) => console.log(e)}
          options={{
            drawingControl: true,
            drawingControlOptions: {
              drawingModes: ["polygon"],
            },
            polygonOptions: {
              editable: true,
              draggable: true,
              strokeColor: "red",
              strokeWeight: 2,
            },
          }}
        />
<button onClick={()=>{
drawingRef.current.setDrawingMode(null); //it doesnt work
}}>Change Mode </button>

**Comment by JustFly1984** [comment]
@amirhosein-rafeie There is no ref prop on components. use onLoad prop function to receive an instance in arguments.

ref is old way to receive instance used by unmaintained npm `react-google-maps-api@9.4.5` library

This library never had a `ref` property!
