### ISSUE TITLE
Cannot npm install react-google-maps-api in React 18

### ISSUE THREAD

**Issue by Ebukachuqz** [JustFly1984/react-google-maps-api#3001]
I Have been tryong to use this great package in react 18 but i keep getting errors when i tryy to NPM INSTALL it.

os: linux

node --version 16

react version 18

@react-google-maps/api version 2.8.1

**Comment by Primajin** [comment]
Duplicate of #2978 I guess?

**Comment by Ebukachuqz** [comment]
> Duplicate of #2978 I guess?

Not exactly. It was about failed functionalities, here I can't even install the package

**Comment by JustFly1984** [comment]
Please post screenshots of errors

**Comment by JustFly1984** [comment]
released 2.10.1, please retry
