### ISSUE TITLE
Cluster does not work

### ISSUE THREAD

**Issue by RuckieOfficial** [JustFly1984/react-google-maps-api#3005]
I tried to make cluster based on example that is not working either.
https://react-google-maps-api-docs.netlify.app/#markerclusterer
![Screenshot from 2022-04-25 11-38-48](https://user-images.githubusercontent.com/43410493/165063291-f93cfc29-4b03-4b81-b071-33cc94f30ed7.png)

os: **Linux**
node --version 16.10
react version 17
@react-google-maps/api version 2.8.1

Is it still maintained, or there is new solution?

**Comment by JustFly1984** [comment]
@RuckieOfficial  Docs are broken due to unmaintained packages. We are in need to replace docs app.

**Comment by RuckieOfficial** [comment]
@JustFly1984 Unfortunately there is not example with marker cluster, not even with marker. If you mean this example: [](https://react-google-maps-api-gatsby-demo.netlify.app/)
