### ISSUE TITLE
Support Cluster Renderer Option

### ISSUE THREAD

**Issue by quantran020173** [JustFly1984/react-google-maps-api#3008]
# Featuer Request
Could you please add the Cluster renderer option so we can custom Cluster?

## Please provide an explanation of the issue
https://googlemaps.github.io/js-markerclusterer/#migration

## How does it behave?
No option for Cluster Component renderer

## How should it behave correctly?
Support way to custom Cluster renderer

## Basic implementation of incorrect behavior in codesandbox.com
https://googlemaps.github.io/js-markerclusterer/public/renderers/

**Comment by JustFly1984** [comment]
@quantran020173 Your PR is welcome
