### ISSUE TITLE
Standalone search box, getPlaces method

### ISSUE THREAD

**Issue by dobrea-v** [JustFly1984/react-google-maps-api#301]
# Please provide an explanation
In Google Maps Places API, there is [note](https://developers.google.com/places/web-service/details#fields) that you can specify 'fields' query parameters to get less data in response, thus getting billed less. Is there a way to specify this parameters?

## How is it behave?
By default Google Places getPlaces method returns all fields.

## How should it behave correctly?
It would be great if we could specify what fields to include

**Comment by JustFly1984** [comment]
Can you provide minimal reproduction in codesandbox.com?

**Comment by dobrea-v** [comment]
Well in my case i should've used Autocomplete component. But there is this StandaloneSearchBox which i don't know how exactly differs in functional way from Autocomplete. But Autocomplete has a prop fields which can get and array of props ex: ['formatted_address', 'geometry'], that in response from Google Place API will return just this specified fields. Thus reducing the billing price. I wonder why StandaloneSearchBox doesn't have this fields, and what is it's use case. But that's another topic, so i will close this question
