### ISSUE TITLE
Deprecated function addDomListener()

### ISSUE THREAD

**Issue by RuckieOfficial** [JustFly1984/react-google-maps-api#3012]
google.maps.event.addDomListener() is deprecated, use the standard addEventListener() method instead: https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener
The feature will continue to work and there is no plan to decommission it.

I have this warning (rendered many times). Is there any way to hide it or someone must to rewrite these functions?
![Screenshot from 2022-04-29 09-12-16](https://user-images.githubusercontent.com/43410493/165899786-1b8f5468-3597-4468-a32e-ce3702ddeb61.png)

**Comment by JustFly1984** [comment]
As I understand correctly, this errors originate from google maps api itself. There was similar issues before, please look, closing it as repeated.
