### ISSUE TITLE
Marker not rendering on localhost using latest version

### ISSUE THREAD

**Issue by Krechals** [JustFly1984/react-google-maps-api#3019]
Marker is not rendering on localhost using @react-google-maps/api@2.10.2

However, after downgrading to @react-google-maps/api@2.7.0, the Marker is displayed on the map.

Here is the code snippet I am using:
```
function Map() {
  const position = useMemo(() => ({ lat: 44.426765, lng: 26.102537 }), []);
  const { isLoaded } = useLoadScript({
    googleMapsApiKey: process.env.REACT_APP_GOOGLE_MAPS_API_KEY,
  });

  if (!isLoaded) return <div> Loading Maps... </div>
  return (
      <GoogleMap 
        zoom={10}
        center={position}
        mapContainerStyle={{ width: '400px', height: '400px'}}
      >
        <Marker position={position} /> 
      </GoogleMap>
  );
}
```

## Environment

os: Linux

node --version: v16.13.0

react version: 18

@react-google-maps/api version: 2.10.2

**Comment by JustFly1984** [comment]
@Krechals please provide minimal reproduction in codesandbox.io

**Comment by leidto** [comment]
+1

**Comment by JustFly1984** [comment]
use MarkerF instead for react@18

MarkerF is hook based, and has no issues.

**Comment by Shaker-Hamdi** [comment]
> use MarkerF instead for react@18
> 
> MarkerF is hook based, and has no issues.

Dude, I've been pulling my hair for two straight hours wondering what is wrong, you rock.
