### ISSUE TITLE
why marker cluster is causing lag in the browser when data sets is large how can i fix this? i am also getting the warnings in the console "google.maps.event.addDomListener() is deprecated, use the standard addEventListener() method instead" any idea?

### ISSUE THREAD

**Issue by GautamChaudhary0923** [JustFly1984/react-google-maps-api#3021]
# Issue template

You can donate or became a sponsor [https://opencollective.com/react-google-maps-api#category-CONTRIBUTE](https://opencollective.com/react-google-maps-api#category-CONTRIBUTE)

If you want to ask question, please ask it in Github Discussions, [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR's or feature requests are allowed. Minimal reproduction in codesandbox.io is required.

## Your Environment

os: mac/linux/windows/android/ios

node --version

react version

webpack version

@babel version

@react-google-maps/api version

**Comment by walien** [comment]
Hi, what was the solution to this issue ?

**Comment by lucasvst** [comment]
Just run `yarn upgrade @react-google-maps/api@^2.12.0` or another newer version.
