### ISSUE TITLE
Uncaught (in promise) TypeError: this.prototype.set is not a function for MarkerClusterer

### ISSUE THREAD

**Issue by pzanwar03** [JustFly1984/react-google-maps-api#3030]
I'm getting errors when I add MarkerClusterer. 

My code is:

<MarkerClusterer>

      {(clusterer) =>
        parcelsClusters &&
        parcelsClusters.map((location: any, i: number) => (
          <Marker
            key={i}
            position={location}
            animation={google.maps.Animation.DROP}
            clusterer={clusterer}
            visible={false}
          />
        ))
      }
    </MarkerClusterer>

My error is:
![image](https://user-images.githubusercontent.com/25006760/169648496-18fa0f97-b3f4-4c06-95c5-222e6f12c2fd.png)

**Comment by JustFly1984** [comment]
please use MarkerF instead of Marker

**Comment by pzanwar03** [comment]
This is the codesandbox.io URL:
https://codesandbox.io/s/react-google-map-api-p4jp60

**Comment by JustFly1984** [comment]
@pzanwar03 sorry for this error - my mistake.

I've released 2.11.8 - it works.

https://codesandbox.io/s/react-google-map-api-forked-xi9t3p?file=/src/App.tsx
