### ISSUE TITLE
React 18 OverlayView Flickering

### ISSUE THREAD

**Issue by Dastari** [JustFly1984/react-google-maps-api#3036]
When using the new **createRoot** render method in React 18 any components in the **OverlayView** will flicker and jump when panning the map. 

Additionally the OverlayView components will not render on initial render (causing a re-render will trigger them to show)

**@react-google-maps/api**:v2.11.9
**react**:18.0

Repo to demonstrate using **createRoot** (note you have to change the number of rendered dots for it to trigger a re-render):

[https://codesandbox.io/s/react-maps-api-overlay-v18-yqsfil](https://codesandbox.io/s/react-maps-api-overlay-v18-yqsfil?file=/src/App.js)

Repo showing it working when returning to the old v17 render method:

[https://codesandbox.io/s/react-maps-api-overlay-v17-4qt0pl](https://codesandbox.io/s/react-maps-api-overlay-v17-4qt0pl?file=/src/App.js)

**Comment by nicolasperalta-endava** [comment]
Hi, I have the same problem, have you fixed it? Its very annoying

**Comment by Dastari** [comment]
The problem appears to be caused by Automatic Batching. In the React v18 documentation it says that you can use **flushSync** to opt-out of Automatic Batching however I don't believe this is entirely correct as Automatic Batching still happens, you can just force a re-render when you want to.

I have attempted many variations of using **flushSync** using @sud977 approach in the **google-maps-react**  [thread](https://github.com/google-map-react/google-map-react/issues/1102#issuecomment-1116455460), however the same issue occurs.

**Comment by becerriljc** [comment]
Hi, I have the same problem too.

**Comment by asdutoit** [comment]
I am also having the same issue

**Comment by manelio** [comment]
Same problem here

**Comment by ShadiBlitz** [comment]
> 
> [https://codesandbox.io/s/react-maps-api-overlay-v17-4qt0pl](https://codesandbox.io/s/react-maps-api-overlay-v17-4qt0pl?file=/src/App.js)

@Dastari  how can I apply this workaround in next js ?

**Comment by JustFly1984** [comment]
use eslint with eslint plugins react react-hooks react-perf to reduce re-renders!

**Comment by ShadiBlitz** [comment]
@JustFly1984 What do you mean? Apparently there is an issue with react 18 and the overlayview is flickering!! We can't upgrade to react 18 because of this issue.

**Comment by SashaMihalache** [comment]
Same problem happening to me

**Comment by RayPaez83** [comment]
I'm having the same issue when dragEnd in react-google-maps, the pins  flickering, using the onDragEnd property you could set the lat and the lng again and recenter where you want to recenter the map.

**Comment by njho** [comment]
Same Issue!

**Comment by Owoscaw** [comment]
Still getting this issue

**Comment by QLeitz** [comment]
This is happening with me too. ~250 polygon features for countries on a world map and they all flicker every zoom in/out. I've confirmed this is not caused by re-renders of the map component by using the React profiler. Using react v18.2.0.

**Comment by lukas-hablitzel** [comment]
I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

**Comment by obsfx** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

This worked for me. Thanks a lot.

**Comment by JustFly1984** [comment]
We are slowly but surely implementing F versions of each component. You can look at the progress in CHANGELOG.md React@18 StrictMode doesn't work with old class based components.

**Comment by Alvarg27** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

Thanks!!! this also worked for me!!!

**Comment by jaikishan-gaxon** [comment]
Same problem happening to me...
but my problem solved... how ( reactStrictMode is false form next.config.js then problem solved...all maps r proper working)

**Comment by vonZ** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

Thanks, this worked fine for me!

**Comment by John-Daniels** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

Bro, you're a life saver, this solution was just what i needed, Thank you so much!

**Comment by JogiPrasadPakki** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

Thank you, your solution works

**Comment by EricWVGG** [comment]
This worked for me as well. The documentation ought to be updated to reflect it.

**Comment by thomastvedt** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

Thank you 🙏

**Comment by pravar-anu** [comment]
> This is happening with me too. ~250 polygon features for countries on a world map and they all flicker every zoom in/out. I've confirmed this is not caused by re-renders of the map component by using the React profiler. Using react v18.2.0.

@QLeitz  Did you find any solution ?

**Comment by JustFly1984** [comment]
Divide everything in smallest components, wrap all exports with memo, use useMemo and useCallback everywhere.

**Comment by ducthong1991** [comment]
There is the fix for this, just use patching the change for your code
https://github.com/google-map-react/google-map-react/pull/1224

**Comment by michael-alterio** [comment]
This also worked for me too! OverlayViewF 😊

**Comment by nguoingulanh** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

This worked for me, thanks you !!!

**Comment by surafel-99** [comment]
> I had the same problem when using the `OverlayView` component. However replacing it with `OverlayViewF`, which is also exported from `@react-google-maps/api` resolved the issue for me. Just thought this might help someone else too.

Thank you. This worked for me. But you still need to import OverlayView for the mapPaneName prop. 

```
import { OverlayView, OverlayViewF } from "@react-google-maps/api"

        <OverlayViewF
             position={{
                 lat: "",           // your latitude goes here
                 lng: "",          // your longitude goes here,
          }}
            mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}  // if you use OverlayViewF here, it won't work.
          >
            <div>
              <MarkerListingCard 
                item={selectedListing} 
                closeHandler={() => setSelectedListing(null)}
                />
            </div>

          </OverlayViewF>

```
