### ISSUE TITLE
API key Does NOT work with Safari

### ISSUE THREAD

**Issue by AJTJ** [JustFly1984/react-google-maps-api#3039]
using the api like this works perfectly with chrome:
```
  return (
    <MapPage style={{ height: "100vh", width: "100%" }}>
      <LogoSection logo={logo} />
      <LoadScript googleMapsApiKey="xxx">
        <GoogleMap
          mapContainerStyle={containerStyle}
          center={center}
          zoom={zoom}
        >
```
but in safari it does not recognize the api key.
![Screen Shot 2022-06-02 at 2 37 43 PM](https://user-images.githubusercontent.com/29932896/171742724-cd512640-6e97-4a10-af3d-fca6a05b99e2.png)

It appears that something is missing/broken with the api key injection for safari.
I’m noticing that your examples on the documentation website (https://react-google-maps-api-docs.netlify.app/) are also doing the same thing with safari. So, I don’t think this has anything to do with my implementation.

**Comment by AJTJ** [comment]
@dvislov yes billing is enabled
And it works fine in chrome.
It seems like Safari might not be getting the api key? Since it is telling me to enable billing
![Screen Shot 2022-07-05 at 1 33 47 AM](https://user-images.githubusercontent.com/29932896/177286217-28a686d7-50eb-42c9-aa8b-732b6dd547f4.png)

But billing is enabled and it works in chrome. Only safari is giving me that error.

**Comment by AJTJ** [comment]
@dvislov you can see it here: https://yukonliteracy.com/little-libraries/#/

**Comment by dvislov** [comment]
@AJTJ Could you please open this simple "Hello World" html example from the Google Maps docs with your key in both browsers?

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    #map {
      height: 100%;
    }
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
  </style>
</head>
<body>
  <div id="map"></div>
  <script>
    let map;

    function initMap() {
      map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: -34.397, lng: 150.644 },
        zoom: 8,
      });
    }

    window.initMap = initMap;
  </script>
  <script
  src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap&v=weekly"
  defer
></script>
</body>
</html>
```

Because I have similar issue, but the API key is provided by the client and I have no any access to its settings.
The map is working in the Brave browser, neither in Chrome nor Safari.

I've found another option to load google maps instance https://developers.google.com/maps/documentation/javascript/overview#js_api_loader_package Did you try it?

**Comment by AJTJ** [comment]
@dvislov I tried your example. It works in chrome but it does NOT work in Safari.

This is really interesting, and makes me wonder what the problem is.
Safari is giving me the same error


<img width="1062" alt="Screen Shot 2022-07-05 at 1 59 20 AM" src="https://user-images.githubusercontent.com/29932896/177291152-e4c68318-5375-4a93-8a30-7e679733ac3a.png">
.

**Comment by AJTJ** [comment]
I tried using the `loader.load().then(...` method, and it didn't make a difference

**Comment by JustFly1984** [comment]
All I see in safari logs is errors from google itself, not from our library.

**Comment by JustFly1984** [comment]
can you try to make new google cloud account and test with fresh key?

**Comment by JustFly1984** [comment]
did you try to use useLoadScript hook instead of LoadScript component?

**Comment by AJTJ** [comment]
@JustFly1984 yes, so I just tried rewriting my map component using the `useLoadScript` but I'm still getting the "development purposes only" while in Safari.
<img width="1777" alt="Screen Shot 2022-07-24 at 9 49 17 PM" src="https://user-images.githubusercontent.com/29932896/180700761-ad1f4526-2fe4-420d-b2a5-1c67b1376d26.png">

You can see it live here: https://yukonliteracy.com/little-libraries/#/
(where it will NOT work in safari, but it does work in chrome)

You can see my code here: https://github.com/Yukon-Literacy-Coalition/ylc_website_v2/blob/master/src/LittleLibraries/index.jsx#L157

**Comment by AJTJ** [comment]
@dvislov did you ever solve this problem so that it works in every browser? And on mobile?

**Comment by dvislov** [comment]
@AJTJ Yes, we've checked the billing for the modules we need (places, drawing, etc.) For now everything works fine in Chrome/Safari.

**Comment by AJTJ** [comment]
@dvislov what was the problem for you? Did you need to set up billing differently so that it worked in different browsers?

**Comment by dvislov** [comment]
@AJTJ Actually I don't know, it just started working one day. So, the issue depended on some API key settings I suppose

**Comment by miladebadi** [comment]
I also have this issue, I tried more than 5 different api keys and still it doesn't work in safari! please let me know if you find a way to resolve it

**Comment by AJTJ** [comment]
Well, as stupid as it was, the issue was that our google maps api service wasn't fully configured and purchased. I still don't know why it was working in some situations, but not others.

That being said, make sure you've purchased and configured your google maps api key.
