### ISSUE TITLE
Markers dissapear after refresh

### ISSUE THREAD

**Issue by SimeriaIonut** [JustFly1984/react-google-maps-api#3048]
## Your Environment

os: MacOS

node --version: v14.19.3

react version: 18.1.0

webpack version: N/A

@babel version: N/A

@react-google-maps/api version: 2.12.0

## How does it behave?
The marker dissapears after page refresh.

## How should it behave correctly?
The marker should not dissapear after page refresh

## Basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/react-google-maps-api-issue-7meur1

**Comment by JustFly1984** [comment]
@SimeriaIonut import MarkerF instead of Marker

**Comment by SimeriaIonut** [comment]
Thanks, will do. Is there a reason for using MarkerF instead of Marker?

**Comment by JustFly1984** [comment]
yes. MarkerF is functional component vs class based Marker component, which does not work with react Strict and/or react@17+

**Comment by toddjudd** [comment]
Looks like MarkerClusterer has the same issue, but is not solved by using the MarkerClustererF version.

**Comment by HelloAyan** [comment]
I also faced the same issue.  After using MarkerF component instead of Marker component it's working on my web application.

**Comment by YohannesTz** [comment]
thank you. you have saved me hours!

**Comment by salorsino** [comment]
This took me a few hours to find, but this is the correct answer. 

I had a project with a sample repo that was using Next 12 and React 17, then I went to create my own project using `npx create-next-app` and that creates it with Next 13 and React 18, and then I began seeing the Marker issue. 

Removing `reactStrictMode: true` from `next.config.js` and using `MarkerF` and `MarkerClusterF` solved my issues

**Comment by nkechr1s** [comment]
I was trying to the days to fix that issue, thank you!

**Comment by ezejerez** [comment]
Hi, I'm facing the same issue and using <MarkerF /> I've solved it, but the problem is that <MarkerF /> is a memoized Component, so if I try to use the "icon" prop in order to use a custom Marker icon and I want to dinamically change it's fillColor, the memoized component (MarkerF) does not work as expected. The same example works just fine using <Marker />, but refresing the page all the markers disappear.

**Comment by SirBob01** [comment]
Hello, I'm facing the same issue as @ezejerez. the MarkerF component no longer rerenders when I change the properties of the 'icon' prop. Is there a fix for this?

**Comment by EliseiNicolae** [comment]
I've the same problem. I tried using MarkerF and MarkerClustererF, but is not working - after a few refreshes / hard refresh I can't see the markers.

This is happening just in dev mode, In production mode I can't reproduce.

**Comment by hamzapaskingakhtar1999** [comment]
> This took me a few hours to find, but this is the correct answer.
> 
> I had a project with a sample repo that was using Next 12 and React 17, then I went to create my own project using `npx create-next-app` and that creates it with Next 13 and React 18, and then I began seeing the Marker issue.
> 
> Removing `reactStrictMode: true` from `next.config.js` and using `MarkerF` and `MarkerClusterF` solved my issues

I really don't understand the reason behind removing reactStrictMode but it worked. The map shows even after refresh.
