### ISSUE TITLE
React 18 not render

### ISSUE THREAD

**Issue by becerriljc** [JustFly1984/react-google-maps-api#3051]
When using the new createRoot render method in React 18 any components in the OverlayView will flicker and jump when panning the map.

Additionally the OverlayView components will not render on initial render (causing a re-render will trigger them to show)

@react-google-maps/api:v2.12.0
react:18.2.0

Repo to demonstrate using createRoot (note you have to change the number of rendered dots for it to trigger a re-render):

[https://codesandbox.io/s/react-maps-api-overlay-v18-yqsfil](https://codesandbox.io/s/react-maps-api-overlay-v18-yqsfil?file=/src/App.js)

Repo showing it working when returning to the old v17 render method:

[https://codesandbox.io/s/react-maps-api-overlay-v17-4qt0pl](https://codesandbox.io/s/react-maps-api-overlay-v17-4qt0pl?file=/src/App.js)

#Bug

**Comment by asdutoit** [comment]
Hi @becerriljc, I have the same issue.   
As a temporary fix, I used CSS to reposition the OverlayView component. 

```js
<OverlayView
  position={position}
  mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
>
  <div className="shadow-3xl rounded-lg relative flex flex-col bg-purple-100 p-2 border-2 border-purple-400 -left-1/2 -top-[72px]">
       <p>Hello World</p>
  </div>
</OverlayView>
```
Note sure if this could assist you. 

Hopefully, they can implement a solution to this issue.

**Comment by mariomeraz** [comment]
I have the same issue.

18.1.0

but it doesn't show me the circle, nor the marker and sometimes it works

**Comment by becerriljc** [comment]
Try with @react-google-maps/api v2.12.1
