### ISSUE TITLE
How to disable the tilt control?

### ISSUE THREAD

**Issue by mmarienko** [JustFly1984/react-google-maps-api#3072]
Hi there, how to disable the tilt control? I didn't find the on\off setting in @react-google-maps/api library, only the number setting for zoom level

<img width="292" alt="Screenshot 2022-07-27 at 17 50 51" src="https://user-images.githubusercontent.com/64919508/181278926-10de7bd7-b558-4f47-98e3-ae99fef4c500.png">

<img width="526" alt="Screenshot 2022-07-27 at 17 54 23" src="https://user-images.githubusercontent.com/64919508/181279693-e43f2cfd-5744-4524-83d4-d881e273128e.png">
<img width="526" alt="Screenshot 2022-07-27 at 17 55 11" src="https://user-images.githubusercontent.com/64919508/181279710-d55b3f0c-2ba4-4ff4-b391-cdc1597905c1.png">

Also, I cannot disable it by styling 'cause the button wrapper didn't have a specific class

**Comment by JoshSinghEscreen** [comment]
I turned it off by passing `tilt: 0` in the options

**Comment by mmarienko** [comment]
> I turned it off by passing `tilt: 0` in the options

You are my savior, thanks
