### ISSUE TITLE
MarkerClusterer typescript error with Element[]

### ISSUE THREAD

**Issue by luan-dang-techlabs** [JustFly1984/react-google-maps-api#3101]
I am getting this error with typescript, here is the documentation:  https://react-google-maps-api-docs.netlify.app/#markerclusterer for 'MarkerClusterer'.  Is this an error with the type declaration?

<img width="1054" alt="Screen Shot 2022-09-13 at 5 25 25 PM" src="https://user-images.githubusercontent.com/91907117/190032230-2954d868-eda1-4d93-b2ce-19fd89f2d6bd.png">

<img width="800" alt="Screen Shot 2022-09-13 at 5 25 44 PM" src="https://user-images.githubusercontent.com/91907117/190032247-68b672e8-bcc1-458d-95eb-513a53ea4185.png">

Type Declaration:

<img width="978" alt="Screen Shot 2022-09-13 at 5 16 51 PM" src="https://user-images.githubusercontent.com/91907117/190031468-c84026d1-b3d8-44f3-b5e9-060e0ede7f1b.png">

**Comment by rackdon** [comment]
The problem is that MarkerClusterer is expecting a single element and you're returning an array of elements. It can be solved grouping everything inside a Fragment:
```
<MarkerClusterer>{(cluster) => {
   return <Fragment>{stores.map....}</Fragment>
}</MarkerClusterer>
```

**Comment by luan-dang-techlabs** [comment]
@rackdon - thanks a lot that was it.
