### ISSUE TITLE
Polygons vertices not clickable or movable

### ISSUE THREAD

**Issue by memee** [JustFly1984/react-google-maps-api#3104]
## Please provide an explanation of the issue

When using `<DrawingManager>` like that:

```
<DrawingManager
  options={{
    drawingControl: false,
    polygonOptions: {
      clickable: true, // <− here
      editable: true, // <− and here
      draggable: true, // <− and here
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.1,
    },
  }}
  drawingMode={google.maps.drawing.OverlayType.POLYGON}
/>
```

-> then polygon **vertices** are **not clickable or movable**

## Your Environment

os: mac

node --version
v16.6.1

react version
^17.0.2

webpack version
^5.68.0

@babel version
"@babel/core": "^7.16.12",

@react-google-maps/api version
^2.7.0

## How does it behave?
It does not allow for clicking or moving vertices

## How should it behave correctly?
I should be able to move vertex after I set up appropriate polygon options

## Basic implementation of incorrect behavior in codesandbox.com
https://stackblitz.com/edit/react-yz5ov5?file=MyMapComponent.js,index.js,package.json

**Comment by JustFly1984** [comment]
try PolygonF instead

**Comment by memee** [comment]
Sorry my bad. I needed to again set `drawingMode={null}` to reenable clicking.
