### ISSUE TITLE
renderMap Being Executed Multiples Times 

### ISSUE THREAD

**Issue by lnorton89** [JustFly1984/react-google-maps-api#311]
## Your Environment

os: Windows 10

node v12.13.1

react 16.12.0

webpack latest cra

@babel latest cra

@react-google-maps/api 1.7.14

## How is it behave?
renderMap() fires 4 times before the page is actually done loading. 

## How should it behave correctly?
renderMap() should only fire when the page is loaded and 'google' / mapRef is available.

This is the example I'm working from: https://codesandbox.io/s/react-google-maps-api-ir5ks

If you update the packages to their latest versions you can see the error if you uncomment line 89: https://codesandbox.io/s/react-google-maps-api-hiu6m

After bringing into my project it would not work without commenting out `onCenterChanged={() => setCenter(mapRef.getCenter().toJSON())}` as mapRef is not available when the map is rendered as the page isn't fully loaded. 

Stripped down example still has renderMap being fired twice. once before the mapRef is defined and once after. 

```javascript
import React from 'react';
import { GoogleMap, useLoadScript } from '@react-google-maps/api';
import { Grid, Paper } from '@material-ui/core';
import Preloader from '../Preloader';

const data = require('../../data.json');

export default function Map() {
  const [mapRef, setMapRef] = React.useState(null);

  // Iterate data to size, center, and zoom map to contain all markers
  const fitBounds = map => {
    const bounds = new window.google.maps.LatLngBounds();
    data.map(place => {
      bounds.extend({ lat: place.lat, lng: place.lng });
      return place.id;
    });
    map.fitBounds(bounds);
  };

  const loadHandler = map => {
    // Store a reference to the google map instance in state
    setMapRef(map);
    // Fit map bounds to contain all markers
    fitBounds(map);
  };

  const { isLoaded, loadError } = useLoadScript({
    googleMapsApiKey: '<MY_KEY>'
  });

  const renderMap = () => (
    <Grid container spacing={3}>
      <Grid item xs={12} md={8} lg={9}>
        <Paper>
          <GoogleMap
            onLoad={loadHandler}
            id="example-map"
            mapContainerStyle={{
              height: '500px',
              width: '100%'
            }}
          ></GoogleMap>
        </Paper>
      </Grid>
    </Grid>
  );

  if (loadError) {
    console.log('loaderror');
    return <div>Map cannot be loaded right now, sorry.</div>;
  }

  if (isLoaded) {
    console.log(
      `we are now rendering the map. here is its reference stored as useState: ${mapRef}`
    );
    return renderMap();
  }

  return <Preloader />;
}
```

**Comment by JustFly1984** [comment]
Never pass object as props to  Components as you pass mapContainerStyle prop

it is recreated on each state change. save it to const outside of component scope.

You need to pass center prop - it is required.

**Comment by lnorton89** [comment]
In my full code I have a center prop. Moving the mapContainerStyle to a const outside of component scope has no change on this issue.

**Comment by JustFly1984** [comment]
@lnorton89 
get rid of renderMap function and return JSX directly. Also you can use https://github.com/welldone-software/why-did-you-render to detect issues. please use eslint-plugin-react-perf to avoid common performance mistakes

**Comment by lnorton89** [comment]
This doesn't really solve the problem -- the 'google' variable is not available when the component tries to render--this is why `renderMap()` was used.

**Comment by JustFly1984** [comment]
well, you need to extract renderMap to separate component and pass required props. use eslint with react-perf plugin. also would recommend react-hooks plugin. Just do not render components with google object until script is initialized. pretty much all rules applied to SSR should be applied to google maps.
