### ISSUE TITLE
the latest version 2.13 included a breaking change for OverlayView

### ISSUE THREAD

**Issue by dogofpavlov** [JustFly1984/react-google-maps-api#3114]
Using the latest 2.13 version it included a change that made the "position" property of "OverlayViewProps" required. Previously this property was optional.  I am using the OverlayView by passing only a "bounds" property of LatLngBounds. Is it a new requirement to also pass the position? I could get the center of the bounds and use that but I'm not sure what other effects this would have.

**Comment by fireboltfrog** [comment]
If this is not a bug, the position property should also be labeled as required in the documentation.

**Comment by fireboltfrog** [comment]
Definitely looks like a bug to me. 

@dogofpavlov did you manage the OverlayView to consider the bounds property as expected?

**Comment by JustFly1984** [comment]
@fireboltfrog @dogofpavlov  you PR is welcome

**Comment by joshuapaling** [comment]
Looks like this is the line that did it: https://github.com/JustFly1984/react-google-maps-api/pull/3106/files#diff-12da235eb26b2571f4bc4a5a0b1686d9c1462b454f6b297afb910572a41bd5f3R73
