### ISSUE TITLE
Basic example does not seem to work

### ISSUE THREAD

**Issue by Nargonath** [JustFly1984/react-google-maps-api#315]
# Please provide an explanation
I'm trying to make a plain map display in a pristine create-react-app project but it doesn't seem to be working. I used the example from the documentation. The key I used works because when using it with Google's example code from their documentation the map displays properly.

Thanks for your help.

## Your Environment

os: mac

node --version
10.15
react version
16.8.6
webpack version
4.29.6
@babel version

@react-google-maps/api version
1.7.14
## How is it behave?
The map is not displayed and only an empty page is shown.
## How should it behave correctly?
The map should be displayed.
## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/react-reohj?fontsize=14&hidenavigation=1&theme=dark

**Comment by JustFly1984** [comment]
@Nargonath 
In code sandbox you don't have to provide a key.

This is working fork of your example: https://codesandbox.io/s/react-google-maps-repro-5yn2g

**Comment by Nargonath** [comment]
Alright, my bad. This was definitely a silly problem on my part. Thanks for your help.
