### ISSUE TITLE
How to add debounce in AutoComplete

### ISSUE THREAD

**Issue by Risyandi** [JustFly1984/react-google-maps-api#3169]
how to add debounce at best places (onload, onPlaceChanged, or etc) in Autocomplete using this function for example debounce. 

```javascript
function debounce(func, timeout = 300) {
  let timer;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      func.apply(this, args);
    }, timeout);
  };
}
```

### Environment

os: windows

react version : 16.13.1

@react-google-maps/api version : 1.8.9

**Comment by JustFly1984** [comment]
you should wrap the function you pass into useCallback.

```
{
const debouncedOnClick = useCallback(debounce(() => { /* your code goes here */ }, 400), [/* do not forget to set dependencies for your code*/])

...
}
```

**Comment by Risyandi** [comment]
Hi, @JustFly1984 Thank you for your response, I will try the solution. hopefully will be working fine.
