### ISSUE TITLE
StandaloneSearchBox not working in Modal

### ISSUE THREAD

**Issue by stesvis** [JustFly1984/react-google-maps-api#3171]
Hello,

I am using the `StandaloneSearchBox` successfully in my pages.
However it doesn't seem to work when I load it inside a [Modal](https://react-bootstrap.github.io/components/modal/).

When I type in the box it won't show me the popup with the list of matches.
Or most likely it's showing behind the modal.
https://codesandbox.io/s/react-bootstrap-5-forked-9o3xnb?file=/src/App.js

How can we get it to work in a Modal?

**Comment by stesvis** [comment]
Fixed with
```css
.pac-container {
    z-index: 10000 !important;
}
```

**Comment by ROD-MASAMI** [comment]
where did you write that in the global.css its not working for me i can see the popup but i can't click them

**Comment by devavikalabs** [comment]
yes not working me
