### ISSUE TITLE
MarkerClusterer adds one more number to the marker count

### ISSUE THREAD

**Issue by pedrolaxe** [JustFly1984/react-google-maps-api#3173]
## MarkerClusterer adds one more number to the marker count

Hi, I implemented the MarkerClusterer in my code and realized that whenever I click on the MarkerClusterer it adds another number to the marker count

## Your Environment

os: windows 10 Pro x64
node 14.17.0
react 18.2.0
@react-google-maps/api 2.17.1

### Before Click - Count 4
![](https://laxe.dev/before.png "before click")

### After Click - Only 3 - Correct
![](https://laxe.dev/depois.png "afterclick")

**Comment by JustFly1984** [comment]
try use MarkerClustererF instead

**Comment by pedrolaxe** [comment]
I use MarkerClustererF  and MarkerF but not fix

I include with
```
import { GoogleMap, useJsApiLoader, Marker, MarkerF, MarkerClustererF } from '@react-google-maps/api';
```
![](https://laxe.dev/marker.png "code")

**Comment by pedrolaxe** [comment]
Thanks for support, i found 2 markers in same lat and lng.
