### ISSUE TITLE
Draw a marker in center of a polygon?

### ISSUE THREAD

**Issue by web-programmer-here** [JustFly1984/react-google-maps-api#3184]
I am using `PolygonF` to draw bunch of polygons

```
<PolygonF onLoad={onLoad} paths={paths} options={options} />
```

I want to show a marker in the center of each polygon, is that possible?

**Comment by Yrll21** [comment]
What polygons are you trying to make? Is it just basic shapes? Or a complex one? You need first to calculate the center to be able to create a marker on the center.

**Comment by web-programmer-here** [comment]
we can close this issue, I decided not to do this.
