### ISSUE TITLE
Docs page is not working

### ISSUE THREAD

**Issue by aliMurtaja** [JustFly1984/react-google-maps-api#3273]
When I am visiting the main docs page `https://react-google-maps-api-docs.netlify.app/`, it is not working the way it should work.

I am getting the popup as I showed below.

![image](https://github.com/JustFly1984/react-google-maps-api/assets/49111180/91ea4406-9443-4780-b6df-00371a768191)

**Comment by JustFly1984** [comment]
Docs build is broken.
