### ISSUE TITLE
Problem with autocomplete 

### ISSUE THREAD

**Issue by Hropotova** [JustFly1984/react-google-maps-api#3280]
everything was fine with autocomplete for about a year, but yesterday this error appeared and I don't understand why I have it problem

© > Uncaught TypeError: Cannot read properties of undefined (reading
'location')

![IMG_4153](https://github.com/JustFly1984/react-google-maps-api/assets/68398910/16908614-b869-4fa7-a797-25a77e41202a)
![IMG_4154](https://github.com/JustFly1984/react-google-maps-api/assets/68398910/1263eea9-bc16-469f-bc3d-a2027f38f958)
![IMG_4155](https://github.com/JustFly1984/react-google-maps-api/assets/68398910/36cdbf00-6e41-4490-a376-316724cf866d)

**Comment by clelantoson** [comment]
Probably you need to check that place and geometry are defined 

on my side I have no issue and it's typed like this 
```
  const onDepartureAutocompletePlaceChanged = () => {
    setDepartureCoordinates(autocompleteDepartureRef.current?.getPlace()?.geometry?.location)
  }
```
