### ISSUE TITLE
Two tooltips/dailog when clicking on marker

### ISSUE THREAD

**Issue by ahsaanshuja** [JustFly1984/react-google-maps-api#3286]
when I click on marker it shows two tooltips/dailog I am using `"@react-google-maps/api": "^2.19.2"` in Next js typescript 

my code is:

`  import {
  GoogleMap,
  InfoWindow,
  LoadScript,
  MarkerF,
  Marker,
} from '@react-google-maps/api';
import { FC, useState } from 'react';
const containerStyle = {
  width: '100%',
  height: '500px',
};

const markers = [
  {
    id: 1,
    name: 'Chicago, Illinois',
    position: { lat: 41.881832, lng: -87.623177 },
  },
  {
    id: 2,
    name: 'Denver, Colorado',
    position: { lat: 39.739235, lng: -104.99025 },
  },
  {
    id: 3,
    name: 'Los Angeles, California',
    position: { lat: 34.052235, lng: -118.243683 },
  },
  {
    id: 4,
    name: 'New York, New York',
    position: { lat: 40.712776, lng: -74.005974 },
  },
];
const MapComponent: FC = () => {
  const [activeMarker, setActiveMarker] = useState<number>();
  const handleActiveMarker = (marker: number) => {
    if (marker === activeMarker) {
      return undefined;
    }
    setActiveMarker(marker);
  };
  const handleOnLoad = (map: google.maps.Map) => {
    const bounds = new google.maps.LatLngBounds();
    markers.forEach(({ position }) => bounds.extend(position));
    map.fitBounds(bounds);
  };

  return (
    <LoadScript googleMapsApiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY!}>
      <GoogleMap
        onLoad={handleOnLoad}
        mapContainerStyle={containerStyle}
        zoom={10}
      >
        {markers.map(({ id, name, position }) => (
          <MarkerF
            key={id}
            position={position}
            onClick={() => handleActiveMarker(id)}
          >
            {activeMarker === id ? (
              <InfoWindow
                onCloseClick={() => setActiveMarker(undefined)}
              >
                <div key={id}>{name}</div>
              </InfoWindow>
            ) : null}
          </MarkerF>
        ))}
      </GoogleMap>
    </LoadScript>
  );
};

export default MapComponent `

Here is the image of this issue

<img width="1063" alt="Screenshot 2023-09-07 at 12 05 15 AM" src="https://github.com/JustFly1984/react-google-maps-api/assets/59344804/cb79c1b4-947a-4be8-8ec3-74bf3a026378">

**Comment by DavidArutiunian** [comment]
Try to remove `<React.StrictMode>` around your app component

**Comment by vojtech-cerveny** [comment]
^^ Same issue with NextJS, StrictMode off doesn't fork

**Comment by impartdan** [comment]
I have the same problem. Any idea what could be causing this?

**Comment by ahsaanshuja** [comment]
Solution https://stackoverflow.com/a/77055881/13492516
