### ISSUE TITLE
Use Map only as a display. Prevent all user inputs

### ISSUE THREAD

**Issue by risingwolf21** [JustFly1984/react-google-maps-api#3296]
Is it possible to disable all user inputs and options in the map?
I just want to show a plain google map part with one marker in the middle of it.
The user should not be able to zoom in/out, change the appearance type or move within the app. (On mobile with two fingers moving the map)

I can turn everything off except the moving part.
Is there a mode or something to have the map as a readonly or view only?

**Comment by erikzylstra** [comment]
Check out the [Google Maps Static API](https://developers.google.com/maps/documentation/maps-static/overview)
