### ISSUE TITLE
Can't use StandaloneSearchBox

### ISSUE THREAD

**Issue by annapopova1** [JustFly1984/react-google-maps-api#33]
Hi all.
I want to migrate code from react-google-maps to the newest react-google-maps-api (1.0.8) but can't do it because can't replace StandaloneSearchBox usage.
My code is:
```
import StandaloneSearchBox from 'react-google-maps-api/lib/components/places/StandaloneSearchBox';

...

          <StandaloneSearchBox
            ref={this.onSearchBoxMounted}
            onPlacesChanged={this.onPlacesChanged}
          >
            <input
              name="location"
              placeholder="Enter a location"
              value={locationInput}
              onChange={this.updateLocationInputState}
              className="location-input"
            />
          </StandaloneSearchBox>
```

With this code I got the exception like this:
```
StandaloneSearchBox.js:64 Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at StandaloneSearchBox.componentDidMount (StandaloneSearchBox.js:64)
    at commitLifeCycles (react-dom.development.js:16227)
    at commitAllLifeCycles (react-dom.development.js:17592)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:17788)
    at completeRoot (react-dom.development.js:19240)
    at performWorkOnRoot (react-dom.development.js:19169)
    at performWork (react-dom.development.js:19077)
```

How can I use StandaloneSearchBox? Or there is a real issue for it?

**Comment by uriklar** [comment]
Hi Anna, 
I'm looking over the code for StandaloneSearchBox and i see that it indeed misses some implementation.
There should be some kind of containerElement.

If you'd like to try and fix the component i'd be happy to guide you to the right direction. 
The solution might look something like this.
Add to StandaloneSearchBox:
```
render = () => {
  return (
   <div ref={ref => this.containerElement = ref} />
       {this.props.children}
   </div>
 )
}
```

And then where ever it says this.props.containerElement, change it to this.containerElement.
I'm just guessing though... Don't have the time to try it out right now, but again, if you need guidance to create a PR yourself, talk to me and it would be very welcome

**Comment by annapopova1** [comment]
Hi Uri, thank you for the response. But unfortunately, I don't have time to contribute and fix it.

**Comment by JustFly1984** [comment]
@annapopova1 there is new @react-google-maps/api@1.0.8 version with StandaloneSearchBox included. please update. https://react-google-maps-api-docs.netlify.com/src-standalone-search-box
https://react-google-maps-api-gatsby-demo.netlify.com
