### ISSUE TITLE
This page can't load Google Maps correctly. For developmental purposes only.

### ISSUE THREAD

**Issue by spietrek-insight** [JustFly1984/react-google-maps-api#3335]
## Please provide an explanation of the issue

Today, Google Maps has started displaying "This page can't load Google Maps correctly. For developmental purposes only.". We did not have this issue a few days ago. I am seeing this error running locally as well. I am also seeing the following error which I haven't noticed until today.

Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading

## Your Environment

Next.JS deployed to Vercel

os: mac/linux/windows/android/ios

node --version 18

react version 18.2

webpack version

@babel version

@react-google-maps/api version 2.19.2

**Comment by spyshower** [comment]
@spietrek-insight what was the problem?
