### ISSUE TITLE
21st, 2024, google.maps.Marker is deprecated.

### ISSUE THREAD

**Issue by Eng1Mahmoud** [JustFly1984/react-google-maps-api#3343]
# 21st, 2024, google.maps.Marker is deprecated.

 As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement.

i can not find AdvancedMarkerElement ,how i can use it ,

**Comment by JustFly1984** [comment]
@Eng1Mahmoud  You have to create it, or wait for somebody else creating it and providing PR. This is opensource.
If you really need it, but can't do it yourself, I'm open for donations crowdfunding. After I get 500$ in donations, I can find the time to implement it.

**Comment by christopherboisvert** [comment]
@JustFly1984 Thanks for the support you have given this repository.

**Comment by russmenum** [comment]
> @Eng1Mahmoud You have to create it, or wait for somebody else creating it and providing PR. This is opensource. If you really need it, but can't do it yourself, I'm open for donations crowdfunding. After I get 500$ in donations, I can find the time to implement it.

MIght want to provide a patron, gofund, or something if it is a bounty feature ... just so people know if it is or is not funded

**Comment by JustFly1984** [comment]
If It got founded, I would say about it.

**Comment by SweydManaf** [comment]
Also wanted, my api is being exposed

**Comment by camilova** [comment]
I appreciate the support and that you letting us use this package @JustFly1984 
For anyone looking for an alternative or upgraded package to integrate React with Google Maps, there is a package [Visgl React Google Maps](https://github.com/visgl/react-google-maps) that as they say, is [sponsored by Google itself](https://mapsplatform.google.com/resources/blog/introducing-react-components-for-the-maps-javascript-api/).

**Comment by Eng1Mahmoud** [comment]
@camilova yes i started use it from few month ago
