### ISSUE TITLE
documentation website become gambling ads

### ISSUE THREAD

**Issue by bagusindrayana** [JustFly1984/react-google-maps-api#3345]
documentation website (https://react-google-maps-api-docs.netlify.app) becomes an Indonesian gambling ads page
![image](https://github.com/JustFly1984/react-google-maps-api/assets/36830534/0e7aa3f6-7ce8-498d-9b28-9e6020014f7c)

**Comment by JustFly1984** [comment]
It is fixed by netlify team. That was a cyber-squatt attempt.
