### ISSUE TITLE
README netlify link is showing  scam games

### ISSUE THREAD

**Issue by vogdev** [JustFly1984/react-google-maps-api#3346]
this link is in the README
https://react-google-maps-api-docs.netlify.app

<img width="1190" alt="Screenshot 2024-03-25 at 10 32 07" src="https://github.com/JustFly1984/react-google-maps-api/assets/20149487/0a2a7660-c006-4dc4-9170-542d548afdb6">

**Comment by JustFly1984** [comment]
Thank you @vogdev  , the scam website is down, thanks to netlify froud prevention team

**Comment by vogdev** [comment]
@JustFly1984 the docs link is dead agin https://react-google-maps-api-docs.netlify.app
