### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by alamenai** [JustFly1984/react-google-maps-api#3396]
![image](https://github.com/user-attachments/assets/0bf339e2-8709-4ce3-8c13-d145cc2980e7)

**Comment by KatuGT** [comment]
the same happend in march  [#3344](https://github.com/JustFly1984/react-google-maps-api/issues/3344)

there the owner left some recomendations

**Comment by abuzain432432** [comment]
i am getting the issue. where to find the docs?

**Comment by JustFly1984** [comment]
in github repository /packages/react-google-maps-api/
