### ISSUE TITLE
@react-google-maps/api it is not compatible with React@19

### ISSUE THREAD

**Issue by serialgit** [JustFly1984/react-google-maps-api#3397]
Environment
mac

node  20.14.4

react version: React@19

Vitejs version: 6.0.5

@react-google-maps/api version: 2.20.3

Updating from React@18 to React@19 the operation is not successful because @react-google-maps/api is not compatible.
Is there any news on when it will be?

**Comment by JustFly1984** [comment]
What exactly is incompatible? Do you have any runtime errors?

**Comment by nomadical** [comment]
> What exactly is incompatible? Do you have any runtime errors?

`npm error Could not resolve dependency:npm error peer react@"^16.8 || ^17 || ^18" from @react-google-maps/api@2.20.3`
Seems like the latest version does not yet include the [PR]( https://github.com/JustFly1984/react-google-maps-api/pull/3389) fixing the issue.

**Comment by JustFly1984** [comment]
released 2.20.4, please check

**Comment by cbetancourt** [comment]
That fixed it. Thank you!

**Comment by serialgit** [comment]
Thank you!

**Comment by Bellow18** [comment]
After a lengthy quest, I found the answer I was looking for



https://database-relations.github.io/JMAYM8yhqhO4zX9hjDfYOdhweGxyEuUJ7E/
