### ISSUE TITLE
documentation does not show all components

### ISSUE THREAD

**Issue by AndyOGo** [JustFly1984/react-google-maps-api#34]
Missing `<Marker>`, etc. at

https://react-google-maps-api.netlify.com/

**Comment by uriklar** [comment]
Hi @AndyOGo, if you'd like to contribute, adding to the documentation is an easy win!
You have plenty of existing examples to copy from. 
We'd love your contribution.

**Comment by JustFly1984** [comment]
@AndyOGo we do not have sponsors, and all of us working on this project for using it in our own or company websites. Maintainers, contributors, new examples and documentation are welcome.

**Comment by AndyOGo** [comment]
@JustFly1984 
Thanks for your answer.
Sure, I can imagine this.
As I said I really appreciate your voluntary effort 👍 

It's just not that easy to start contributing.

**Comment by JustFly1984** [comment]
@AndyOGo You can run `react-google-maps-api-gatsby-example`, and add examples as you need. There is a plenty examples already.

**Comment by JustFly1984** [comment]
I've updated documentation: 
https://react-google-maps-api-gatsby-demo.netlify.com/
https://react-google-maps-api-docs.netlify.com/

**Comment by AndyOGo** [comment]
@JustFly1984 
Thanks for your help.

May I missunderstood the purpose of the docs.
I assumed to have explanations of the api complementary to examples, also I saw storybook, and it has awesome knobs feature and describing stories.

Whats is your plan regarding the docs, just examples or a more story based approach?

**Comment by JustFly1984** [comment]
@AndyOGo 
I have a plan to make @react-google-maps/create-react-app-example pretty much copying @react-google-maps/gatsby-example

Also I'm pretty sure we need to add jest tests. I think we need end-to-end tests, cos unit tests are useless without DOM

**Comment by JustFly1984** [comment]
@uriklar ^

**Comment by JustFly1984** [comment]
I can add jest to gatsby example in separate branch `jest` and we can start to add tests.
