### ISSUE TITLE
drawingmanager add maker change points

### ISSUE THREAD

**Issue by Angelk90** [JustFly1984/react-google-maps-api#361]
## Please provide an explanation

I would like to be able to do such a thing and shifting the points of the marker change the area of the drawing manager and the main points accordingly.

I am using DrawingManager to create area, but I can't set the main points as a maker and make way for moving the points without problems.

Can you give me a hand?

![](https://i.stack.imgur.com/EiiLj.png)

## Your Environment

os: linux

node: v13.5.0

react 16.12.0

webpack latest cra

@babel latest cra

@react-google-maps/api 1.8.1

## Code
```
<GoogleMap
ref={this.onMapMounted}
defaultZoom={this.props.defaultZoom}
defaultCenter={this.props.defaultCenter}
loadingElement={
  this.props.loadingElement || <div style={{ height: '100%' }} />
}
containerElement={
  this.props.containerElement || <div style={{ height: '400px' }} />
}
mapElement={this.props.mapElement || <div style={{ height: '100%' }} />}
onBoundsChanged={this.onBoundsChanged}
center={this.props.center}
onClick={this.props.onClick}
>
{this.props.marker}
{this.props.drawing &&
<DrawingManager
  defaultDrawingMode={google.maps.drawing.OverlayType.POLYGON}
  onPolygonComplete={poly => {
    return this.props.onPolygonComplete(poly)
  }}
  //getDrawingMode={() => console.log("a")}
  defaultOptions={{
    drawingControl: true,
    drawingControlOptions: {
      position: google.maps.ControlPosition.TOP_CENTER,
      drawingModes: [
        google.maps.drawing.OverlayType.POLYGON,
      ],
    },
    markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
    polygonOptions: {
      fillColor: `#2196F3`,
      strokeColor: `#2196F3`,
      fillOpacity: 0.5,
      strokeWeight: 2,
      clickable: true,
      editable: true,
      draggable: true,
      zIndex: 1,
    },
  }}
/>}
</GoogleMap>
```

**Comment by JustFly1984** [comment]
You are using outdated documentation from `react-google-maps`

our package is `@react-google-maps/api`
 Please use correct documentation.

Please provide minimal reproduction in codesandbox.com

**Comment by Angelk90** [comment]
@JustFly1984 : 
Here's to you:
Link: https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-scwzz

What I would like to do is this:
1) Every time a point of the polygon is put, a maker with a numeric label is put in the coordinated one
2) At the end when the polygon is closed, all the coordinates of the polygon points must return to me and must change the setting from Draw to shape to stop drawing
3) When in Stop drawing mode and user changes the position of the maker to also changes the point of the polygon accordingly.

**Comment by JustFly1984** [comment]
@Angelk90 
I've cleaned up a bit your example. I guess you need to use Marker component.
continue from here: https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-tgy5x

**Comment by Angelk90** [comment]
@JustFly1984 : 
How am I supposed to use this this I'm asking?
Furthermore, there is no method that when I change the points of the polygon I get back the updated points.

**Comment by Angelk90** [comment]
@JustFly1984 : Is there any news?

**Comment by ambr89** [comment]
@Angelk90  did you have found any solution about it? Can you intercept when polygon has updated?

**Comment by ashuradadiya2000** [comment]
@JustFly1984 thank you thank you  so much for give example 
i have done my task with your help thanks a lot
