### ISSUE TITLE
Find by lat and lng

### ISSUE THREAD

**Issue by Goshishah** [JustFly1984/react-google-maps-api#379]
I was implementing this library into my project. Right now I am using Autocomplete component and only able to search via place. But I want to search via latitude and longitude like google map use for search. how I can add this functionality?

Thanks

**Comment by giovanniantonaccio** [comment]
I have the same issue in my project here. Any tips on how to implement this? 

Thanks in advance!

**Comment by JustFly1984** [comment]
@Goshishah @giovanniantonaccio You need to use Directions API in conjunction with maps
https://developers.google.com/maps/documentation/directions/start?hl=ru
