### ISSUE TITLE
Map reference not defined

### ISSUE THREAD

**Issue by MiguelGPereira** [JustFly1984/react-google-maps-api#38]
Hello! When I try to use the functions binded to the map reference, I get an internal error that "google map is not defined". 
```javascript
<GoogleMap
    ref={map => {
            const bounds = new window.google.maps.LatLngBounds();
            map.fitBounds(bounds);
```
However, if I skip to the next loop in the event loop using a setTimeout, it works:
```javascript
<GoogleMap
    ref={map => {
        setTimeout(() => {
            const bounds = new window.google.maps.LatLngBounds();
            map.fitBounds(bounds);
        }, 0);
```
codesandbox demo: https://codesandbox.io/embed/1y7xqo7453

Should this be the default behaviour? Let me know if there's anything I can help :)

**Comment by JustFly1984** [comment]
@MiguelGPereira  instead of using ref, you need to use onLoad prop callback as in this example:

https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api-gatsby-example/src/examples/data-example.js

**Comment by MiguelGPereira** [comment]
Ah, alright! I just migrated from the old react-google-maps to yours, and that ref pattern was working before. Thank you very much for your fast response, it's working.

**Comment by JustFly1984** [comment]
I think we should add this to migration guide
