### ISSUE TITLE
Map Inside Popup Window Bug

### ISSUE THREAD

**Issue by zning** [JustFly1984/react-google-maps-api#384]
I was able to create a quick demo and please see the example here:

https://codesandbox.io/s/googlemap-popup-tesing-9d93h

When you click the button to put the map inside a popup window, something strange happened. Just  trying to drag around the map inside the popup window, the map will not move around. The event logs show only the onDragStart fired, the onDrag and onDragEnd events were decoupled  until you click back to the main app window, these two event resumed... Weird behavior.

**Comment by JustFly1984** [comment]
@zning  Do you have working example where you have fixed your issue?

**Comment by zning** [comment]
> @zning Do you have working example where you have fixed your issue?

I‘m still trying to solve this. Posted this to multiple places already but no luck.  I'm closed this because I want it to be one place (#248), so once it solved, all people could follow that one thread. 
Thanks for the following up.

**Comment by JustFly1984** [comment]
@zning 
I will reopen, cos my library will definitely use solution. I still advise you to window.open(url) instead of components. I think here you have issues with browsers, and you can have different behavior in different browsers or even OS. Have you test it in FF, Safari, IOS, Windows? or only Chrome?

**Comment by zning** [comment]
> @zning
> I will reopen, cos my library will definitely use solution. I still advise you to window.open(url) instead of components. I think here you have issues with browsers, and you can have different behavior in different browsers or even OS. Have you test it in FF, Safari, IOS, Windows? or only Chrome?

So far, I've tested on Chrome, Safari, Firerfox, Opera, they're all the same. Someone on the community found a solution without using the library and React Portal, but unfortunately, it may not as flexible and easy as I need. You could see it here:
https://spectrum.chat/react-google-maps/general/map-inside-popup-window-bug~372cf283-b2e7-4d34-a6fd-1d7faf815a23
I'm still trying find a solution for this. And let's keep this updated once it solved.
