### ISSUE TITLE
Change the color of the marker

### ISSUE THREAD

**Issue by Angelk90** [JustFly1984/react-google-maps-api#386]
## Please provide an explanation

Hi @JustFly1984 , Is there any way to change the marker color without having to define a new svg file?

## Your Environment

os: linux

node: v13.5.0

react 16.12.0

webpack latest cra

@babel latest cra

@react-google-maps/api 1.8.1

**Comment by JustFly1984** [comment]
@Angelk90 please refer to official documentation, or make custom marker
