### ISSUE TITLE
 StandaloneSearchBox problem

### ISSUE THREAD

**Issue by Angelk90** [JustFly1984/react-google-maps-api#390]
## Please provide an explanation

Hi @JustFly1984, I'm trying to add StandaloneSearchBox.
But I am not able to make it work gives me the following problem, see image.
Here is an online example on codesandbox, where I tried to insert it but it is not working properly.

Link: [codesandbox](https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-mdyeu)

![](https://i.stack.imgur.com/RkV0q.png)

## Your Environment
os: linux

node: v13.5.0

react 16.12.0

webpack latest cra

@babel latest cra

@react-google-maps/api 1.8.1

**Comment by Angelk90** [comment]
A possible solution:
https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-fkrs8

**Comment by lluisrojass** [comment]
@Angelk90 looks like your issue was the onLoad callback into the search box component, if so kindly close this.
