### ISSUE TITLE
RFC: Remove all updater functions that are included in object's options

### ISSUE THREAD

**Issue by uriklar** [JustFly1984/react-google-maps-api#40]
Currently each component has an `updaterMap` which is an object mapping react props to the function that updates that prop on the google maps instance. Here, for example, is the ```updaterMap``` object for Circle:

```

const updaterMap = {
  center (instance, center) {
    instance.setCenter(center)
  },
  draggable (instance, draggable) {
    instance.setDraggable(draggable)
  },
  editable (instance, editable) {
    instance.setEditable(editable)
  },
  map (instance, map) {
    instance.setMap(map)
  },
  options (instance, options) {
    instance.setOptions(options)
  },
  radius (instance, radius) {
    instance.setRadius(radius)
  },
  visible (instance, visible) {
    instance.setVisible(visible)
  }
}
```

The thing is, each of these functions is superseded by the setOptions function.  I.E:
`circle.setCenter(center)` is the equivalent of `circle.setOptions({center})`

Removing all these updater function in favour of `setOptions` will remove a ton of repeating and unnecessary code. The only downside to it is that instead of using the component like:
`
<Circle center={{ lat: 0, lng: 0 }} radius={10} />
`

You would have to do:
`<Circle options={{center: { lat: 0, lng: 0 }, radius: 10 }} />`

This is especially beneficial maintenance-wise when migrating to Typescript, since all these types are already defined by: https://www.npmjs.com/package/@types/googlemaps. 
But, they are all under the options property, since that's how google maps defines them. 
This means we can get all out typings out of the box, instead of having to create specific types for these "flattened" properties. 

I would love to get your thoughts on this.

@JustFly1984 @awwit @gregoryfm @xalisys

**Comment by JustFly1984** [comment]
@uriklar I do not really need those separate options. If you remove them, we will totally branch out of original `react-google-maps` without any backward compatibility. I'm personally don't care much. single prop is better than many. 

On other side passing an object to the prop is bad for performance. If you pass options object generated in runtime, it is bad for performance anyway. So less props, less headaches for everybody. We already get rid of `default` prefixed props anyway.

**Comment by uriklar** [comment]
Good points! I actually think backwards compatibility with react-google-maps is pretty crucial if we want people to be able to migrate easily. And also the performance point is a good one. 

I think those two are good enough points to drop this proposal.. We'll have a one time effort to write the type annotations correctly and then it will be behind us.

**Comment by JustFly1984** [comment]
Looks good!

**Comment by JustFly1984** [comment]
can we close this issue?

**Comment by JustFly1984** [comment]
reopen if needed
