### ISSUE TITLE
Typescript eslint dependencies/no-unresolved warning

### ISSUE THREAD

**Issue by uriklar** [JustFly1984/react-google-maps-api#42]
After migrating to typescript there is an eslint warning of unresolved dependencies for all imports

**Comment by JustFly1984** [comment]
you can turn 'off' rules in `.eslintrc.js` in package

**Comment by JustFly1984** [comment]
https://github.com/alexgorbatchev/eslint-import-resolver-typescript/commit/af4444181008fcc205c183adccd1352c19a9503d

**Comment by JustFly1984** [comment]
@uriklar can we close this issue?

**Comment by uriklar** [comment]
I tried playing around with these different settings last night but didn't manage to get to that golden setup yet... I think the current configuration in the typescript branch is ok except for these warnings.
I think we can leave it open for a bit longer
