### ISSUE TITLE
Why nodejs version was added to package.json in 1.8.2 version?

### ISSUE THREAD

**Issue by aleksandrlat** [JustFly1984/react-google-maps-api#430]
Nodejs version was added to `package.json` in 1.8.2 version here https://github.com/JustFly1984/react-google-maps-api/commit/406a88b76a29ed34d68030f30536f935667d510d#diff-be9de55362155ec12ffb9aee3fe5cc17R12-R14

There was no nodejs version prior 1.8.2.
I'm not sure why it was added but it disallows to use this library with nodejs version lower than `12.13.1`

I could not find any explanation of why nodejs version is required now in minor 1.8.2 lib update.

We still use prev LTS nodejs version `10.15.0`.
Do you think 1.8.2 will not work with nodejs `10.15.0`?

**Comment by JustFly1984** [comment]
I would advise to use 12.x cos it is LTS. We are using typescript and build tools, which work best with node 12. Do you have any particular issue with updating node.js?

**Comment by aleksandrlat** [comment]
@JustFly1984 thank you for response and advise!

10.x is also LTS. Unfortunately nodejs version is out of my control.

And again there is no nodejs version in 1.8.1 version. Why it is needed in 1.8.2 now? What has changed that requires nodejs version now?

12.x is probably good to compile and build. But it is not required to run compiled lib, right?

**Comment by aleksandrlat** [comment]
For example I see `devEngines` in react https://github.com/facebook/react/blob/master/package.json#L94-L96

Looks like it is some custom feature. These `devEngines` are checked here https://github.com/facebook/react/blob/master/package.json#L107 in `postinstall` script by `node_modules/fbjs-scripts/node/check-dev-engines.js package.json`

Probably this is what you need. But I'm not sure.

**Comment by JustFly1984** [comment]
@aleksandrlat your PR is welcome :)

**Comment by aleksandrlat** [comment]
@JustFly1984 here it is https://github.com/JustFly1984/react-google-maps-api/pull/469

**Comment by South-Paw** [comment]
Changing the node version would have been fine if it was released as a major version rather than a patch.

**Comment by ninjacarr** [comment]
Azure app service does not currently support 12.13.1 out of the box, but 12.13.0 is supported. If we keep the engine dep, at least bumping it down a notch could help a lot of people.

**Comment by South-Paw** [comment]
@JustFly1984 thanks for merging that PR - issue can be closed now! :)

**Comment by leibowitz** [comment]
this commit is far from enough
https://github.com/JustFly1984/react-google-maps-api/pull/469/commits/b68b3511cee2e4417edc3c108a6cfd7a14dd03cf
since the main package still depends on other packages with a strict version dependency on 1.8.2
https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/package.json#L86-L87
And these do have the engine part in package.json on 1.8.2 as well

**Comment by JustFly1984** [comment]
Ok, I will update and release tomorrow

**Comment by JustFly1984** [comment]
released 1.8.4
