### ISSUE TITLE
StreetViewService: onLoad function doesn't work

### ISSUE THREAD

**Issue by jeromevvb** [JustFly1984/react-google-maps-api#446]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Please provide an explanation

I use the `<StreetViewService onLoad={onLoad} />` component inside of my `<GoogleMap>` component and the onLoad function of StreetViewService is never trigger.
Why?

## Your Environment

os: mac/linux/windows/android/ios 
macOs 10.14.6

node --version
v12.9.1

react version
v16.12.0

webpack version
4.41.5

@babel version
v'7.8.3 

@react-google-maps/api version
v1.8.2

## How is it behave?
Nothing happen

## How should it behave correctly?
Fire my onLoadStreetView function

## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/confident-moon-fgrb4

**Comment by JustFly1984** [comment]
please don't post code in issue, provide codesandbox.io example with code.

**Comment by jeromevvb** [comment]
@JustFly1984 Sorry, please find my codesandbox here https://codesandbox.io/s/confident-moon-fgrb4
you'll notice that the `onLoadStreetView` is never trigger.
Thanks

**Comment by JustFly1984** [comment]
I've updated your example, and now I see the prop is passed correctly
https://codesandbox.io/s/recursing-grass-3gmrb

<img width="1920" alt="Screenshot 2020-01-24 18 20 26" src="https://user-images.githubusercontent.com/2255993/73080123-61071900-3ed6-11ea-812a-a8ff367b1762.png">

I can't really tell why, but for next 2 weeks I'm on vacations. I'm confirming the bug. Maybe @uriklar can help if he has time. If you have time yourself - you can make a PR, and I will merge it ASAP.
