### ISSUE TITLE
DirectionsRenderer triggering unnecessary requests

### ISSUE THREAD

**Issue by JoeKlimcak** [JustFly1984/react-google-maps-api#447]
Hey guys,

I downloaded your Directions Renderer example from netlify. The issue that I'm seeing is when you build a route, the map starts glitching for a good few seconds before stabilizing. I noticed in the console that it seems to be calling the directions service many times and thus triggering a render each instance.

Is this something known?

Attaching gif:
![dirRen](https://user-images.githubusercontent.com/19940004/73040095-32465f80-3e50-11ea-9ae4-181fdcac12b4.gif)

**Comment by JustFly1984** [comment]
@JoeKlimcak 
please isolate each component in React.memo() and use debounce or something, also redux is usefull.

eslint with eslint-plugin-react-perf - must have to eliminate excessive renders

**Comment by krismorf** [comment]
I have the same issue inside the Directions callback. If I just console.log the response it returns only 1, whereas if I use a hook it will re-render until it's stooped by `OVER_QUERY_LIMIT`. Tried with memo() but no change.
```jsx
const directionsCallback = response => {
    if (response !== null) {
      if (response.status === "OK") {
        console.log(response) // This alone works
        setDirectionsResponse(response) // This is triggering the re-render
      }
    }
  }
```

**Comment by liao02x** [comment]
I had the same issue, and what I did is just use google.maps for direction instead of DirectionsService component. 
I think there's some bug within the component because what really happens is that the DirectionsServices calls API many times and DirectionsRenderer just re-render after every API call.

**Comment by krismorf** [comment]
Interestingly enough this is the default behavior of Maps Javascript API. When adding another hook inside the function for whatever reason it will still re-render.
```jsx
useEffect(() => {
    if (pickupCoordinates !== null && destinationCoordinates !== null) {
      directionsService.route(request, (result, status) => {
        if (status === 'OK') {
          directionsRenderer.setDirections(result) // This alone works
          // setDirectionsResponse(response) // This is triggering the re-render
        }
      })
    }
    return () => {
      // Clear directions on cleanup
      directionsRenderer.setMap(null)
    }
  }, [
    ...,
  ])

**Comment by ankithherle** [comment]
Any solution for this ?

**Comment by JoeKlimcak** [comment]
Never found one. Resorted to using the old, unsupported react-google-maps library for directions only. Doesn’t seem to have an issue there.

**Comment by vedran-laplacian** [comment]
I have the same issue when using useState hook in component that uses DirectionsService.

**Comment by christiankn** [comment]
Elaborating @JustFly1984's answer for the example code:

`const DirectionsAsAService = ({destination, origin, travelMode, callback}) => {
    return <DirectionsService
        options={{
            destination: destination,
            origin: origin,
            travelMode: travelMode,
        }}
        callback={callback}
    />
};

const DirectionsServiceMemo = memo(DirectionsAsAService);
`

Then use it like this

`<DirectionsServiceMemo
    destination={this.state.destination}
    origin={this.state.origin}
    travelMode={this.state.travelMode}
    callback={this.directionsCallback}
/>`

**Comment by cyberlake** [comment]
Similar issue while using within [react-admin](https://github.com/marmelab/react-admin). Map re-render when focused on any input

**Comment by JustFly1984** [comment]
@cyberlake please provide minimal reproduction at codesandbox.io

**Comment by agustin107** [comment]
Guys, I leave you my approach to use `setState` in `directionsCallback` and avoid re-renders.

I hope this helps you. 

**Approach**: [CodeSandbox](https://codesandbox.io/s/react-google-maps-directions-service-render-inywc)

**Comment by cyberlake** [comment]
The above comment actually helped. Thanks @agustin107 .   I just added a couple of extra checks to compare and reset count when origin or destination is changed. Also, set `center` to `undefined` if you are changing origin and destination, otherwise map re-renders and sets center to the initial value. I'll try to make codesandbox with a full example.

**Comment by cyberlake** [comment]
Here are an example `codesandboxe`s.
[This one](https://codesandbox.io/s/react-admin-google-maps-example-with-render-issues-9vtm4?file=/public/index.html:1074-1174) is the one with issues, where map re-renders after setting directions and pressing on any other input.

[And this one](https://codesandbox.io/s/react-admin-google-maps-working-example-d7lom?file=/public/index.html) is working examples with the changes suggested above by @agustin107

**Comment by agustin107** [comment]
Another

> Here are example `codesandboxe`s.
> [This one](https://codesandbox.io/s/react-admin-google-maps-example-with-render-issues-9vtm4?file=/public/index.html:1074-1174) is the one with issues, where map re-renders after setting directions and pressing on any other input.
> 
> [And this one](https://codesandbox.io/s/react-admin-google-maps-working-example-d7lom?file=/public/index.html) is working examples with the changes suggested above by @agustin107

Another way that I've improved when you need to refresh `directions`, when `origin` or `destination` was updated is to use `useEffect`.

```
useEffect(() => {
    count.current = 0;
}, [origin, destination]);
```

**Comment by aazcast** [comment]
Hi Thanks for the temporal solution @agustin107 ! At the end the problem persist. i will try to debug and know why this happens. it not ok. i just check even with the count.current there is a loop of request on directions service. our Api Google Tokens collapse, because of high request using it only 1 person on development.

**Comment by ShaMan123** [comment]
+1 seems to be related to zooming

**Comment by aazcast** [comment]
Doing this solves the problem:

const directionsService = new google.maps.DirectionsService()
directionsService.route({
        origin,
        destination,
        travelMode: travelMode || 'DRIVING',
        waypoints
      }, (result, status) => 
          if (status === google.maps.DirectionsStatus.OK) {
              if (result) {
                  setDirections(result)
              }
        } 
      })

**Comment by ShaMan123** [comment]
This didn't fix the flickering for me

**Comment by kenkit** [comment]
@christiankn christiankn solution works.
Except for a minor warning I can't trace 
```
InvalidValueError: setDirections: not an Object
```

**Comment by kenkit** [comment]
Found the bug, turns out I had not defined  response  in my state.

**Comment by NeliHarbuzava** [comment]
My problem was that I used the compoent like this:
```js
<DirectionsRenderer
    options={{
        directions: directionGeoData,
     }}
 />
```
It has been creating new object every time

**Comment by TheNatas** [comment]
For cases in which the directions don't need to be dynamic, setting the response only if it isn't already set will fix the problem:

```
if (directionsResponse) {
    setDirectionsResponse(response);
}
```

**Comment by Younggregs** [comment]
This worked for me perfectly:

`const options = useMemo(
    () => ({
      origin: "Zurich, Switzerland",
      destination: "Bern, Switzerland",
      waypoints: [{ location: "Geneva, Switzerland" }],
      travelMode: google.maps.TravelMode.DRIVING,
    }),
    []
  );

  const directionsCallback = useCallback(
    (
      result: google.maps.DirectionsResult | null,
      status: google.maps.DirectionsStatus
    ) => {
      if (status === google.maps.DirectionsStatus.OK && result !== null) {
        setDirections(result);
      } else {
        console.error(`Directions request failed due to ${status}`);
      }
    },
    []
  );`
