### ISSUE TITLE
Error (Uncaught exception) when unmounting Map

### ISSUE THREAD

**Issue by mpgon** [JustFly1984/react-google-maps-api#47]
# Please provide an explanation
Sometimes the subscriptions are not correctly canceled during the Map component unmount. This is causing occasional crashes in our E2E tests. When Lazy Loading the map with Suspense, the problem is considerably exacerbated, ence I reproduce it that way in this codesandbox: https://codesandbox.io/s/1y7xqo7453

## Your Environment
in codesandbox

## How does it behave?
If you quickly unmount the map, sometimes it will trigger the following warning:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in LoadScript (created by Map)
```

This will trigger the following error:
```
TypeError: Cannot read property 'parentNode' of null
at LoadScript.eval [as cleanup] (webpack-internal:///./node_modules/@react-google-maps/api/lib/LoadScript.js:82:14)
at LoadScript.componentWillUnmount (webpack-internal:///./node_modules/@react-google-maps/api/lib/LoadScript.js:170:12)
at callComponentWillUnmountWithTimer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16670:12)
at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:147:14)
at HTMLUnknownElement.dispatchEvent (http://10.0.4.6:56409/hammerhead.js:3:13879)
at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:197:16)
```

## How should it behave correctly?
It should correctly clean all the pending subscriptions on unmount.

## How to reproduce?
Click on the Refresh icon in the browser view, and then as quickly as possible click on "Map OFF". You should find the error in the console.

**Comment by MiguelGPereira** [comment]
**UPDATE**: I managed to reproduce this problem without lazy loading, so it might not be solely related to that. However, lazy loading makes this problem easier to reproduce, without lazy loading is considerably harder. I'll update the title and the description accordingly.

**Comment by uriklar** [comment]
Hi @MiguelGPereira. Thanks a lot for the super detailed bug report. 
I'll look into it in the next couple of days

**Comment by JustFly1984** [comment]
@MiguelGPereira please check new @1.0.10 version. It should resolve your error.

**Comment by JustFly1984** [comment]
@MiguelGPereira I've tested your codesandbox example, and it seems there is no issue

**Comment by MiguelGPereira** [comment]
@JustFly1984 I updated to the new version but the problem still occurs, although it looks harder to reproduce. But even in the codesandbox w/@1.0.10 it still happens, try a few times clicking fast between Refresh and Map OFF, and you'll see the `Warning: Can't perform a React state update on an unmounted component in LoadScript` in the console. You might want to add an API_KEY to the const in "map.js" so the error `You have exceeded your request quota for this API` doesn't appear first.

**Comment by nojaf** [comment]
Hi @mpgon I'm having the same error ```react-dom.development.js?7f13:546 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in LoadScript```

Were you ever able to solve this?

**Comment by mpgon** [comment]
@nojaf unfortunately not, we ended up migrating to mapbox and react-map-gl

**Comment by JustFly1984** [comment]
@uriklar  mention

**Comment by osphost** [comment]
Also experiencing this, seems to happen when nextjs hot reloads in development mode.

**Comment by JustFly1984** [comment]
considering issue closed

**Comment by mattvb91** [comment]
@ostenning i am still experiencing the same issue even when switching to LoadScriptNext. Could you expand on what you "switched" to the react hooks API? Im not really sure what I should switch to it?
