### ISSUE TITLE
Marker have no rotation

### ISSUE THREAD

**Issue by howdyhyber** [JustFly1984/react-google-maps-api#478]
I tried to display marker in map but it does have bearing/rotation. How to do it using this? There is no rotation field in documentation.

**Comment by bluiska** [comment]
It is not possible to rotate the JavaScript-based Google Maps, unfortunately. 

[https://stackoverflow.com/questions/11985107/how-to-rotate-map-orientation-with-google-maps-api-v3]

**Comment by rawtaz** [comment]
I'm pretty new to the Google Maps API and this lovely React library, but doesn't https://developers.google.com/maps/documentation/javascript/reference/marker#Symbol.rotation suggest that Markers should be able to rotate? If not, why? If yes, what is needed for that to work in this library?

**Comment by bluiska** [comment]
I have a feeling that Markers themselves can rotate. The trouble is rotating the tiles is what's not implemented as far as I can tell. Sure, you can tell a marker to rotate but if the base map is unable to rotate then that's not much use. Mapbox is able to rotate the map online (i just discovered this recently)

**Comment by rawtaz** [comment]
@bluiska Sorry the ignorant follow up question here, but I'm not entirely following what you mean. If the marker itself, it's icon, can rotate, then what does this have to do with map tiles They're two different things unless I'm mistaken. Rotating the Marker itself should be doable if this library can just support the rotation property of the Google Maps Marker, no?

**Comment by bluiska** [comment]
@rawtaz Apologies for the unclear answer.  I had another look and the MarkerOptions object does not have a rotation parameter for the JavaScript API. Don't get this confused with the Android (or other) API as that does allow for rotation (https://developers.google.com/maps/documentation/android-sdk/marker#rotate_a_marker). 

So unfortunately, it is not possible to rotate a Marker. The link that you have sent specifies the rotation for a Symbol which can be used as an icon for a marker, not the marker itself.

**Comment by iamir4g** [comment]
hi, I have the same issue, I can't rotate my custom icon. my data comes from server one field rotation, this is my code :
```
import GreenArrow from '../assets/images/icon/TruckMoving.png';
...
<Marker
         key={value.ID}
         position={{ lat: parseFloat(value.YPOINT), lng: parseFloat(value.XPOINT) }}
         onLoad={marker => markerLoadHandler(marker, value)}
         onClick={event => markerClickHandler(event, value)}
         icon={{ url: GreenArrow ,rotation: parseInt(value.DIRECTION), scaledSize: new google.maps.Size(22, 22) }}
            />
```
how to rotate the marker?

**Comment by JustFly1984** [comment]
@iamir4g please provide minimal reproduction in codesansbox.io

**Comment by iamir4g** [comment]
> @iamir4g please provide minimal reproduction in codesansbox.io

this link [codesandbox](https://codesandbox.io/s/stoic-cartwright-y69eb?file=/src/Maps.js)

**Comment by rawtaz** [comment]
@iamir4g The Marker doesn't have suppor for rotation I think. Here's how I ended up having to do it, using Icon:

~~~
<Marker
    key={aircraft.registration}
    title={aircraft.registration}
    opacity={opacity}
    position={{ lat: aircraft.lastLocation.latitude, lng: aircraft.lastLocation.longitude }}
    icon={{
        path: this.gliderSvgPath,
        strokeColor: 'black',
        fillColor: 'black',
        strokeWeight: 1.8,
        scale: 0.6,
        anchor: new window.google.maps.Point(50, 43),
        rotation: aircraft.heading,
    }}
/>
~~~

The properties for the Icon are described in the Google Maps API documentation.

**Comment by iamir4g** [comment]
@rawtaz thank, but I don't understand, now u cant rotate or not? and your icon is SVG ?? if yes how to add SVG icon?

**Comment by rawtaz** [comment]
@iamir4g Not sure what you mean by "now u cant rotate or not?" - The code I pasted is what I use to be able to rotate an icon. It's technically not a Marker, but an Icon, that's the way I found I had to do it given that Marker doesn't support rotation. Instead you rotate the Marker's Icon.

In the code, the `this.gliderSvgPath` variable is SVG path data (`gliderSvgPath = 'M98.88,40.089l-20.965-0.476H52.382c0.033-0.361-0.012-2.196-0.193-6.602 ...`), you can grab that out of your SVG, see [here](https://stackoverflow.com/a/38206993) for info on how to do that.

Does that help?

**Comment by iamir4g** [comment]
@rawtaz Thank you for your time,
I read this post [rotate...](https://stackoverflow.com/a/57277224/10734755) and update may [codesandbox](https://codesandbox.io/s/stoic-cartwright-y69eb?file=/src/Maps.js:4601-4631).
I can rotate my png icon but can't use it.

**Comment by rawtaz** [comment]
@iamir4g I don't think anyone here knows what "can't use it" means, please be more specific when describing the symptoms of your problem.

**Comment by iamir4g** [comment]
> @iamir4g I don't think anyone here knows what "can't use it" means, please be more specific when describing the symptoms of your problem.

hi, I cant, rotate my png, please explain how to convert a PNG image to SVG to use your code:
```
<Marker
    key={aircraft.registration}
    title={aircraft.registration}
    opacity={opacity}
    position={{ lat: aircraft.lastLocation.latitude, lng: aircraft.lastLocation.longitude }}
    icon={{
        path: this.gliderSvgPath,
        strokeColor: 'black',
        fillColor: 'black',
        strokeWeight: 1.8,
        scale: 0.6,
        anchor: new window.google.maps.Point(50, 43),
        rotation: aircraft.heading,
    }}
/>
```

**Comment by rawtaz** [comment]
@iamirg4 A PNG is a bunch of pixels, you cant just convert that to a vector format like SVG out of the box. You'd essentially have to "redraw" the lines and curves you want from that original motive in vector format. I suggest you DuckDuckGo this, or find a SVG to use instead :)
