### ISSUE TITLE
Add support for mapElement and containerElement

### ISSUE THREAD

**Issue by buzzguy** [JustFly1984/react-google-maps-api#48]
# Please provide an explanation
A google map is rendered nested inside an empty div. I'm trying to use a sticky class, but the div is preventing that. Could this be refactored as a fragment or allow for declaring the element with a classname or id? thanks!

**Comment by JustFly1984** [comment]
@buzzguy This empty div comes from `<LoadScript />` component. All `<GoogleMap />` components should be children of LoadScript. If you know `redux` - `<LoadScript /> is like a `<Provider />`, which provides google maps api <script /> for all maps used in your React app by Context API.

You can place <LoadScript /> somewhere higher in your component structure, where it does not affect your css layout, and style `<GoogleMap />` component directly in place where it is needed. 

Currently we are not planing to style that `div`, cos `<LoadScript />`'s API could be changed in the future.

**Comment by JustFly1984** [comment]
BTW I failed an issue in google maps bug tracker for supporting proper cleanup in their script. Please add your concern in their tracker https://issuetracker.google.com/issues/121054556
