### ISSUE TITLE
onDrag, onDragEnd, onDragStart return new center map

### ISSUE THREAD

**Issue by Angelk90** [JustFly1984/react-google-maps-api#484]
## Please provide an explanation

Hi @JustFly1984 , 
I would need a way that when I move the map then the center of the source map has changed, to know the new center.
The reason is very simple, I have many markers, but I can't query the db for points.
What I do is take the center of the map, pass it to the backend, pass a beam and he returns to me all the markers that are in that area.
The problem at the moment that when I use an event of type onDrag ... nothing is returned, I would need the center to return, I think it is a very logical thing.

Link: [codesandbox](https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-5l4uo)

File: https://github.com/JustFly1984/react-google-maps-api/blob/1ddc54799df63fa7a8ccb53de95b50611d1d1ea0/packages/react-google-maps-api/src/GoogleMap.tsx#L92-L97

I assume it should become something like this:

```
 /** This event is repeatedly fired while the user drags the map. */ 
 onDrag?: (e: google.maps.Drag) => void 
 /** This event is fired when the user stops dragging the map. */ 
 onDragEnd?: (e: google.maps.DragEnd) => void 
 /** This event is fired when the user starts dragging the map. */ 
 onDragStart?: (e: google.maps.DragStart) => void 
```

or

```
 /** This event is repeatedly fired while the user drags the map. */ 
 onDrag?: (e: google.maps.MouseEvent) => void 
 /** This event is fired when the user stops dragging the map. */ 
 onDragEnd?: (e: google.maps.MouseEvent) => void 
 /** This event is fired when the user starts dragging the map. */ 
 onDragStart?: (e: google.maps.MouseEvent) => void 
```

## Your Environment

os: linux

node: v13.5.0

react 16.12.0

webpack latest cra

@babel latest cra

@react-google-maps/api 1.8.1

**Comment by herzuull** [comment]
Hello, 

I have the same issue for the Zoom Event : 
`/** This event is fired when the map zoom property changes. */
    onZoomChanged?: () => void;`
Should be : 
`/** This event is fired when the map zoom property changes. */
    onZoomChanged?: (e: google.maps.MouseEvent) => void;`

Thanks !!

**Comment by GuillaumeSpera** [comment]
Hi guys, this library doesn't alter the behaviour of GMaps API.
Therefore, you only have event callbacks.
If you want to access those data, you have to add an onLoad event on your map :
`onLoad={map => {
            console.log(map);
          }}`
Store that map value into some sort of singleton or class context if you are using class components.
Then, once events occur, you use this ref to access the data :
`onZoomChange = () => {
        if (this.mapRef) {
            const zoom = this.mapRef.getZoom();
            console.log(zoom);
        }
    }`

That's how I figured you are supposed to consume this library with what I've seen from documentation, etc.

Hope I deduced the right informations and that it'll help you guys.

**Comment by Angelk90** [comment]
Hi @GuillaumeSpera , 

take a look here: https://developers.google.com/maps/documentation/javascript/events#EventsOverview

What we are saying is not alteral to the library, but being that there are the definitions of `onDrag`, ..., `onZoomChanged`, they have the definition of empty topic, which probably they probably have a topic that is passed which can be accessed. 'information.

For example, for what I have to do the I need that when the `onDragEnd` is done, I return the center of the map to take all the markers that are in a radius r from the new center.

I could also use `mousemove` as an event, the problem that I would have too many updates and then it would not be very correct.

I don't know if I managed to explain myself.

**Comment by GuillaumeSpera** [comment]
https://developers.google.com/maps/documentation/javascript/reference/map#Map.dragend
The documentation clearly says it doesn't provide any argument when the event listener is called.

For that, you need to do as I explained.
I do understand what you need to do (I do the same : once I have moved to a new map area using drag, I request an API for some data that are rendered into new Markers).

To do that, you can use the map reference when the onDragEnd event is triggered to call the `map.getCenter()` and trigger your own call to API with the center.

I don't have the time right now to provide an example, I'll try to make you one if you have issues.

**Comment by Angelk90** [comment]
@GuillaumeSpera : 
I understand, it would be very useful if I could make an example on codesandbox.

**Comment by Angelk90** [comment]
@GuillaumeSpera :
I understand, it would be very useful if I could make an example on codesandbox.

**Comment by Angelk90** [comment]
@GuillaumeSpera , @JustFly1984 : Is there any news?

**Comment by Angelk90** [comment]
@GuillaumeSpera , @JustFly1984 : Is there any news?

**Comment by leandrosalgado** [comment]
Why don't you use the 'idle' event? You can add a listener and get the new center:

map.addListener("idle", callback)

> This event is fired when the map becomes idle after panning or zooming.

https://developers.google.com/maps/documentation/javascript/reference/map#Map.idle
