### ISSUE TITLE
Reference Map object from outside the GoogleMap component

### ISSUE THREAD

**Issue by buzzguy** [JustFly1984/react-google-maps-api#49]
Thanks for the quick response to my last issue.

I'm able to control the map object from within the onLoad function, but I wanted to have an airbnb like effect of hovering over a place card which would trigger a panTo that marker on the map and perhaps a toggle of an infowindow. 

would you know the best way of doing that?

thanks

**Comment by uriklar** [comment]
Hi @buzzguy. You say you have the map object from onLoad, why not save it somewhere (class variable for instance) and then you'll be able to control it whenever you wish?

**Comment by FredyC** [comment]
It might easier and more robust to use a Context for that purpose. Perhaps even on the side of the library, it would make sense except it could be `undefined` till loaded, but that should be fine.

**Comment by uriklar** [comment]
We use context to pass the map down to it's children, but @buzzguy is talking about accessing the map from the parent that renders it

**Comment by buzzguy** [comment]
@uriklar  Hi, I do have the map object that exists within the onLoad. 
The hierarchy of the components is basically:
- Page
    - List of places component
	    - place item
    - Map Component
	    - markers

So if I want to give place item scope to the map object inside of Map Component, I should save it as a class variable? Would you have an example?

I have the map object from within the onLoad method of GoogleMap from the example (below).
```
callBack = map => {
    const bounds = new window.google.maps.LatLngBounds();
    map.fitBounds(bounds);
  }
render(){
<GoogleMap
  onLoad={this.callBack}
/>
```

**Comment by uriklar** [comment]
First of all, this question isn't really react-google-maps-api related.. Second, I can try and help, but i'd have to see some code. Can you link a codesanbox with what you're trying to do?
In general, once you get the map from onLoad you can save it wherever you want, be it a class variable, state, context...

**Comment by buzzguy** [comment]
@uriklar right on, you're right. I figured it out. I just set this.map = map in the callBack. thanks!
