### ISSUE TITLE
Syntax error in Safari, parameter name shadows function name

### ISSUE THREAD

**Issue by emilioestebanez** [JustFly1984/react-google-maps-api#518]
# Issue template

## Please provide an explanation

In LoadScript.tsx (https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/LoadScript.tsx#L59) there is the following code:

```
this.isCleaningUp()
        .then(this.injectScript)
        .catch(function err(err) {
          console.error('Error at injecting script after cleaning up: ', err)
        })
```

When this is being used with iOS Safari 9 it throws this error:

> SyntaxError: Cannot declare a parameter named 'err' as it shadows the name of a strict mode function

## Your Environment

os: ios safari 9

node 12

react 16.11

webpack 4.39.0

@babel 7.6.4

@react-google-maps/api 1.7.12 (also occurring in latest version)

## How is it behave?
Throws this error on iOS Safari 9
> SyntaxError: Cannot declare a parameter named 'err' as it shadows the name of a strict mode function
## How should it behave correctly?
Modifying the parameter name from `err` to something else different than the function name (e.g. `e`) should solve this.

## basic implementation of incorrect behavior in codesandbox.com
N/A

**Comment by JustFly1984** [comment]
released 1.8.5
