### ISSUE TITLE
onPlacesChanged callback is not called if function passed as variable

### ISSUE THREAD

**Issue by aiven715** [JustFly1984/react-google-maps-api#527]
## How is it behave?
When I pass function as variable(for example `console.log`) as `onPlacesChanged` callback of `StandaloneSearchBox` component, it's not called upon clicking a suggestion.

It is only called when I provide anonymous inline function such as:
```
<StandaloneSearchBox
  onPlacesChanged={() => console.log("Suggestion clicked")}
/>
```

## How should it behave correctly?
Once function passed as variable it should be called when suggestion was clicked by a user.

## basic implementation of incorrect behavior in codesandbox.com
It is reproduced here - https://codesandbox.io/s/laughing-moon-r9hv4

**Comment by lluisrojass** [comment]
Does onPlacesChanged even get invoked with a param? lib TS typings imply not, what do you expect to get logged?

**Comment by aiven715** [comment]
I expect onPlacesChanged function to be called, when it's provided as a variable to the prop, check the codesandbox example

**Comment by lluisrojass** [comment]
Got it, i'm simply unable to reproduce this

![2020-02-07 21 32 53](https://user-images.githubusercontent.com/15043356/74077873-8c6b2700-49f1-11ea-97cb-c3bdc2e0fb46.gif)
