### ISSUE TITLE
can we publish the deletion of the node_engines in package.json?

### ISSUE THREAD

**Issue by kelly-tock** [JustFly1984/react-google-maps-api#537]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Please provide an explanation
it is currently breaking a build for me :)
## Your Environment

os: mac/linux/windows/android/ios

node --version

react version

webpack version

@babel version

@react-google-maps/api version

**Comment by JustFly1984** [comment]
It should be published in 1.8.3

**Comment by kelly-tock** [comment]
i'm still getting this in 1.8.3.
