### ISSUE TITLE
Circle shape

### ISSUE THREAD

**Issue by grdpr** [JustFly1984/react-google-maps-api#56]
Hi,
Are there any options to render the Circle Component more rounded? I seems to me not totally a perfect circle. Any borderRadius possible to override the radius option? 
Thanks!

**Comment by uriklar** [comment]
Hi @grdpr 
Issues isn't the place for these questions... Please join [our slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtNTQ4NzU4NDY5ODc4LTYwZTRhNWU1ODcxMDM0ZjAwODRlZmQzNDkyYjk4YjZhMzNhZmFjYmM1MTE4YTM1OTgyYjVhZjE0NGYwNDE2NTU) and you'll probably find help there.

regarding your question, google maps draws the circle and it can't be edited with css.
