### ISSUE TITLE
Bump major version if node12 is now required

### ISSUE THREAD

**Issue by willedanielsson** [JustFly1984/react-google-maps-api#568]
Hi and first of thanks for a really smooth library!

I was going to bump our version 1.8.1 to the patch 1.8.3 when I saw that now node12 is required. Therefore I'd suggest the version bump should be more than just a patch 👍

**Comment by kpalmvik** [comment]
See https://github.com/JustFly1984/react-google-maps-api/issues/430

**Comment by JustFly1984** [comment]
fixed

**Comment by willedanielsson** [comment]
Thanks @JustFly1984  👍
