### ISSUE TITLE
Should @types/googlemaps be in dependencies?

### ISSUE THREAD

**Issue by robations** [JustFly1984/react-google-maps-api#57]
## Your Environment

(other details unlikely to be relevant)

@react-google-maps/api version = 1.1.0

## How is it behave?

> How **does** it behave :)

In the exported Typescript definitions we have an old-fashioned reference comment, such as:

```
/// <reference types="googlemaps" />
```
(from `@react-google-maps/api/lib/components/drawing/Marker.d.ts`)

and further down the same file we have references to the Google Maps types:

```
interface MarkerProps {
    options?: google.maps.MapOptions;
    animation?: google.maps.Animation;
...
```

The reference is to `@types/googlemaps` but as this is in devDependencies it is necessary to track this down and manually install, so that you can refer to the types within the IDE.

## How should it behave correctly?

If `@types/googlemaps` is in dependencies it will be installed for consumers of the package as well. There could be arguments against this, such as package bloat, but would give a better experience for users IMO.

**Comment by uriklar** [comment]
Hi @robations,
What IDE support are you missing? I just created a create-react-app and it looks like i'm getting TS support correctly

![image](https://user-images.githubusercontent.com/2545447/53958420-afa69b80-40e9-11e9-8d37-d2d5bec7e3ef.png)


Also, which IDE are you using?

**Comment by robations** [comment]
I'm using PHPStorm, and the `google.maps.xyz` references are underlined as undefined/unknown.

When I install `@types/googlemaps` the reference works okay. The package works (as far as I have tested), it's more of a developer experience or documentation issue.

(Thanks for the quick reply, and for the package/maintenance.)

**Comment by robations** [comment]
Is that VSCode? If `@types/googlemaps` is only in devDependencies (therefore not installed for consumers) how does it know what the "googlemaps" reference is referring to? 🤔 

Perhaps VSCode parses the `package.json` files under `node_modules/` and installs types separately?

**Comment by uriklar** [comment]
Ok yeah I just got what you mean :-) You aren't seeing the googlemaps types.
DX was a big consideration behind the Typescript re-write so this is definitely worth the extra few kbs IMHO.. Either that or a clear message in the docs saying you need to install it.
@JustFly1984 what do you think?

Without ```@types/googlemaps``` in the dependencies it basically means you could write:
```<Marker options={{nonExistingOption: "wrongValue" }} />``` and not get a warning

**Comment by uriklar** [comment]
Yeah it's VSCode, but it only recognises our lib's types, not the googlemaps types. As I wrote in the previous comment.

**Comment by robations** [comment]
That's it. There's a general discussion of this issue here:

https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

I don't think it would be included in the build package, just would mean consumers would install the extra package (whether or not they use Typescript, although JS users would benefit if the IDE understands the types).

**Comment by uriklar** [comment]
Yeah, sounds like a no brainer... The @types/googlemaps lib is basically this library's documentation :-)
Wanna create a PR?

**Comment by robations** [comment]
Done! Unless I missed something.
