### ISSUE TITLE
Circle does not work

### ISSUE THREAD

**Issue by kasinskas** [JustFly1984/react-google-maps-api#59]
## Environment

os: mac

node --version - v10.13.0

react version - 16.7.0

webpack version - 4.23.1

@babel version - 7.1.2

@react-google-maps/api version - ^1.1.0

## How does it behave?

I copied exact same example of a map with a circle from docs and map works fine, but circle doesn't even appear.

**Comment by uriklar** [comment]
Please provide code on better yet a codesandbox

**Comment by faraz566** [comment]
Not working for me as well
