### ISSUE TITLE
StandaloneSearchBox rendering problems

### ISSUE THREAD

**Issue by daniel17903** [JustFly1984/react-google-maps-api#60]
I am unable to get google maps rendering correctly when using the StandaloneSearchBox example code. 

My code looks like this:
```
import React from 'react';
import { GoogleMap, LoadScript, StandaloneSearchBox } from "@react-google-maps/api";

class LocationSearchInput extends React.Component {
        
    render() {
        return (
            <LoadScript
            id="script-loader"
            googleMapsApiKey={"Api-Key"}
            language={"de"}
            region={"DE"}
            version={"weekly"}
            libraries={["places"]}
            onLoad={() => console.log("script loaded")}
            loadingElement={<div>Loading...</div>}
            >
                <GoogleMap
                    id="rectangle-example"
                    mapContainerStyle={{
                        height: "400px",
                        width: "800px"
                      }}
                      zoom={8}
                      center={{
                        lat: -34.397,
                        lng: 150.644
                      }}
                >
                    <StandaloneSearchBox>
                    <input
                        type="text"
                        placeholder="Customized your placeholder"
                        style={{
                        boxSizing: `border-box`,
                        border: `1px solid transparent`,
                        width: `240px`,
                        height: `32px`,
                        padding: `0 12px`,
                        borderRadius: `3px`,
                        boxShadow: `0 2px 6px rgba(0, 0, 0, 0.3)`,
                        fontSize: `14px`,
                        outline: `none`,
                        textOverflow: `ellipses`,
                        position: "absolute"
                        }}
                    />
                    </StandaloneSearchBox>
                </GoogleMap>
            </LoadScript>
        );
    }
}

export default LocationSearchInput;
```

And the map is rendering like this:
![image](https://user-images.githubusercontent.com/9028156/54314503-23f6a880-45dc-11e9-9128-9ac38d85abfb.png)

How can i get rid of these grey areas?

## Environment
os: windows
node --version: v8.12.0
react version: 16.8.4
webpack version: 4.28.3
@react-google-maps/api: 1.1.0

**Comment by uriklar** [comment]
Are these grey areas constantly there? It looks a bit like tiles not loading due to connection problems

**Comment by daniel17903** [comment]
Yes, they are there constantly. I can move the map around, zoom in or out but there are always grey areas. When looking in the chrome devtools I can not see any failed or pending network requests.

![image](https://user-images.githubusercontent.com/9028156/54347706-cc8e2200-4647-11e9-85f2-8154c2316925.png)

![image](https://user-images.githubusercontent.com/9028156/54347723-da43a780-4647-11e9-835d-afa74b12d2a1.png)

**Comment by uriklar** [comment]
Hi @daniel17903,
I've tried putting your example in codesandbox and I don't get these grey bars. 
Can you try editing this example: https://codesandbox.io/s/lxkw25j65q (or creating your own) that manages to re-create the issue?
Maybe you have some additional elements, css not included in your example code?

**Comment by daniel17903** [comment]
While trying to re-create the issue I found the problem. I had some css included by another component that destroyed google maps:

```
img {
    display: block;
    max-width: 90px;
    max-height: 90px;
    width: auto;
    height: auto;
    margin: 2px;
}
```

Thanks for your help
