### ISSUE TITLE
UMD dist

### ISSUE THREAD

**Issue by kevinresol** [JustFly1984/react-google-maps-api#62]
Any plan to provide a UMD build to be used without bundling (e.g. load from CDN)?

**Comment by JustFly1984** [comment]
@kevinresol We are working on typescript refactoring and version 1.2.0 right now. Will definitely come back to your PR later.

**Comment by JustFly1984** [comment]
@kevinresol  If you can PR some setup how to auto-deploy to some free CDN on post-publish hook, it will be useful.

**Comment by kevinresol** [comment]
If you publish the umd output to npm, it would automatically be available on unpkg.com

**Comment by JustFly1984** [comment]
@kevinresol Thank you, I will make umd next week

**Comment by uriklar** [comment]
We can use https://github.com/mobxjs/mobx-state-tree/tree/master/packages as a good reference

**Comment by JustFly1984** [comment]
Done in 1.2.3
