### ISSUE TITLE
Can i use ImageMapType in react-google-maps?

### ISSUE THREAD

**Issue by cuongdevjs** [JustFly1984/react-google-maps-api#633]
# Issue template
I have tons the image and I wanna use ImageMapType as example google.
But in react-google-maps, I don't know how to do it. I used props defaultExtraMapTypes but it's not working. 
Have any idea? Thanks
If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Your Environment

os: mac/linux/windows/android/ios

node --version

react version

webpack version

@babel version

@react-google-maps/api version

**Comment by JustFly1984** [comment]
@cuongdevjs I think you can use this https://developers.google.com/maps/documentation/javascript/maptypes as example. you need to set options prop on GoogleMap component
