### ISSUE TITLE
Cannot find name 'google'. 

### ISSUE THREAD

**Issue by kalmndo** [JustFly1984/react-google-maps-api#639]
Cannot find name 'google'. in zoomControlOptions.

i want to change the zoom control to left side.
but when i try on sandbox it works tho, event the typescript still mad with "Cannot find name 'google'".

```
<GoogleMap
  id="circle-example"
  mapContainerStyle={{
    height: "100%",
    width: "100%"
  }}
  zoom={12}
  center={viewport}
  options={{
    streetViewControl: false,
    scaleControl: false,
    mapTypeControl: false,
  zoomControlOptions: {
    position: google.maps.ControlPosition.LEFT_CENTER
  }
}}>
  
</GoogleMap>
```

**Comment by JustFly1984** [comment]
you have to load Google Map component from separate component, if you want to have access to google object. this way it will be accessed only after google script loaded.

**Comment by kalmndo** [comment]
thankyou this is a great library !!

**Comment by gabrielmoncea** [comment]
@JustFly1984 I did exactly that and it's not working

**Comment by gabrielmoncea** [comment]
It looks like the error is in [GoogleMap.tsx](https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/GoogleMap.tsx#L146)

**Comment by lakshmisanthi** [comment]
I am also struct in same like. can you tell how to fix this?

**Comment by JustFly1984** [comment]
please provide minimal reproduction in codesandbox.io

**Comment by lakshmisanthi** [comment]
I tried like below code

`import React, {useEffect, useState} from 'react';
import {withGoogleMap,GoogleMap,InfoWindow, Marker, DirectionsRenderer, Circle} from "react-google-maps";
import MarkerClusterer from "react-google-maps/lib/components/addons/MarkerClusterer";
import MarkerWithLabel from "react-google-maps/lib/components/addons/MarkerWithLabel";
import Swiper from 'react-id-swiper';
import {Button, Image} from 'semantic-ui-react';

const styles = require('../listing/GoogleMapStyles.json');

const PropertyMap = withGoogleMap(props => {//console.log(props)
  let [markers, setmarkers] = useState(props.markers)

  let onDragEnd = (coord) =>{console.log(coord)}
  // console.log(google,"google")
  return(
    <GoogleMap 
      yesIWantToUseGoogleMapApiInternals={true}
      onDragEnd={onDragEnd} 
      defaultOptions={{streetViewControl: false,
        scaleControl: false,
        mapTypeControl: false,
        panControl: false,
        zoomControl: true,
        rotateControl: false,
        fullscreenControl: false,
        gestureHandling: "greedy",
        styles: styles,
        minZoom: 10,
        maxZoom: 18,
      }} defaultZoom={props.defaultZoom} center={props.center}>
        <Circle
              defaultCenter={m.geography}
              radius={props.defaultRadius}
              options={props.options}/>      
    </GoogleMap>
  )
});

export default PropertyMap;`

I need to change the position on map controls (zoom control, Map change, street view controls)

**Comment by JustFly1984** [comment]
code pasted into comment is not readable, nor executable. provide minima; reproduction in codesandbox.io

**Comment by lakshmisanthi** [comment]
Sorry, Please look here
https://codesandbox.io/s/jovial-faraday-cjfsh?file=/src/App.js

**Comment by lakshmisanthi** [comment]
Sorry, please look here,
https://codesandbox.io/s/distracted-lovelace-o91hh

**Comment by JustFly1984** [comment]
You are using outdated library. instead of `react-google-maps` you need to use `@react-google-maps/api` Read docs and look examples in repo.

**Comment by lakshmisanthi** [comment]
Hi JustFly1984,
I have tried with @react-google-maps/api, I can't load even map, still getting google is undefined.

**Comment by lakshmisanthi** [comment]
@JustFly1984  I have tried with @react-google-maps/api. It's loading map, markers and it's working fine. I need MarkerClusterer.  When I am using MarkerClusterer , I am getting google is not defined. check below screen 
![Screenshot from 2020-05-12 15-22-21](https://user-images.githubusercontent.com/19183887/81670225-eeaa4c80-9464-11ea-8b0b-5ffb8e9ef34e.png)

**Comment by reubenkcoutinho** [comment]
This is a good start for a react library for Google Map. Is there any documentation on how to use this when using Typescript. I'm currently facing the same issue as @lakshmisanthi .

@JustFly1984  Please help!

**Comment by vipulm124** [comment]
@

> This is a good start for a react library for Google Map. Is there any documentation on how to use this when using Typescript. I'm currently facing the same issue as @lakshmisanthi .
> 
> @JustFly1984 Please help!

I am also facing the same issue. 
Please help

**Comment by reubenkcoutinho** [comment]
I've fixed this issue by adding `//@ts-ignore`
e.g.
```
const onLoad = (mapInstance: any) => {
    //@ts-ignore
    const bounds = new google.maps.LatLngBounds();
    //do something with bounds
}
```
