### ISSUE TITLE
How to style Autocomplete result items?

### ISSUE THREAD

**Issue by kafkas** [JustFly1984/react-google-maps-api#641]
How do I style Autocomplete predictions shown in [original docs](https://developers.google.com/maps/documentation/javascript/places-autocomplete#style_autocomplete)?

**Comment by gstvribs** [comment]
Using the lib the only way to style result items is override css classes from result search box: https://developers.google.com/maps/documentation/javascript/places-autocomplete#style_autocomplete

**Comment by HawiCaesar** [comment]
@gstvribs is there an example in react ?

**Comment by HawiCaesar** [comment]
I found a way. It seems I had to add the styles in my `index.html`

**Comment by gstvribs** [comment]
You can simply write a css file, for example i use this sass file on my project

`.pac-container {
  position: fixed !important;
  top: auto !important;
  bottom: 0 !important;
  left: 0 !important;
  width: 100% !important;
  height: 156px !important;
  border-top: none !important;

  @media screen and (min-width: global(breakpoint-desktop)) {
    top: calc(100% - 156px) !important;
    bottom: 0 !important;
    margin-top: 0 !important;
  }

  .pac-item {
    max-width: 1216px !important;
    margin-right: auto;
    margin-left: auto;
    padding-left: 16px;
    cursor: pointer;

    @media screen and (min-width: 1024px) and (max-width: 1366px) {
      max-width: 1088px !important;
    }

    @media screen and (min-width: global(breakpoint-desktop)) {
      padding: 0;
    }

    &:nth-child(4),
    &:nth-child(5) {
      display: none;
    }

    & > span {
      color: color(neutral, 08);
      font-weight: fonts(semi-bold);
      font-size: 16px;
      font-family: map-get($fonts, family);
      line-height: 50px;

      .pac-matched {
        color: color(neutral, 06);
        font-weight: fonts(medium);
      }
    }

    .pac-icon {
      display: none;
    }
  }

  &::after {
    height: 0 !important;
    background-image: none !important;
  }
}`
