### ISSUE TITLE
Error 404. A Gatsby App including examples are not there

### ISSUE THREAD

**Issue by DoubleChamp** [JustFly1984/react-google-maps-api#65]
NPM Page: https://www.npmjs.com/package/@react-google-maps/api
Link: https://github.com/JustFly1984/react-google-maps-api/tree/master/examples/react-google-maps-api-gatsby/src/examples

**Comment by JustFly1984** [comment]
https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

**Comment by JustFly1984** [comment]
fixed link in alpha5 branch, tomorrow will publish new version 1.2.0
