### ISSUE TITLE
Can't resolve markerclustererplus

### ISSUE THREAD

**Issue by oscarhou** [JustFly1984/react-google-maps-api#68]
Hi all,
I'm trying to use the module and have installed according the instruction on the docs but am currently getting this error:

./node_modules/@react-google-maps/api/lib/components/addons/MarkerClusterer.js
Module not found: Can't resolve 'markerclustererplus'

It doesn't quite seem to be the same issue as #64 though. Any help would be great thanks

**Comment by uriklar** [comment]
@oscarhou what version are you using? The stable version right now is 1.1.0 (without MarkerClusterer support)
We're working on releasing a stable 1.2.0-alpha

**Comment by oscarhou** [comment]
Ah that makes sense I was using 1.2.0 alpha, I shall try the stable version

**Comment by JustFly1984** [comment]
@oscarhou please try alpha 4, soon will be alpha 5
