### ISSUE TITLE
Calling LoadScript in multiple components

### ISSUE THREAD

**Issue by oscarhou** [JustFly1984/react-google-maps-api#70]
What's the proper way to be able to load the API using LoadScript in different components?
I'm getting the following error when redirecting to different Routes using react-router. 
`google api is already presented`

**Comment by JustFly1984** [comment]
You can't and should not call 2 <LoadScript /> components at the same time, although, you can use as many <GoogleMap /> components inside of <LoadScript /> as you need. This is due to google-maps-api limitations. For example you just can't run 2 maps with different languages, cos google-maps script could be loaded one at the time.

**Comment by JustFly1984** [comment]
@oscarhou 
There should be only one single LoadScript component in react-dom tree at the same time, although you can use as many GoogleMap components as you need (or performance allows). You can see our demo https://react-google-maps-api-gatsby-demo.netlify.com/ with implementation details source code in repo

**Comment by AndyOGo** [comment]
@JustFly1984 
hmh, I face the same issue migrating from original [`withscriptjs`](https://tomchentw.github.io/react-google-maps/#withscriptjs) HoC to `<LoadScript />`.
Originally this was supported, so may could this be considered a regresssion?

**Comment by TkachovaAnna** [comment]
@AndyOGo  I face same problem. Have you found the way to fix this?

**Comment by AndyOGo** [comment]
@TkachovaAnna 
Yes I found a workaround by extending `LoadScript`, as suggested in this comment.
https://github.com/JustFly1984/react-google-maps-api/issues/159#issuecomment-502446663

IMHO, it's not ideal and `LoadScript` should be fixed 🤔 

```js
// @todo: https://github.com/JustFly1984/react-google-maps-api/issues/70
// see: https://github.com/JustFly1984/react-google-maps-api/issues/159#issuecomment-502446663
class LoadScriptOnlyIfNeeded extends LoadScript {
  componentDidMount() {
    const cleaningUp = true;
    const isBrowser = typeof document !== 'undefined'; // require('@react-google-maps/api/src/utils/isbrowser')
    const isAlreadyLoaded =
      window.google &&
      window.google.maps &&
      document.querySelector('body.first-hit-completed'); // AJAX page loading system is adding this class the first time the app is loaded
    if (!isAlreadyLoaded && isBrowser) {
      // @ts-ignore
      if (window.google && !cleaningUp) {
        console.error('google api is already presented');
        return;
      }

      this.isCleaningUp().then(this.injectScript);
    }

    if (isAlreadyLoaded) {
      this.setState({ loaded: true });
    }
  }
}
```

**Comment by JustFly1984** [comment]
@AndyOGo @TkachovaAnna 
You can have only one `<LoadScript />` per application. that the whole point. you can have as many `<GoogleMap />` components as children as you need. There could be only one instance of google-maps-api script, as it works as Singleton. Can't do nothing about it.

**Comment by AndyOGo** [comment]
@JustFly1984 Thanks for your feedback. And thank you very much for your awesome work.

May I ask you kindly to have a look at the above workaround.
`LoadScript` could be a stateful React component, which guarantees that Google-Map's script is injected only once.

**Why we need this?**
Because we dynamically render a UI defined by and API, which can display GoogleMap components at random spots.

Please also note, that the original [`withScriptjs` Higher-Order-Component](https://tomchentw.github.io/react-google-maps/#withscriptjs) did support multiple instances, but only one script injection.

It's certainly possible to improve this, may I ask you to reopen this issue, please?

**Comment by JustFly1984** [comment]
so in your case it is better to use LoadScript as top component in component tree. If you want to make alternative LoadScript, you can create PR and I will merge it and release in next version.

**Comment by TkachovaAnna** [comment]
@AndyOGo  Thank you, that helped!

**Comment by AndyOGo** [comment]
@JustFly1984 Thanks for your quick response.
Though we won't use Google maps at each UI and all components can be arbitrarily nested.
So we want them to scoped together and not scattered at different places in the component tree.

Yeah, an alternative component is a nice idea too 👍

**Comment by liamcmitchell-sc** [comment]
> You can have only one <LoadScript /> per application. that the whole point. you can have as many <GoogleMap /> components as children as you need. There could be only one instance of google-maps-api script, as it works as Singleton. Can't do nothing about it.

Can you document this?

**Comment by JustFly1984** [comment]
@liamcmitchell-sc PR is welcome

**Comment by Angelk90** [comment]
@JustFly1984 , @liamcmitchell-sc , @AndyOGo :

Can anyone help me out, I am not able to solve the problem.

Link: https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-plcof

**Comment by rajitha302** [comment]
Well, I managed to reuse it by loading the  Loadscript inside the index.js by wrapping all components.

**Comment by AKclown** [comment]
Hey how to fix

**Comment by rajitha302** [comment]
> Well, I managed to reuse it by loading the Loadscript inside the index.js wrapping all components.

@AKclown

**Comment by AKclown** [comment]
> Well, I managed to reuse it by loading the Loadscript inside the index.js wrapping all components.

Thanks for the reply, but this way, the google map fails to load and the whole page is available. Is this not a good way? I have tried

**Comment by AKclown** [comment]
I temporarily use the script tag to solve this problem instead of using <LoadScript />

**Comment by AKclown** [comment]
I temporarily use the script tag to solve this problem instead of using <LoadScript />

**Comment by JustFly1984** [comment]
Use latest `useJsApiLoader` hook instead of `LoadScript` component

**Comment by AKclown** [comment]
Thanks for your quick reply, I will try it

**Comment by AKclown** [comment]
I'm late, useJsApiLoader is ok, I hope it can help people who encounter this problem later

**Comment by tomasznguyen** [comment]
When using `useJsApiLoader` in multiple components (some on the same page and some not), `useJsApiLoader` gives me a warning which I cannot suppress. `useLoadScript` does not give me warnings and does exactly the same.

**Comment by JustFly1984** [comment]
You can fail an issue to official repository of js api loader

**Comment by tomasznguyen** [comment]
I have created a component and a hook to simplify integrating Google Maps in your application when you need a map in multiple components. See this [gist](https://gist.github.com/tomasznguyen/ac28b0b3207c08a81687b657a2ce86d6) for the code and a usage example.

@JustFly1984 If interested, I can make a PR.

**Comment by mark-bt** [comment]
> Well, I managed to reuse it by loading the Loadscript inside the index.js wrapping all components.

This works for me as well but then there is the 'Loading...' being displayed across the entire application onLoad

**Comment by obayomi96** [comment]
> > Well, I managed to reuse it by loading the Loadscript inside the index.js wrapping all components.
> 
> This works for me as well but then there is the 'Loading...' being displayed across the entire application onLoad

Same here

**Comment by stesvis** [comment]
Any solution? Happening with v ^2.11.9
