### ISSUE TITLE
Ability to add Custom Markers in google maps api

### ISSUE THREAD

**Issue by MalikBagwala** [JustFly1984/react-google-maps-api#701]
I want to add my own React Components as Markers. like I can do it in [`google-map-react`](https://www.npmjs.com/package/google-map-react)

**Comment by danadn** [comment]
As far as I've seen you only have the possibility of doing it using OverlayView
https://react-google-maps-api-docs.netlify.com/#overlayview

**Comment by MalikBagwala** [comment]
is there any way I could add it?

**Comment by MalikBagwala** [comment]
@danloiterton 
Overlay view did the trick..thanks a lot..I have been scratching my head over this since a long time.
:dagger:

**Comment by davidrhoderick** [comment]
@MalikBagwala how did you use OverlayView to get custom markers to show up?  Did it work with InfoWindows?

**Comment by MalikBagwala** [comment]
@davidrhoderick  I created my own custom component
```jsx
const CustomMarker: React.FC<CustomMarkerProps> = ({
  children,
  top,
  left,
  position,
  style,
  className,
  onClick,
}) => {
  return (
    <OverlayView
      position={position}
      mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
    >
      <div
        className={className}
        onClick={onClick}
        style={{
          ...style,
          // This is set by default in order for top and left to take effect
          position: "absolute",
          top,
          left,
        }}
      >
        {children}
      </div>
    </OverlayView>
  );
};

export default CustomMarker;
```

And yes its your own react component so you can basically do anything with it. (The overlay component takes a *position* param which is basically a javascript object with lat ,lng properties and it renders your own dom element at that co-ordinate

**Comment by Lakshit-Singhal** [comment]
@MalikBagwala I'm also using OverlayView to render the Custom Marker. 

`  
<View style={styles.container}>
      <Script
        url={`https://maps.googleapis.com/maps/api/js?key=${ConfigHelper.getPlacesApiKey()}&libraries=places`}
        onLoad={(): void => setHasScriptLoaded(true)}
      />
      {hasScriptLoaded && (
        <GoogleMapView center={{ lat, lng }} onMapLoadCallBack={handleOnMapLoad}>
          {results.map((property) => {
            if (map) {
              return (
                <CustomMarker
                  position={{ lat: property.latitude, lng: property.longitude }}
                  key={property.id}
                  selected={false}
                />
              );
            }
            return [];
          })}
        </GoogleMapView>
      )}
    </View>
    `
    
    `
interface IProps {
  position: ILatLng;
  selected: boolean;
}

const CustomMarker = (props: IProps): React.ReactElement => {
  const { position, selected } = props;
  useEffect(() => {
    console.log('position => ', position);
  }, []);
  const renderMarker = (isSelected: boolean): React.ReactNode => {
    if (!isSelected) {
      return <View style={styles.marker} />;
    }

    return <View style={styles.selectedMarker} />;
  };

  console.log('position => ', position);
  return (
    <OverlayView position={position} mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}>
      {renderMarker(selected)}
    </OverlayView>
  );
};

const styles = StyleSheet.create({
  marker: {
    ...(theme.circleCSS(16) as object),
    backgroundColor: theme.colors.primaryColor,
  },
  selectedMarker: {
    ...(theme.circleCSS(40) as object),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.markerOpacity,
  },
});
`
