### ISSUE TITLE
I see `utc_offset is deprecated as of November 2019 and will beturned off in November 2020. Use utc_offset_minutes instead` in console

### ISSUE THREAD

**Issue by geryit** [JustFly1984/react-google-maps-api#702]
How can I get rid of this warning?

**Comment by JustFly1984** [comment]
Please provide minimal reproduction in codesandbox.io

**Comment by geryit** [comment]
Sorry here: https://codesandbox.io/s/pensive-liskov-btnyh

**Comment by JustFly1984** [comment]
I do not see the errors you have described in sandbox example, although I see that you have made some  errors. There is no libraries prop on GoogleMap component, only on LoadScript. Also you need to style GoogleMaps component.

Look at my fixed version: https://codesandbox.io/s/small-cookies-tn1l0

**Comment by bockc** [comment]
I also see this warning in the console.

I had the `libraries` prop only in my `useLoadScript` hook, I added it to `<GoogleMap>` and even like that I still see it when I call `getPlaces()` on my StandaloneSearchBox ref.
Looking at your fixed version in codesandbox.io didn't help unfortunately.

Here is a quick snippet showing how I configure the components of this package :
(pastebin link to avoid my message being too long)
https://pastebin.com/PQgCCZA8
The warning occurs when the line 84 of the pastebin is executed.

Is this enough for you to take a look or would you absolutely prefer a codesandbox.io minimal version ?
