### ISSUE TITLE
MouseEvent types are incorrect

### ISSUE THREAD

**Issue by renchap** [JustFly1984/react-google-maps-api#73]
# Please provide an explanation
`onClick` (and other mouse event handlers) `e` argument type is currently `MouseEvent` but should be `google.maps.MouseEvent`

## Your Environment
@react-google-maps/api version: 1.2.0-alpha.8

## How is it behave?
Currently if you define your own `onClick` handler and check the `e` argument, it is a `MouseEvent` from Google Maps SDK, not a browser `MouseEvent`.

For example with
```jsx
<GoogleMap … onClick={(e) => { console.log(e) }} />
```

You get
```
_.wk {latLng: _.P, va: MouseEvent, pixel: _.M, pa: _.M}
  latLng: _.P {lat: ƒ, lng: ƒ}
  pa: _.M {x: 128.37920009601385, y: 111.05081764442744}
  pixel: _.M {x: 326.203125, y: 316.3125}
  va: MouseEvent {isTrusted: false, screenX: 646, screenY: 636, clientX: 646, clientY: 636, …}
  __proto__: Object
```

## How should it behave correctly?
Mouse handler events argument type should be `google.maps.MouseEvent`.
This is also true for other components (like `Marker`).

**Comment by JustFly1984** [comment]
I've fixed types to google.maps.MouseEvent and published alpha.9. Thank you for your findings, keep up!
