### ISSUE TITLE
onXXXChanged are called once when loading the map

### ISSUE THREAD

**Issue by renchap** [JustFly1984/react-google-maps-api#75]
## Your Environment
@react-google-maps/api version: 1.2.0-alpha6

## How is it behave?
I defined `onCenterChanged`, `onZoomChanged` and `onMapTypeIdChanged` on my `GoogleMap` component, and the 3 callbacks are called once when the map is loaded.

Simple repro: 
```jsx
<GoogleMap … onCenterChanged={() => console.log("centerChanged")} />
```

This breaks my app as I need to query the google map object in those callbacks (set using `onLoad`), and it is not yet set when they are called.

## How should it behave correctly?
Those callbacks should only be called when the corresponding events are fired from Google Maps SDK, not on load.

**Comment by renchap** [comment]
My bad, it looks like this is caused by my code which is somehow triggering an option/position/zoom change on load.

**Comment by JustFly1984** [comment]
@renchap Glad your issue is resolved
