### ISSUE TITLE
StandaloneSearchBox

### ISSUE THREAD

**Issue by michaelsync** [JustFly1984/react-google-maps-api#77]
I am trying to use the StandaloneSearchBox as below. 

`import { LoadScript, GoogleMap, InfoWindow, Marker, StandaloneSearchBox  } from '@react-google-maps/api'
`
```
<LoadScript
    id="script-loader"
    googleMapsApiKey="..............."
    language={"en"}
    region={"EN"}
    version={"weekly"}
    libraries={[]}
    onLoad={() => console.log("script loaded")}
    loadingElement={<div>Loading...</div>}
  >
    <GoogleMap
      id="basic-map-example"
      mapContainerStyle={{
        height: "800px",
        width: "100%"
      }}
      zoom={9}
      options={{gestureHandling:'greedy'}}
      center={cbdCoordinates}
    >
      <StandaloneSearchBox>
          <input
            type='text'
            placeholder='Customized your placeholder'
          />
        </StandaloneSearchBox>  
    </GoogleMap>
  </LoadScript>
```

I am getting this error. 

![image](https://user-images.githubusercontent.com/192911/55305549-4c175000-5494-11e9-8daa-5341e4dd014a.png)

## Environment

{
  "name": "react-map-sample",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@react-google-maps/api": "^1.1.0",
    "@types/googlemaps": "^3.30.19",
    "bootstrap": "^4.3.1",
    "json-typescript-mapper": "^1.1.3",
    "react": "^16.8.4",
    "react-bootstrap": "^1.0.0-beta.5",
    "react-dom": "^16.8.4",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts-ts": "3.1.0",
    "whatwg-fetch": "^3.0.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/bootstrap": "^4.3.0",
    "@types/jest": "^24.0.11",
    "@types/node": "^11.11.3",
    "@types/react": "^16.8.8",
    "@types/react-dom": "^16.8.2",
    "@types/react-router-dom": "^4.3.1",
    "typescript": "^3.3.3333"
  }
}

**Comment by uriklar** [comment]
![image](https://user-images.githubusercontent.com/2545447/55306339-9086f980-545c-11e9-914e-28ae74c51aa4.png)
Well, did you? :-)

You need to include the places library when loading the script as so:
```
<LoadScript
    ...
    libraries={["places"]}
    ...
  >
```

**Comment by michaelsync** [comment]
Thanks.  I missed out that part. 

The auto-complete doesn't work tho. What permission do I need to enable? Geolocation?

> 
This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_ For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

![image](https://user-images.githubusercontent.com/192911/55307035-8fc08880-5499-11e9-8d3a-276e554076ff.png)

**Comment by michaelsync** [comment]
Thanks, uriklar.
