### ISSUE TITLE
InfoBox error on language change

### ISSUE THREAD

**Issue by samuelpucat** [JustFly1984/react-google-maps-api#791]
InfoBox causes error `InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama` on language change and does not render

https://codesandbox.io/s/gifted-violet-gp1cm?from-embed

**Comment by JustFly1984** [comment]
@samuelpucat please debug and provide a PR if you can.

**Comment by Diaver** [comment]
Hey!
The same issue. It doesn't work with react-router with user walks between pages (forward and backward).
@samuelpucat Did you find any solution?

**Comment by JustFly1984** [comment]
@Diaver infobox is a fork, which has been upgraded with typescript by us as is. If you are interested enough, you can debug and provide PR with fix.

**Comment by Diaver** [comment]
@JustFly1984 
Can you please point me how to run and debug this?
I was trying to do it, but didn't find any debug/start run command.

Thanks!

**Comment by Diaver** [comment]
Trying debug GoogleApi to understand what exactly wrong with it, but it is really hard to understand how it is working with obfuscated code:
![image](https://user-images.githubusercontent.com/644716/81134123-c16c1480-8f21-11ea-9a45-1fa2ca43600c.png)
Interesting moment here: we are trying set Map, and before that checking instance of Map which is looks good for me and for debugger initially, but this throw exception:
![image](https://user-images.githubusercontent.com/644716/81134286-45260100-8f22-11ea-9050-7d05acfa038f.png)

**Comment by JustFly1984** [comment]
@Diaver  you can run `gatsby-example`, and change @react-google-maps/api import to `packages/react-google-maps-api/dist` - you need to build it first though. You can create your own example, and add it to the list of existing.

I guess we should make typescript developing environment, so it will be possible to import typescript from src directly without build, or use ts-node in current gatsby-example.

If you want you can create new package based on create-react-app with typescript support if it is easier for you.

**Comment by Diaver** [comment]
@JustFly1984  thanks! I just replaced modified code directly into my node_modules and it works, but I didn't find any bugs in the code. For me it is looks good and we always pass the same object into:
` InfoBox 
 this.setMap(map)`

Dark magic :(

**Comment by Diaver** [comment]
3 days of debugging without any result.
Just in case: issue is not related just to language - InfoBox disappear after any state change by very strange reason:
![image](https://user-images.githubusercontent.com/644716/81256468-960b2780-8ffe-11ea-91bf-dcfa47afa2a2.png)
it is allow to set map first time, but throw exception in second time when state get changed :(

**Comment by JustFly1984** [comment]
well, it is original bug, I had to place `// @ts-ignore` comment as I was in hurry. I had not changed any logic, just added types everywhere I could, and unfortunately here I had no time to investigate back then. Wish you the luck to solve your issue. I would recommend you to remove my comment and fix the code.

**Comment by MyriamMansouri** [comment]
Hi, I got the same error message while using Infobox + react-router-dom when using router to navigate across the app. Here is a minimal reproduction of the bug : 
https://codesandbox.io/s/infobox-yuyjw
Thx

**Comment by Diaver** [comment]
> Hi, I got the same error message while using Infobox + react-router-dom when using router to navigate across the app. Here is a minimal reproduction of the bug :
> https://codesandbox.io/s/infobox-yuyjw
> Thx

I spent 3 days to understand what is going, but the problem is exception came from obfuscated google map library and I just gave up.

**Comment by MyriamMansouri** [comment]
Yes I read thread. I dug the issue hoping someone would have a new perspective on this. Thanks for taking the time to answer.

**Comment by aldyadk** [comment]
@Diaver @MyriamMansouri 
i use 'useLoadScript' as a workaround 

https://codesandbox.io/s/priceless-snyder-v1zij?file=/src/Map.js

**Comment by samuelgrigolato** [comment]
> @Diaver @MyriamMansouri
> i use 'useLoadScript' as a workaround
> 
> https://codesandbox.io/s/priceless-snyder-v1zij?file=/src/Map.js

This saved my life :).

This problem only really started happening when I used the InfoBox, I also have a lot of Marker instances but they do not cause the issue even when I navigate back and forth.

**Comment by gege-hoho** [comment]
> useLoadScript

Thank you! Solved it for me!

**Comment by guilhermepontes** [comment]
The solution is the same as above, but I think it's easier to read:

```
import React from 'react';
import Alert from '@material-ui/lab/Alert';
import Paper from '@material-ui/core/Paper';
import { Loading } from '../loading/Loading';
import { GoogleMap, useLoadScript } from '@react-google-maps/api';

interface Coordinates {
  lat: number;
  lng: number;
}

interface MapProps {
  width?: string;
  height?: string;
  zoom?: number;
  center?: Coordinates;
  id?: string;
}

const Map: React.FC<MapProps> = ({
  id = 'google-maps',
  width = '25rem',
  height = '25rem',
  zoom = 16,
  center,
  children,
  ...rest
}) => {
  const { isLoaded, loadError } = useLoadScript({
    googleMapsApiKey: key,
  });

  return (
    <>
      {!isLoaded && <Loading />}

      {loadError && (
        <Alert severity="error">We couldn't load the map.</Alert>
      )}

      {isLoaded && !loadError && (
        <Paper elevation={3}>
          <GoogleMap
            id={id}
            mapContainerStyle={{ width, height }}
            zoom={zoom}
            center={center}
            {...rest}
          >
            {children}
          </GoogleMap>
        </Paper>
      )}
    </>
  );
};

export { Map };

```
