### ISSUE TITLE
panBy() API missing from the GoogleMap object

### ISSUE THREAD

**Issue by PerthCharern** [JustFly1984/react-google-maps-api#794]
## Please provide an explanation

`panBy()` missing from the GoogleMap object in https://github.com/JustFly1984/react-google-maps-api/blob/1ddc54799df63fa7a8ccb53de95b50611d1d1ea0/packages/react-google-maps-api/src/GoogleMap.tsx

https://developers.google.com/maps/documentation/javascript/reference/map#Map.panBy

## How should it behave correctly?

`panBy()` should be added to the API.

**Comment by PerthCharern** [comment]
I noted that only `panTo` seems to be implemented for the GoogleMap object as a wrapper around the under lying Map API `panTo(x,y)`. 

This wrapper does not really do much since we can already use `onLoad` function to get out `mapRef` and call any APIs directly (e.g. `panTo`, `panBy`, etc.)

Maybe we should remove `panTo` instead (though that would be a breaking change). It is a little confusing to have multiple ways of access these APIs, and to only have `panTo` in the top-level object.

**Comment by JustFly1984** [comment]
@PerthCharern it was a PR by someone who needed that functionality.
