### ISSUE TITLE
Map re-centers on initial coordinates when setState() is called

### ISSUE THREAD

**Issue by rawtaz** [JustFly1984/react-google-maps-api#803]
## Please provide an explanation

In a simple custom component, having just a GoogleMap and a few Markers, whenever `setState(…)` is called, the map scrolls/pans/centers on the coordinates that are set as the initial centering coordinates for the map.

## Your Environment

os:  Microsoft's .NET Core Linux container, based on Debian 10 (Buster).

node --version:  v13.11.0

react version:  16.13.1

webpack version:  3.8.1

(@)babel version:  6.26.0 (babel-core and babel-runtime)

@react-google-maps/api version:  1.8.6

## How is it behave?

The map re-centers on the initial center coordinates when `setState(…)` is called in the component.

## How should it behave correctly?

The map should not re-center when `setState(…)` is called in the component :)

## Basic implementation of incorrect behavior in codesandbox.com

Here is a very small piece of code that shows the problem:  https://codesandbox.io/s/confident-davinci-fxmj7

I have stripped out irrelevant things. As you can see in `App.js` it's just a map without anything in it, and with a timer that every five seconds calls `setState(…)` without anything weird going on.

To reproduce: Let the map load, check the console for the output of `[]`, then pan the map a bit to the side, and next time the `[]` is output, watch the map reset to the initial coordinates.

To verify that it's triggered by `setState(…)`, uncomment line 19 in the `App.js` code, reload the browser preview window, and run the reproduction steps above - the map will no longer re-center on the initial coordinates when `setState(…)` is run.

## Other comment

Before using `@react-google-maps/api` we were using another Google Maps React library, and didn't experience this (we switched only that library for this one, and this re-centering started happen). For that reason I believe it's something that's caused by this library. I'm open to being wrong, of course!

**Comment by leandrosalgado** [comment]
The thing is, you're creating a new object with your center every time you re-render then
it passes a new reference to the Map component, therefore it triggers the centering logic.

I have changed your code and it should work as you expect:
https://codesandbox.io/s/hopeful-swirles-6yxlq

**Comment by rawtaz** [comment]
@leandrosalgado Thank you for that fix, it totally works.

I'm probably ignorant, but is this something that is common in React rather than specific in this library? I presume so, yet I'm highly surprised as to how a static value such as `{ lat: 56.687222, lng: 12.9 }` can trigger the creation of a new object - why is that? It's a static value, it doesn't change, just as the value 10 for `zoom` doesn't change.

Also, it feels rather unclean to put an initialization value in the state. I mean, those *initial* coordinates aren't something that should be considered stateful, it doesn't make sense to put them in a state entry, don't you think?

Clearly I'm having very different expectations on React than what the world does :D

**Comment by rawtaz** [comment]
PS: FWIW, the previous library we used was `google-maps-react` and the corresponding code (that didn't let `setState()` re-center) was this:

~~~
<Map google={this.props.google} onReady={this.onMapReady} initialCenter={{lat: 57.687222, lng: 13.000000}} zoom={10}>
~~~

This makes me wonder; Is there anything similar in `@react-google-maps/api` that let's you provide those *initial* values without putting it in the state? And I have previously searched for it, without finding anything.

**Comment by leandrosalgado** [comment]
@rawtaz that's common in React, the value isn't static because the render method creates a new object every time it's called, thus the reference of the previous center isn't the same. 

You can test it in your console:
![image](https://user-images.githubusercontent.com/5623011/78565536-5cd47180-781e-11ea-8aab-0fcf7eb0b29b.png)

However, with primitive types, it works as you thought.

Regarding the center in the state, I agree and you could have this default center as a const variable outside of the Class Component or as a property of the component.

https://codesandbox.io/s/cranky-euler-d7xt3
https://codesandbox.io/s/interesting-maxwell-yx431

- initialCenter
As far as I know, this library doesn't have a default center property.

**Comment by JustFly1984** [comment]
count it as closed

**Comment by rawtaz** [comment]
@leandrosalgado Thanks for the clarification. It makes sense regarding the object, I guess I was just expecting some magic to be done by React :-) This is what I get for diving head first into an app without reading more (I did read some) about the fundamentals of React and related stuff. Cheers!

**Comment by rawtaz** [comment]
Just one last note to any other newbie that comes across this: The reason I was seeing re-centering with this library and not the previous one is simply that the previous one more specifically handles the centering property, so it takes care to treat it specifically as an *initial* center. This one doesn't (which I'm not saying is a bad thing).

**Comment by jimmypoulsen** [comment]
> The thing is, you're creating a new object with your center every time you re-render then it passes a new reference to the Map component, therefore it triggers the centering logic.
> 
> I have changed your code and it should work as you expect: https://codesandbox.io/s/hopeful-swirles-6yxlq

This saved my evening ... Thank you so much @leandrosalgado!
