### ISSUE TITLE
StreetViewService onLoad doesn't work

### ISSUE THREAD

**Issue by taroosg** [JustFly1984/react-google-maps-api#837]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Please provide an explanation

I want to use streetViewService, but the onload event does not work.
Seems to be resolved in issue #446 , but not reflected in my package.

I've tried removing and reinstalling other versions but it didn't improve.

## Your Environment

os: mac/linux/windows/android/ios
macOS 10.15.4

node --version
v12.15.0

react version
16.13.1

@react-google-maps/api version
1.8.6

## How is it behave?

The problem in in `react-google-maps-api/packages/react-google-maps-api/src/components/streetview/StreetViewService.tsx`

Thiis is the newest code from Github.
<img width="558" alt="Screen Shot 2020-04-14 at 2 13 40" src="https://user-images.githubusercontent.com/28992410/79141982-c7c11200-7df5-11ea-91da-a07484346e5b.png">

I installed by `$ npm install @react-google-maps/api`

This is my code in node_modules. ` this.setStreetViewServiceCallback` does not exist.
<img width="832" alt="Screen Shot 2020-04-14 at 2 03 42" src="https://user-images.githubusercontent.com/28992410/79141829-803a8600-7df5-11ea-95b1-4102acab200f.png">

## How should it behave correctly?

The correct code above is installed

**Comment by JustFly1984** [comment]
@taroosg I have published new version 1.8.7 - please check if it works for you now.

**Comment by taroosg** [comment]
I installed version 1.8.7. It seems installed correctly.
This is my `package.json` file.
<img width="593" alt="Screen Shot 2020-04-22 at 10 11 48" src="https://user-images.githubusercontent.com/28992410/79929824-e4a6b680-8481-11ea-9876-bbbed6869ca6.png">

But it doesn't work. It was not updated at `/node_modules/@react-google-maps/api/src/components/streetview/StreetViewService.tsx`.
(at line 39)

<img width="827" alt="Screen Shot 2020-04-22 at 10 12 22" src="https://user-images.githubusercontent.com/28992410/79929917-28012500-8482-11ea-8abf-992c5d331bef.png">

**Comment by JustFly1984** [comment]
released 1.8.9, please test again

**Comment by taroosg** [comment]
I installed v1.9.0 and it works!

Thank you for your excellent job!!
I love this API :-)

**Comment by JustFly1984** [comment]
closing
