### ISSUE TITLE
StandaloneSearchBox tutorial not working

### ISSUE THREAD

**Issue by GleidsonDaniel** [JustFly1984/react-google-maps-api#84]
Hi, I'm just trying to implement the component.

I tried recreating the example in the demo but I'm unable to get any response.

I thought maybe it had something to do with the application I'm running it in, but I also could not get the example working in a code sandbox.

`Uncaught TypeError: _this3.searchBox.getPlaces is not a function`

![Screenshot_1](https://user-images.githubusercontent.com/18687097/55561104-faefa200-56c7-11e9-8f2a-cbd89fbd65e7.png)

The code:

```
<StandaloneSearchBox
              ref={ref => (this.searchBox = ref)}
              onPlacesChanged={() => console.log(this.searchBox.getPlaces())}
            >
              <input
                type="text"
                placeholder="Customized your placeholder"
                style={{
                  boxSizing: `border-box`,
                  border: `1px solid transparent`,
                  width: `240px`,
                  height: `32px`,
                  padding: `0 12px`,
                  borderRadius: `3px`,
                  boxShadow: `0 2px 6px rgba(0, 0, 0, 0.3)`,
                  fontSize: `14px`,
                  outline: `none`,
                  textOverflow: `ellipses`,
                  position: 'absolute',
                  left: '50%',
                  marginLeft: '-120px'
                }}
              />
 </StandaloneSearchBox>
```

**Comment by uriklar** [comment]
Hi @GleidsonDaniel. There's an open PR that updates the example to a working example.
Until version 1.2.0-alpha14 is released, please use 1.2.0-alpha11 and change ref to be ```onLoad```

onLoad accepts a function that is called with the searchBox instance once it's loaded. You can then call getPlaces on that instance

**Comment by uriklar** [comment]
Please try latest version (example has been updated as well)

**Comment by joecees3** [comment]
sdffdsfsfsdfsdfsdfsdfsdfsdfsdfsdfsdfdfdfdfdfdfdfdfdfdfdffdfdfdfdfdfdfdfdfdfdfdfdfdfdfdfdfdfdfvmnzvxcmmc,xcnm,cxv,mcv,xcv,m,vcx,nvcx,cvx,mvcx,mvcx,vcx,vxc,mxcvxcv,mvxc,vxc,vxcnmnvcx,nvxc,mvcx,vcx,nvcx,mvxc,nvcx,nxvc,mvxcn,vxc,cxvnxcv,nxcvm,xcxcvn,xcv,mvxc,ncxvn,cxvnxvc,vcxn,vcx,vcxn,vcxm,vxc,nvxcvxcmn,xcv,vxcn,vxcnvcx,vxcxcv,mvxc,nvc,ncxn,vcxcxv,mncvx,nvxcn,vcx,ncxvn,vcx,ncxv,ncxv,ncvxncvxvc.vxcncvx,cvx,ncvx,nvcx,nvcx,nvcx,mvcx,ncvxn,vcx,nvcx,ncxv,cxvn,cvx,ncxv,cxvn,cvxn,vcxn,cv,ncxv,nxcv,cxvn,cvxnx,ncvx,ncvxn,cvxn,cxv,nn,cvxmn,vc,xvcn,cvx,cn,vcxn,nvxcn,cn,cn,vxcn,,vnc,xvmncvx,ncv,ncvx,nvcx,nvcx,ncvx,,nv,c,vcx,n,n,vn,,cxvn,vcx,ncv,n,ncx,nvc,ncx,ncxv,nxcv,c,cnxcv,xcvn,vcxmn,n,,,cvn,cv,cvx,cm,nv,cxv,nxcvcx,nm,cn,vcxn,n,nc,ncxn,vn,n,,nvxc,ncvn,,
