### ISSUE TITLE
Removing Top Blocks

### ISSUE THREAD

**Issue by ZefirTheFear** [JustFly1984/react-google-maps-api#847]
Hello!
How can i get rid of these blocks? Cant find it in docs.
![qwe](https://user-images.githubusercontent.com/47114687/79311654-705e9700-7f06-11ea-8db3-704109ed4a4e.jpg)

**Comment by ZefirTheFear** [comment]
<GoogleMap
          options={{
          fullscreenControl: false,
          mapTypeControl: false
        }}
/>

**Comment by JustFly1984** [comment]
Please cache options object in const outside of component scope, and install Eslint-plugin-react-perf
