### ISSUE TITLE
Marker clusterer with infowindow throws error

### ISSUE THREAD

**Issue by AshwinTayson** [JustFly1984/react-google-maps-api#854]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Your Environment

os: Windows

node: 12.16.0

react version: 16.7.0

react-scripts: 3.4.0

@babel version: 7.8.7 Runtime

@react-google-maps/api version: 1.8.6

## How is it behave?

If I create a Infowindow with MarkerCluster the app crashes with the following error

> Cannot read property 'getSouthWest' of null
> at Clusterer.createClusters (https://ir5ks.csb.app/nodemodules/
> react-google-maps/marker-clusterer/dist/markerclusterer.cjs.development.js:953:30
> at Clusterer.redraw (https://ir5ks.csb.app/node_modules/
> react-google-maps/marker-clusterer/dist/markerclusterer.cjs.development.js:853:10
> at Gi.eval (https://ir5ks.csb.app/node_modules/
> react-google-maps/marker-clusterer/dist/markerclusterer.cjs.development.js:527:13
> qe.H
> https://maps.googleapis.com/maps/api/js?v=weekly:187:294
> Object..N.trigger
> https://maps.googleapis.com/maps/api/js?v=weekly:184:157
> b
> https://maps.googleapis.com/maps-api-v3/api/js/40/9/map.js:32:165
> This screen is visible only in development. It will not appear if the app crashes in production.
> Open your browser’s developer console to further inspect this error.
> This error overlay is powered by react-error-overlay used in create-react-app.

## How should it behave correctly?
It should open the infowindow without any problems

## basic implementation of incorrect behavior in codesandbox.com

https://codesandbox.io/s/react-google-maps-api-qjudu

**Comment by JustFly1984** [comment]
Sorry for your issue, the markerclusterer code was copied as is from previous package, and typescript added on top. You can fork our repo, create your example in gatsby-example package and debug it. Your PR is welcome
