### ISSUE TITLE
How to sync map coordinates with marker coordinates ?

### ISSUE THREAD

**Issue by AdiBevoor** [JustFly1984/react-google-maps-api#855]
Currently I want sync my map coordinates with marker coordinates when map is dragged around.
Right now react is breaking the app saying its too many updates.

## Your Environment

os: windows

react version 16.12

Here is my repo 
https://codesandbox.io/embed/unruffled-haze-dugvw?fontsize=14&hidenavigation=1&theme=dark

**Comment by JustFly1984** [comment]
I have looked at your example and I think I solved it: https://codesandbox.io/s/frosty-bash-e6sjw?file=/src/App.js

**Comment by AdiBevoor** [comment]
@JustFly1984  Thanks for taking a look at this. Unfortunately in my set up map doesn't move at all. When I remove setState inside of `onMapDrag` then map moves and coordinates are different. But If I leave the setState then map doesnt move and coordinates stays same always.

**Comment by AdiBevoor** [comment]
@JustFly1984  Nevermind I know why you have set center to zero now. In my case I needed center to be dynamic but only when user selects a place.  So I tweaked a little bit like [this ](https://codesandbox.io/s/brave-driscoll-un9o1?fontsize=14&hidenavigation=1&theme=dark).
Thanks a lot now I know how to use useCallback properly and its use case :D. Thanks again saved lots of time 😄
