### ISSUE TITLE
Bug - on maxZoom change, redraw clusters

### ISSUE THREAD

**Issue by razbensimon** [JustFly1984/react-google-maps-api#865]
# Issue

when `maxZoom` prop changes, a redraw of the clusters should happen.

@react-google-maps/api@1.8.6 

## How is it behave?

markers / clusters not changed / redraw.

## How should it behave correctly?
markers and clusters should changed / redraw.

**Comment by JustFly1984** [comment]
please provide minimal reproduction in code sandbox.io
