### ISSUE TITLE
Bug - onZoomChanged triggered before onLoad

### ISSUE THREAD

**Issue by razbensimon** [JustFly1984/react-google-maps-api#866]
# Issue 
`onZoomChanged` event callback can triggered before onLoad callback!

## Your Environment
@react-google-maps/api@1.8.6

## How is it behave?
`onZoomChanged` event callback can triggered before onLoad callback!

## How should it behave correctly?
`onZoomChanged` event callback should not trigger before `onLoad`

**Comment by JustFly1984** [comment]
please provide minimal reproduction in code sandbox.io
