### ISSUE TITLE
LoadScript error when unmounting (script tag with null src)

### ISSUE THREAD

**Issue by janek-bieser** [JustFly1984/react-google-maps-api#867]
First of all, thanks for this library :)

## Problem Description

When `LoadScript` component gets unmounted I get the the following Error:
```
TypeError: Cannot read property 'includes' of null
```

This happens on the marked line:
```js
Array.prototype.slice.call(document.getElementsByTagName('script')).filter(function filter(script) {
--> return script.src.includes('maps.googleapis');
}).forEach(function forEach(script) {
    if (script.parentNode) {
        script.parentNode.removeChild(script);
    }
});
```

As far as I can tell [this is the corresponding source line](https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/LoadScript.tsx#L136)

In my case I have a `script` on the page with a `src` attribute of `null`. Why the `src` is `null` and not just an empty string like other `script` tags without a `src` attribute, I don't know. This `script` tag is created by a third party service.

## Solution

We can replace the linked line above with:
```js
return script.src && script.src.includes("maps.googleapis")
```

Let me know if you need more details or anything is unclear.
Thanks!

**Comment by JustFly1984** [comment]
@janek-bieser You can clone the repo and make a PR, I will merge and release new version

**Comment by janek-bieser** [comment]
@JustFly1984  I created the PR. I could not get the build working unfortunately, and didn't have time to investigate further. So I did not test my change yet. Is it possible for you to release a new alpha version so I can test it with my current project?

**Comment by JustFly1984** [comment]
@janek-bieser please test 1.8.8-alpha although I would write an issue to the lib which makes src null.

**Comment by janek-bieser** [comment]
@JustFly1984 1.8.8-alpha fixes my problem, thank you!

**Comment by JustFly1984** [comment]
@janek-bieser let this issue alive, see if somebody else complains

**Comment by JustFly1984** [comment]
@janek-bieser  btw can you name this 3rd party service?

**Comment by janek-bieser** [comment]
Its a client project so I'm not sure how specific I can be, sorry. Its some kind of Cookie Layer service loaded via Google Tag Manager. I will try to find out if its possible to contact the devs of this service.

**Comment by JustFly1984** [comment]
closing issue, will repoen if needed
