### ISSUE TITLE
Problem with onPlaceChanged

### ISSUE THREAD

**Issue by gstvribs** [JustFly1984/react-google-maps-api#869]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Please provide an explanation

the onPlaceChanged is not working properly, in 100% of cases, in our experience about of 8% of users are facing the problem that the google maps api lat and lng values are 0

## Your Environment

os: widows

node --version: v12.14.1

react version: 16.12.0

webpack version: xxx (react-scripts latest version)

@babel version: xxxx (react-scripts latest version)

@react-google-maps/api version: 1.8.3

## How is it behave?

When onPlaceChanged has been called the values lat() and lng() are returned with 0

```
const onPlaceChanged = async () => {
    if (autoComplete) {
      const places = autoComplete.getPlace();

      if (places.address_components) {
        const map = {
          address: places.formatted_address,
          latitude: places.geometry.location.lat(),
          longitude: places.geometry.location.lng(),
        } as CustomerAddressState;
   }
}
```

## How should it behave correctly?

The values could not be 0, there is any way that i could treat this behavior?

**Comment by lluisrojass** [comment]
Can you provide the props you pass to Autocomplete?

**Comment by gstvribs** [comment]
sorry about issue, this problem is not related to the library, but with how i unmounted the component : )
