### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fromLatLngToDivPixel' of undefined

### ISSUE THREAD

**Issue by capaj** [JustFly1984/react-google-maps-api#875]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

## Your Environment

os: mac/linux/windows/android/ios

node --version

react version

webpack version

@babel version

@react-google-maps/api version

## How is it behave?

![image](https://user-images.githubusercontent.com/1305378/81169762-ac32cc80-8f99-11ea-8aa7-a5c2a5365aa3.png)

```
Uncaught TypeError: Cannot read property 'fromLatLngToDivPixel' of undefined
    at reactgooglemapsapi.esm.js:2332
    at reactgooglemapsapi.esm.js:2350
    at t.n.onPositionElement (reactgooglemapsapi.esm.js:2424)
    at Object.n.draw (reactgooglemapsapi.esm.js:2433)
    at reactgooglemapsapi.esm.js:2467
    at r (helpers.js:71)
```
## How should it behave correctly?
should not throw type error

**Comment by JustFly1984** [comment]
please provide minimal reproduction in codesandbox.io

**Comment by hnq90** [comment]
I got same issue.

**Comment by JustFly1984** [comment]
@capaj  @hnq90 please provide minimal reproduction in codesandbox.io

**Comment by capaj** [comment]
will try, no promises. It might be easier for me to debug it locally and report back my findings.

**Comment by JustFly1984** [comment]
You can fork the repo, and use react-styleguidist with yarn docs:dev to run live editing on src in packages/react-google-maps-api, and provide a PR

**Comment by aleksandrlat** [comment]
I suspect this PR https://github.com/JustFly1984/react-google-maps-api/pull/871 caused the issue
