### ISSUE TITLE
Getting many typescript errors from the react-google-maps-api node_module

### ISSUE THREAD

**Issue by pubodanee93** [JustFly1984/react-google-maps-api#878]
## Please provide an explanation
I'm getting so many types errors when trying to integrate the react-google-maps-api to a react project. I have attached a screenshot for  reference.

## Your Environment

os: windows

node --version - v12.16.1

react version - v16.13.1

webpack version - v4.43.0

@react-google-maps/api version - v1.9.0

## How is it behave? Giving many types errors.

![image](https://user-images.githubusercontent.com/13557939/81375659-9f3fe580-911f-11ea-920a-8eb0af40f4e7.png)

**Comment by JustFly1984** [comment]
I guess you need to add `@types/google-maps-api`

**Comment by pubodanee93** [comment]
@JustFly1984 It gives 404 for when I try to install @types/google-maps-api. I'm getting type errors from @react-google-maps/api, @react-google-maps/infobox and @react-google-maps/marker-clusterer.

**Comment by JustFly1984** [comment]
@pubodanee93 can you provide minimal reproduction repository?

**Comment by pubodanee93** [comment]
@JustFly1984 https://drive.google.com/drive/folders/1vjxsiXhvH22o3nVLVuR3u1p-jTHL8nsz

**Comment by JustFly1984** [comment]
please provide the link to public guthub repository

**Comment by breeze9527** [comment]
Maybe you should install `@types/googlemaps` as your devDependencies
https://www.npmjs.com/package/@types/googlemaps
