### ISSUE TITLE
I cannot get google.maps.PolyMouseEvent from Polygon, I see code  has it,but not use.

### ISSUE THREAD

**Issue by huaSoftware** [JustFly1984/react-google-maps-api#885]
I cannot get google.maps.PolyMouseEvent from Polygon, I see code has it,but not use. MouseEvent cannot find  Polygon position. Why code declare don't use it.
```
interface PolyMouseEvent extends MouseEvent {
        edge?: number;
        path?: number;
        vertex?: number;
    }
```

**Comment by JustFly1984** [comment]
@huaSoftware please provide minimal reproduction in codesandbox.io
