### ISSUE TITLE
Cannot getBounds on GoogleMap ref

### ISSUE THREAD

**Issue by zacharymostowsky** [JustFly1984/react-google-maps-api#887]
## Description
I am trying to get the current bounds of my GoogleMap object when an event happens (onBoundsChanged, onSubmit of a form, etc.). I am getting the following error -

```Property 'getBounds' does not exist on type 'GoogleMap'.ts(2339)```

I have also tried several other variations including ```useGoogleMap``` and ```useState```. When I tried ```useGoogleMap``` I got error -
```useGoogleMap needs a GoogleMap available up in the tree````

```useState``` resulted in similar issue with not being able to find method getBounds.

I am happy to other suggestions. Thanks in advance for the help.

## Environment

os: windows

node --version: v12.16.1

react version: 16.13.1

webpack version: I am unfamiliar with this

@babel version: I am unfamiliar with this

@react-google-maps/api version: 1.9.1

## How is it behave?
I can do ```console.log(map.current)``` but then I get error message about ```getBounds()``` not existing on type.

## How should it behave correctly?
I want to be able to get the bounds from the map ref.

## basic implementation of incorrect behavior in codesandbox.com
[link to sandbox](https://codesandbox.io/s/flamboyant-lehmann-tfhlh?file=/src/App.tsx)

**Comment by JustFly1984** [comment]
@zacharymostowsky  As it is explained in migration guide we do not use ref to get an instance, we are using onLoad callback. Also your types was incorrect. You have to install npm package `@types/googlemaps` to use correct typings. https://codesandbox.io/s/wispy-snow-mr5po is the link to my working fork for your functionality.

**Comment by JustFly1984** [comment]
please consider to donate to patreon.com/JustFly1984

**Comment by zacharymostowsky** [comment]
Thank you. Works perfectly. Sorry for not picking that up.
