### ISSUE TITLE
Property 'google' does not exist on type 'Window & typeof globalThis'.  TS2339

### ISSUE THREAD

**Issue by kanso-git** [JustFly1984/react-google-maps-api#889]
I have created a react app using npx create-react-app --template typescript , 
and I have integreated  the brand new  "@react-google-maps/api": "^1.9.2",
The map is showing well, but after adding my marker  I tried to scale the size of my icon marker uisng the  scaledSize: new window.google.maps.Size(30, 30) but the code is not compiling anymore
code is below:
```
<Marker
                            key={marker.id}
                            position={{
                                lat: marker.latitude,
                                lng: marker.longitude,
                            }}
                            onClick={() => {
                                setSelected(marker)
                            }}
                            icon={{
                                url: tvEmptyIcon,
                                scaledSize: new window.google.maps.Size(30, 30), //error
                            }}
                        />
```

The error is : Property 'google' does not exist on type 'Window & typeof globalThis'.  TS2339
this is mainly when using  scaledSize: new window.google.maps.Size(30, 30).

## here below the details about my dev environment

os: windows
node --version: v10.16.3
react version : create-react-app using typescript :  react version is : ^16.13.1

@react-google-maps/api version :  "@react-google-maps/api": "^1.9.2",

![react-google-maps_error](https://user-images.githubusercontent.com/2843192/82879116-ccbcc980-9f3c-11ea-8f38-293b51ef0318.png)

**Comment by JustFly1984** [comment]
you can't use google object until LoadScript is finished loading google api script, hence you need to extract your logic to separate component. please rovide minimal reproduction in codesandbox.io, or look for similar solved issues.

**Comment by a-chris** [comment]
write is as 
`(window as any).google.maps.wahever`
or install 
`@types/googlemaps`

**Comment by JustFly1984** [comment]
google does not exists until LoadScript async load script, script executes, and only after LoadScript renders its children. You have to extract children to another javascript file, so it does not executed before script is loaded.

installing types is also good.

I would recommend to use eslint with plugins plugin-plugin-react-perf.
