### ISSUE TITLE
How to reset polygon when polygon is drawn using drawing manager?

### ISSUE THREAD

**Issue by AarjuRabadiya** [JustFly1984/react-google-maps-api#891]
I draw a polygon using a drawing manager. After reset button click I want to reset polygon but if I set the city same as the previous one then automatically polygon is drawn.  

[googleMapDemo.txt](https://github.com/JustFly1984/react-google-maps-api/files/4686675/googleMapDemo.txt)

**Comment by JustFly1984** [comment]
@aarazoo  please provide minimal reproduction at codesandbox.io

**Comment by aarazoo** [comment]
@JustFly1984 Please check this [](https://codesandbox.io/s/google-mapdemo-jj2ri?file=/public/index.html)

**Comment by JustFly1984** [comment]
@aarazoo  there is an error in `react-google-autocomplete` related to Strict mode, I'm recommending to post an issue in their repository.

In codesandbox.io you don't need to enter google maps api key, it is free to use without a key.

I do not have time right now to go through everything, but I've started to work on fork of your code sandbox.

**Comment by aarazoo** [comment]
@JustFly1984 I updated code in sandbox so please check this link :
 https://codesandbox.io/s/google-mapdemo-jj2ri?file=/public/index.html

Drawing manager is not reset when I click on the reset button.

**Comment by giangr21** [comment]
Did u figure out ? Im also looking for an answer

**Comment by taras957** [comment]
Any updates here?

**Comment by crobinson42** [comment]
You have to keep a reference to the drawn object if you want to remove it.

**Comment by crobinson42** [comment]
```
 <DrawingManager
            onOverlayComplete={({ overlay, type }) => {

              overlay.setMap(null) // this is important - it REMOVES the overlay from the map immediately 

              setMyLocalStateOverlay(overlay.getPath().getArray())
              }}
              
              ...
/>


{myLocalStateOverlay && 
         <Polygon
              onLoad={(object) => {
                // store a reference to this overlay - to remove it, do: object.setMap(null)
                mapObjectsRef.current.push(object)
              }}

              paths={myLocalStateOverlay}
         />
}
```
