### ISSUE TITLE
How to get updated polygon path data in react js

### ISSUE THREAD

**Issue by bhumi0901** [JustFly1984/react-google-maps-api#892]
I'm using this library for showing a existing polygon same as this example: https://codesandbox.io/s/popr2?file=/src/index.js:144-166

For above example they have used hooks in react js but I want to get paths of polygon without using hooks.
I have tried all possible ways to do it but none of them worked for me.
How can I do that?

**Comment by bhumi0901** [comment]
@JustFly1984 Would you please help me with this?

**Comment by JustFly1984** [comment]
@bhumi0901 sorry hooks is the best way to use React, please use hooks, or make your own implementation.
