### ISSUE TITLE
Add MarkerClusterer support to Marker

### ISSUE THREAD

**Issue by uriklar** [JustFly1984/react-google-maps-api#9]

**Comment by cukas** [comment]
Is there already a date known when the cluster support will be released?

**Comment by JustFly1984** [comment]
@cukas We are a community driven open source, we do not have a schedule. Your PR is welcome.

**Comment by uriklar** [comment]
Hi @cukas. MarkerClusterer support was merged to master and will be released as v1.1.1 today or tomorrow. We'd love your feedback if you want to try it out using the master branch. Maybe you can find some last minute bugs ;-)

**Comment by guins** [comment]
@uriklar I can't get it to work with the master branch as it's missing the `package.json` file, according to npm install error. I would be happy to give you some feedback if I can implement the marker clusterer !

**Comment by JustFly1984** [comment]
@guins I have cloned marker-clusterer-plus as @react-google-maps/marker-clusterer@1.2.0, and it is a dependency of @react-google-maps/api@1.2.0

We have published new docs, demo and examples

**Comment by cukas** [comment]
Now I had time to test the clusters, it works fine only if you load the data via an API, several markers jump out of the cluster. As soon as you move the card they are correct in the cluster again.
