### ISSUE TITLE
LoadScript vs LoadScriptNext

### ISSUE THREAD

**Issue by d1820** [JustFly1984/react-google-maps-api#918]
I am just looking for an explanation of the difference and when you would use one over the other. The documentation is lacking in the project. Any help would be great.

Thanks

**Comment by tusharshuklaa** [comment]
Also, is there any way to initiate the component when I already have the google maps API script loaded from some other sources.

**Comment by vijay94** [comment]
> Also, is there any way to initiate the component when I already have the google maps API script loaded from some other sources.

Any update on the this?
