### ISSUE TITLE
Map not responding to changes in Center & Zoom

### ISSUE THREAD

**Issue by kitlogan** [JustFly1984/react-google-maps-api#958]
Hi - I'm a bit new to this so sorry if this is a stupid question.

I copied the code from the API README, which has given me a component that has Google Maps inside.

BUT in the code if I try to alter the center (lat and lng) values, or the zoom value, it doesn't make any difference to the map that loads?

Currently it loads at somewhere in the pacific ocean (not at the lat & lng found in the code).

Any help welcome! Thanks

**Comment by JustFly1984** [comment]
@kitlogan  please provide minimal reproduction in codesandbox.io
also make sure you use 1.9.5 version.

2.0.0-alpha is not ready yet.

**Comment by kitlogan** [comment]
Hi! Thanks for the response: https://codesandbox.io/s/competent-fire-rx94n?file=/src/App.js

I think that should work, although I've had to remove my API key, but hopefully you can see it loads away from the intended center...

**Comment by JustFly1984** [comment]
@kitlogan  I've found an issue in your code:
https://codesandbox.io/s/peaceful-fire-3ujpb?file=/src/App.js
you are calling 
```
const bounds = new window.google.maps.LatLngBounds();
   map.fitBounds(bounds);
    setMap(map);
```
in onLoad

` new window.google.maps.LatLngBounds()` without passing correct arguments, so it shifts to 0 coords.

I've commented out this part ands added marker with same coords as center and it works as intended

**Comment by kitlogan** [comment]
Hi! Thank you very much for your help! I can see in the codesandbox that the code is working great, however when I copy it into my react app, I get just a grey box? Any ideas? Sorry for my lack of knowledge!

![image](https://user-images.githubusercontent.com/61054641/84249745-0d067500-ab03-11ea-9a47-ff156f3a2b4b.png)

**Comment by iamir4g** [comment]
> Hi! Thank you very much for your help! I can see in the codesandbox that the code is working great, however when I copy it into my react app, I get just a grey box? Any ideas? Sorry for my lack of knowledge!
> 
> ![image](https://user-images.githubusercontent.com/61054641/84249745-0d067500-ab03-11ea-9a47-ff156f3a2b4b.png)

i have same issue!!

**Comment by taijuten** [comment]
@iamir4g are you definitely using version 1.9.5?

Version 2.0.0-alpha has this issue, as per #957

**Comment by cr8tpro** [comment]
I down the version to 1.9.5 and the zoom issue is still occurring.

**Comment by JustFly1984** [comment]
@cr8tpro please provide minimal reproduction in codesandbox.io, and check errors in browser console

**Comment by eggerand13** [comment]
> 
> ` new window.google.maps.LatLngBounds()` without passing correct arguments, so it shifts to 0 coords.
> 
> I've commented out this part ands added marker with same coords as center and it works as intended

What you said is correct. When commenting out the setting of the bounds, the map will automatically center to the defined center coordinates. 
The question is, if this should maybe be changed in the README. As someone who is new to this library/component I found it very confusing that the (only) provided example defined center coordinates which would then be "overwritten" in the viewport by these bounds. Not saying that this is wrong but I guess the example would be easier to understand if the setting of the bounds would not be used (or maybe commented out and just explained?).

**Comment by JustFly1984** [comment]
@eggerand13 If you can add comments to readme, and may be pass some correct argument to `window.google.maps.LatLngBounds()` and create PR, I will merge it asap and it will be published with next version.
