### ISSUE TITLE
StandaloneSearchBox is hidden under Full Screen status of Google Maps

### ISSUE THREAD

**Issue by yhyuan** [JustFly1984/react-google-maps-api#959]
## Environment

os: windows

node --version
v12.1.0
react version
16.13.1
webpack version
N/A
@babel version
N/A
@react-google-maps/api version
1.9.4
## How is it behave?
When the users click on the full screen control, the search box becomes hidden. 
## How should it behave correctly?
The search input box should still be visible. 
## basic implementation of incorrect behavior in codesandbox.com
https://codesandbox.io/s/peaceful-cache-h2m00
https://h2m00.csb.app/

**Comment by guilhermepontes** [comment]
Any updates on this one?

**Comment by JustFly1984** [comment]
@guilhermepontes please provide minimal reproduction in codesandbox.io

**Comment by guilhermepontes** [comment]
@JustFly1984 I am trying to reproduce here but somehow the fullscreen button is not showing up (same as the OP's codesandbox).
But in general is, both `Marker` and `Autocomplete` doesn't show up when you click in the Google Maps integrated fullscreen button.

I didn't implement in my project yet, but I will probably have to recreate this functionality myself and use the requestFullScreen API to do it.

**Comment by pravar-anu** [comment]
@JustFly1984  Any custom component is not rendering after fullscreen.
