### ISSUE TITLE
animation marker

### ISSUE THREAD

**Issue by VuHongViet** [JustFly1984/react-google-maps-api#984]
Hello guys!
How to add animation for marker ?

**Comment by utftufutukgyftryidytftuv** [comment]
you can set manually, for example `BOUNCE` is number `1`
https://github.com/JustFly1984/react-google-maps-api/blob/819c1516da4b76458ca4cc656980f6810db09ebb/packages/react-google-maps-api/src/setup-tests.js#L39

**Comment by utftufutukgyftryidytftuv** [comment]
or `window.google` in browser after load map
